### ISSUE TITLE
is kuiper support multiple mqtt servers?

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1002]
#全局MQTT配置
default:
  qos: 1
  servers: [tcp://127.0.0.1:1883, **tcp//106.14.245.188:1883**] => This configuration does not take effect
  #username: user1
  #password: password
  #certificationPath: /var/kuiper/xyz-certificate.pem
  #privateKeyPath: /var/kuiper/xyz-private.pem.key
  kubeedgeVersion: "1.0"
  kubeedgeModelFile: "mqtt_model.json"

**Comment by ngjaying** [comment]
@nickscut yeah, this is not implemented yet. Right now, we only take the first server. It is designed as an array for the future implementation.

**Comment by nickscut** [comment]
> @nickscut yeah, this is not implemented yet. Right now, we only take the first server. It is designed as an array for the future implementation.

When will the function be realized？

**Comment by ngjaying** [comment]
This is not planned yet. It is quite a standalone feature, are you interested to implement this?
