### ISSUE TITLE
How to optimize kuiperd virtual memory usage

### ISSUE THREAD

**Issue by anilchoudhury** [lf-edge/ekuiper#1013]
Hi,

I am running the kuiperd in our QEMU x86_64 and ARM32 HW(BBB). I see a huge consumption of virtual memory by the process. even when there is no streams or rules in it. 

in KVM (x86_64):
` 360 root     1079m S    /bin/kuiperd`
in BBB (ARM32):
`414 root      847m S    /bin/kuiperd`

When i add one stream and one simple avg rule, i can see the virtual memory gets increased 140MB for x86_64 and 10MB for ARM32.

This memory size looks too much for a edge device.
Can we optimize the virtual memory need for this service?
Do we have flags to enable/disable based on features we need?

**Comment by ngjaying** [comment]
@anilchoudhury This is kind of a "feature" of go. Please check https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory. We cannot do anything about this and it should have no harm.

**Comment by anilchoudhury** [comment]
Thank you.
