### ISSUE TITLE
Can't convert string datetime to kuiper dattime.

### ISSUE THREAD

**Issue by iamonlysaiful** [lf-edge/ekuiper#1014]
Please suggest me what is the proper way to convert or cast string datetime to kuiper datetime.

This is my payload to stream,

`{
...,
  "TimeStamp": "2021-09-19 20:19:28",
...
}`
this is my stream query,
`SELECT cast(json_path_query(events.magtec,"$.TimeStamp"),"datetime") as name  FROM events;`

and this is the error,

` [{"error":"run Select error: call func cast error: parsing time "2021-09-19 20:19:28" as "2006-01-02T15:04:05.000Z07:00": cannot parse " 20:19:28" as "T""}]`

**Comment by SuperRxan** [comment]
Hi @iamonlysaiful 

If you are using string datetime,  the payload  should in this format 
```
payload
{"magtec":"{\"AssetID\":2263,\"Reason\":205,\"TimeStamp\":\"2021-08-09T14:10:05.000Z\"}"}

query
SELECT cast(json_path_query(demo.magtec,"$.TimeStamp"),"datetime") as name FROM demo;

result 
[{"name":"2021-08-09T14:10:05Z"}]
```

you can also use the UnixMilli  with same sql
```
{"magtec":"{\"AssetID\":2263,\"Reason\":205,\"TimeStamp\":13000000000000}"}
```
