### ISSUE TITLE
why kuiper print so many logs?

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1015]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
![image](https://user-images.githubusercontent.com/5253435/134618842-21c79725-9789-461f-b6bc-98ecea0f3886.png)

so many binary logs, how to close it

![image](https://user-images.githubusercontent.com/5253435/134618937-fad62995-d8cd-4d5f-85e6-4e03c2c74032.png)

**Comment by ngjaying** [comment]
Did you have the context for these logs? Each line should have metadat like timestamp and file like below
`time="2021-09-24 13:11:54" level=info msg="Rule rule1 is replaced." file="processor/rule.go:95"`

What file does this log print from?

**Comment by nickscut** [comment]
Some logs are like this：

time="2021-09-24 04:57:44" level=warning msg="sink cache missing response for 0" file="node/sink_node.go:398" rule=POSDEV_2S2D2P_3P_PD_FB_spare_max

**Comment by nickscut** [comment]
time="2021-09-24 05:58:32" level=info msg="save cache for rule POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform, tail: 70, data: map[13:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 68 75 52 95 49 68 48 54 51 48 82 66 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 48 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 55 49 56 49 53 53 54 50 48 48 125 93] 68:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 68 75 52 95 49 68 48 54 52 48 82 66 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 48 44 34 116 115 34 58 49 54 51 50 52 54 51 49 49 49 49 56 50 52 55 52 56 48 48 125 93] 69:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 68 75 52 95 49 68 48 54 51 48 82 66 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 48 44 34 116 115 34 58 49 54 51 50 52 54 51 49 49 49 49 56 50 52 55 52 56 48 48 125 93]]" file="node/sink_cache.go:148" rule=POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform
time="2021-09-24 05:58:32" level=warning msg="sink cache missing response for 68" file="node/sink_node.go:398" rule=POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform
time="2021-09-24 05:58:32" level=info msg="save cache for rule POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform, tail: 98, data: map[10:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 54 49 95 84 71 49 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 54 56 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 52 56 50 48 50 50 57 54 48 48 125 93] 13:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 68 75 52 95 49 68 48 54 51 48 82 66 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 48 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 53 49 56 49 48 56 49 57 48 48 125 93] 17:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 57 49 95 72 69 49 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 54 56 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 53 54 57 53 51 55 54 48 48 48 125 93] 48:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 54 49 95 49 66 48 48 50 57 83 84 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 55 49 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 55 56 50 50 54 50 54 51 48 48 125 93] 58:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 57 49 95 72 69 49 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 55 49 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 56 54 57 55 56 52 51 53 48 48 125 93] 77:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 54 49 95 84 71 49 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 55 51 44 34 116 115 34 58 49 54 51 50 52 54 51 49 48 57 56 50 52 50 50 50 53 48 48 125 93] 87:[91 123 34 97 115 115 101 116 67 111 100 101 34 58 34 84 49 67 49 57 49 95 72 69 49 34 44 34 97 116 116 114 105 98 117 116 101 67 111 100 101 34 58 34 83 101 110 115 111 114 95 83 112 97 114 101 95 56 34 44 34 97 116 116 114 105 98 117 116 101 71 114 111 117 112 78 97 109 101 34 58 34 83 101 110 115 111 114 34 44 34 97 116 116 114 105 98 117 116 101 78 97 109 101 34 58 34 83 112 97 114 101 95 56 34 44 34 99 97 108 86 97 108 117 101 34 58 53 57 50 49 55 51 44 34 116 115 34 58 49 54 51 50 52 54 51 49 49 48 54 57 57 52 54 53 55 48 48 125 93]]" file="node/sink_cache.go:148" rule=POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform
time="2021-09-24 05:58:32" level=info msg="clean the cache and reopen" file="node/sink_cache.go:200" rule=POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform
time="2021-09-24 05:58:32" level=info msg="clean the cache and reopen" file="node/sink_cache.go:200" rule=POSDEV_2S2D2P_3P_PD_FB_sensor_spare_transform

**Comment by nickscut** [comment]
> Did you have the context for these logs? Each line should have metadat like timestamp and file like below
> `time="2021-09-24 13:11:54" level=info msg="Rule rule1 is replaced." file="processor/rule.go:95"`
> 
> What file does this log print from?

My Consumption is too slow?  At present, my rule  will be sent to HTTP rest and mqtt sink at the same time

**Comment by ngjaying** [comment]
Sink may be a little bit slower. I think eKuiper should not print out the cache content, we will make that change.
If you don't need sink cache, you can disable it by setting `disableCache: true` in `kuiper.yaml` to get rid of the logs.

**Comment by nickscut** [comment]
> Sink may be a little bit slower. I think eKuiper should not print out the cache content, we will make that change.
> If you don't need sink cache, you can disable it by setting `disableCache: true` in `kuiper.yaml` to get rid of the logs.

If cache is turned off, what happens when sink is slow? Will the data be lost?

**Comment by ngjaying** [comment]
> > Sink may be a little bit slower. I think eKuiper should not print out the cache content, we will make that change.
> > If you don't need sink cache, you can disable it by setting `disableCache: true` in `kuiper.yaml` to get rid of the logs.
> 
> If cache is turned off, what happens when sink is slow? Will the data be lost?

It will only affect when kuiperd stops abnormally. If the cache is turned on, the cached items will be resent after kuiperd restart.
