### ISSUE TITLE
How to Print Last item of array by dataTemplate?

### ISSUE THREAD

**Issue by iamonlysaiful** [lf-edge/ekuiper#1022]
Help me to Get Last Item of Array.

Bellow code print First Item of Array,

` "dataTemplate": "{\"content\":{{json (index . 0)}}}",`

But I want to Print **Last Item** Of Array.

**Comment by ngjaying** [comment]
I don't know how to do that in a template. The data template syntax is the same as the golang template so you can do some search for how to do that in go. As an alternative In the selection, you can use `[-1]` as the index to get the last item, like `SELECT children[-1] FROM demo`. Check the doc [here](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/json_expr.md#index-expression)

**Comment by iamonlysaiful** [comment]
I tried go lang way  also like this
 `{{json (index .len(json) -1}}`
tried with random pattern. but no luck.

Please help me to find a way.

**Comment by jinfahua** [comment]
Refer to this doc - https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/data_template.md, you can firstly get the array size and then use `add` function to get the index of the last element.

`{{$len := len .values}} {{$loopsize := add $len -1}}`

**Comment by iamonlysaiful** [comment]
@jinfahua Thanks for reply. It helps a lot.
