### ISSUE TITLE
How to keep stream data static

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1040]
I have 4 Streams, ex: S1, S2, S3, S4, and here data for streams S2, S3, S4 will be static(means data which will be given to these streams once in 6 months OR will be given only once for life long). In this situation, I want to execute a RULE (with JOIN) where S1's data will be coming everyday 'n' number of times and at the same time the S2, S3, S4 data needs to be used .

how could i approach to this ?

**Comment by ngjaying** [comment]
Hi @sujith1994 [Table](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/tables.md) should work for your scenario.

**Comment by sujith1994** [comment]
Hi @ngjaying . i have achieved my functionality through external functions. Thanks for the help
