### ISSUE TITLE
why event time does not work

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1050]
stream info:
![image](https://user-images.githubusercontent.com/5253435/139798056-9dd8559c-e6e4-4b38-b4be-71ed5485ac8a.png)

rule info:
![image](https://user-images.githubusercontent.com/5253435/139796699-d109a2ad-9dac-48eb-8b1a-a9775af55eed.png)

mqtt topic payload info:
![image](https://user-images.githubusercontent.com/5253435/139798173-a34b09f0-d1f4-4599-98fe-f7527a6c1c21.png)

event time: between 1635755400000 and 1635757200000  = 2021-11-01 16:30:00 ~2021-11-01 17:00:00

but window_end() return 1635835221279 = 2021-11-02 14:40:21

why window_end() does not return event time, It should be between 2021-11-01 16:30:00 and 2021-11-01 17:00:00

**Comment by ngjaying** [comment]
Hi @nickscut 
To run in event time mode, the rule must specify an option `isEventTime` explicitly as below:
```json
{
  "id": "rule2-1",
  "sql": "SELECT deviceId, window_end() as ts, avg(temperature) as temp, avg(humidity) as hum FROM demo GROUP BY TumblingWindow(ss, 5), deviceId HAVING count(*) > 0",
  "actions": [{"mqtt": {
    "server": "tcp://127.0.0.1:1883",
    "topic": "rule2-1",
    "sendSingle": true
  }}],
  "options": {
    "isEventTime": true,
    "lateTolerance": 100
  }
}
```

Kindly check the doc about the [rule options](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/overview.md#options)
