### ISSUE TITLE
Is stream join support subquery？

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1054]
![image](https://user-images.githubusercontent.com/5253435/140020719-cba73c73-4a66-43ef-998e-cce57ea0b53e.png)
two streams，Take the latest value within the window time，then add latest values。

error message is：
![image](https://user-images.githubusercontent.com/5253435/140020947-098d7a10-d5bf-4fca-b7cf-2a712ac45302.png)

No reason can be found according to the error message

Is the syntax of SQL statement wrong?

**Comment by ngjaying** [comment]
@nickscut Subquery is not supported. We recommend to use "rule pipeline" which you can extract your subquery as a rule and sink the result to a specific mqtt topic. Then your target rule can retrieve those "medium" results from that mqtt topic with  another stream. In the next release 1.4.0, we will introduce an inMemory source to bridge between rules, check [rule pipeline](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/rule_pipeline.md) for more detail.
