### ISSUE TITLE
interval time save bug

### ISSUE THREAD

**Issue by Jadeite09** [lf-edge/ekuiper#1056]
dashboard web set httppull mode,interval: 3600000,but httppull.yaml was interval: 3.60E+06,and get error in log:
```
time="2021-11-03 09:05:12" level=error msg="closing rule zhanku for error: Not valid interval value 0." file="server/ruleManager.go:110"
```

**Environment**:

- eKuiper version (e.g. `1.3.0`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ysfscream** [comment]
Hi, @ngjaying @SuperRxan

When I tested it, I found that the browser did not convert this value.

![image](https://user-images.githubusercontent.com/21299158/142576770-e8b52d59-5b4f-4f1a-8547-da434a9c24ba.png)

The data on return was also not transformed.

![image](https://user-images.githubusercontent.com/21299158/142576824-a571d6e1-abb5-4657-948a-ee006d09975e.png)
