### ISSUE TITLE
stream join is not work

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1057]
stream1 content
![image](https://user-images.githubusercontent.com/5253435/140295268-7b63a153-1763-4bb9-a6c0-2970a086fe7d.png)

stream2 content
![image](https://user-images.githubusercontent.com/5253435/140295299-bc8e1658-4896-48d2-8ed7-38e6e76cef8d.png)

select * from stream_1 as a left join stream_2 as b on a.assetCode = b.assetCode group by TUMBLINGWINDOW(SS, 20);

![image](https://user-images.githubusercontent.com/5253435/140295388-6330bbca-d655-4adf-9878-431494268656.png)

Why  no result returned？I'm sure I have the same assetcode

am I misunderstood？

**Comment by ngjaying** [comment]
Hi nick,  the stream/table alias is not supported in join. Try not using alias. Thanks.

**Comment by nickscut** [comment]
> Hi nick, the stream/table alias is not supported in join. Try not using alias. Thanks.

Alias is not supported. An error message should be reported

**Comment by ngjaying** [comment]
Yeah, you're right. This is actually a known issue #943.  We are going to support this so not validating it
