### ISSUE TITLE
kuiper support the dimension table function or not ?

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1062]
Does Kuiper support the dimension table function similar to flink?

**Comment by ngjaying** [comment]
@nickscut Do you mean [temporal table](https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/dev/table/concepts/legacy/#temporal-table-function)? It is not supported yet, but it is something that we will investigate in the near future.

**Comment by nickscut** [comment]
> temporal table

[https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/dev/table/sql/queries/joins/#temporal-joins](temporal-joins)
I think this feature is very important and I look forward to supporting it in the near future
