### ISSUE TITLE
Array traversing

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1083]
Is it possible to loop through an array in kuiper? @ngjaying 
ex : state :[{"name":MP},{"name":UP}] ,where i need to find if state.name = "UP" (note : i won't be knowing about the index of the array always)

**Comment by ngjaying** [comment]
Could you please try [json path func](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/json_expr.md#json-path-functions)

**Comment by sujith1994** [comment]
@ngjaying But the string comparison is not working it looks like.
 "sql": "SELECT json_path_query(friends, \"$[?(@.first == 'Dale')]\") FROM streamtest" 

Error : run Select error: call func json_path_query error: json_path_query function error: parsing error: $[?(@.first == 'Dale')]\t:1:16 - 1:22 could not parse string: invalid syntax\"}]"

**Comment by sujith1994** [comment]
ok. it works
