### ISSUE TITLE
Shall we support library like `kafka-stream` for ekuiper

### ISSUE THREAD

**Issue by wfnuser** [lf-edge/ekuiper#1088]
Only use `sql` to define rules seems not that powerful.
Maybe we should build a library to let user can run their tasks by writing some code.
Using primitives like `map` `reduce` `filter`...

One way to implement it is just create a language and a compiler, parse user's code to operator graph just like the way we parse sql.
The rules will both support `sql` or `code` as persistent file.

**Comment by ngjaying** [comment]
This is not considered in the short-term.
