### ISSUE TITLE
Batch API invocation for Kuiper instances.

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#1122]

**Comment by saransh14** [comment]
Any updates, by when can the feature for bulk provisioning will be made available in eKuiper?
Currently, we are provisioning single entity for CONF_KEY, STREAM and RULES using the REST APIs available under eKuiper, which is actually a tedious task for configuring around 100 CONF_KEY, STREAM and RULES (in total making upto 300 REST API calls).
To enhance the performance, we actually need the REST APIs that can provisioning the following entities in bulk, resulting in just 3 REST API calls.

**Comment by ngjaying** [comment]
This is not prioritized because it is easy to have a script or small program to bulk creating multiple rules. Are there any problems that a script cannot meet your requirements?

**Comment by saransh14** [comment]
I agree we can anyway develop a small code using which we can perform the bulk provisioning, but just for better performance and optimized approach we wanted the support for bulk provisioning using a single API interface,

**Comment by ngjaying** [comment]
We provide an API to import/export the ruleset, check https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/operation/restapi/ruleset.md. Hope this is what you need.
