### ISSUE TITLE
A problem from kuiper terminal display

### ISSUE THREAD

**Issue by wttt-py** [lf-edge/ekuiper#1127]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
![kuiper2](https://user-images.githubusercontent.com/83765757/147208393-22579ede-7e9d-4e8f-9979-f2cac1f5f16b.png)
![kuiper1](https://user-images.githubusercontent.com/83765757/147209225-582b7885-2d2c-47aa-acb0-7588f78aeff9.png)

As the picture shows，when i test kuiper，find a problem. There is a problem with the digital display，but string no problem. please check it, thanks~

**Comment by ngjaying** [comment]
Do you mean the printed datatype float64? That's a design of golang's json decoder. All numbers are converted to float64. Did you define the stream schema?

**Comment by wttt-py** [comment]
When you share like this，it's no problem.
![kuiper1](https://user-images.githubusercontent.com/83765757/147211289-8bf24c9c-1533-48e3-9eeb-9d76df3120b4.png)
I want to display normally，This is my configuration.
![kp2](https://user-images.githubusercontent.com/83765757/147211331-a85d99dd-f5b2-413b-8e70-74b2ed56a2c8.png)

**Comment by ngjaying** [comment]
The query and log sink are just for debugging so it tries to show more info as much as possible. You could sink it to mqtt or alike which will only display the json string.

**Comment by wttt-py** [comment]
sink it to mqtt is ok~ ,may that's 1.4.0 debug update. thanks for reply.

**Comment by ngjaying** [comment]
Yes, that's intentional. Maybe we should provide a parameter to log sink to allow the old style output.
