### ISSUE TITLE
The plugin make problem

### ISSUE THREAD

**Issue by JasonNing96** [lf-edge/ekuiper#1137]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
When I want to make my plugin at docker-kuiper-dev, some describe comfuse me, hope the the describetion can be more clear. 
![image](https://user-images.githubusercontent.com/54830624/147620670-af672f00-e6bb-4f8e-b6a9-18951ce91c38.png)
Especially, where is the sample.mod, the only file I found here was extension.mod, is it?
By the way, hope update the mysql demo.
Thanks~

**Comment by ngjaying** [comment]
The idea here is to build the plugin from the same path as kuiperd. 

The easiest way is to copy your plugin code directory like `samplePlugin` into eKuiper project and just build from the eKuiper root path.
`go build -trimpath --buildmode=plugin -o $eKuiperPath/_build/$build/plugins/sinks/Mysql@v1.0.0.so samplePlugin/sinks/mysql.go`

In the doc, we tried to not mix the plugin project and the eKuiper but still build from eKuiper path. The sample.mod is created in the step 2 of [compile locally](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md#compile-locally).

**Comment by ngjaying** [comment]
Close becaus it is inactive after months
