### ISSUE TITLE
kuiper docker image

### ISSUE THREAD

**Issue by kush930** [lf-edge/ekuiper#1138]
Hi all,

Issue : Not able docker image ekuiper on target riscv(native build).
Reproduces:
*Git clone https://github.com/lf-edge/ekuiper.git
*Cd ekuiper
*make build_with_edgex
*make pkg_with_edgex

Binary file and package was successful.

but when i am trying for docker image using command
*make docker

Not Working i am getting error: 

docker buildx build --no-cache --platform=linux/amd64 -t lfedge/ekuiper:1.4.0-23-g5515a6c -f deploy/docker/Dockerfile . --load
[+] Building 5.4s (3/3) FINISHED                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                        0.2s
 => => transferring context: 2B                                                                                                          0.1s
 => [internal] load metadata for docker.io/library/golang:1.17.3                                                                         5.2s
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to load LLB: runtime execution on platform linux/amd64 not supported
make: *** [Makefile:72: docker] Error 1

when i changed amd64 to riscv64 in Makefile

then i am facing issue: 
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.4.0-23-g5515a6c -f deploy/docker/Dockerfile . --load
[+] Building 5.0s (5/11)                                                                                                                      
 => [internal] load .dockerignore                                                                                                        0.2s
 => => transferring context: 2B                                                                                                          0.1s
 => [internal] load build definition from Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                      0.0s
 => ERROR [internal] load metadata for docker.io/library/golang:1.17.3                                                                   3.7s
 => [internal] load build context                                                                                                        0.0s
 => ERROR [1/7] FROM docker.io/library/golang:1.17.3                                                                                     1.0s
 => => resolve docker.io/library/golang:1.17.3                                                                                           1.0s
------
 > [internal] load metadata for docker.io/library/golang:1.17.3:
------
------
 > [1/7] FROM docker.io/library/golang:1.17.3:
------
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: no match for platform in manifest sha256:199102125d11c943c927a8a33911ef960ca72c4879e307c7c2e40ceaa72201e3: not found
make: *** [Makefile:72: docker] Error 1

if anything i am missing please guide me.

Thanks,
lavkhush

**Comment by ngjaying** [comment]
@Rory-Z Please take a look

**Comment by kush930** [comment]
hello all,
 
i am facing issue
when i am using **$ make docker ** on **target riscv64** 

root@lavkhush-3:~/ekuiper# make docker
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.4.0-23-g5515a6c -f deploy/docker/Dockerfile . --load
[+] Building 0.2s (5/11)                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                        0.2s
 => => transferring context: 2B                                                                                                          0.1s
 **=> ERROR [internal] load metadata for docker.io/library/golang:1.17.3                                                                   0.0s
 => [internal] load build context                                                                                                        0.0s
 => ERROR [1/7] FROM docker.io/library/golang:1.17.3                                                                                     0.0s
 => => resolve docker.io/library/golang:1.17.3**                                                                                           0.0s
------
 > [internal] load metadata for docker.io/library/golang:1.17.3:
------
------
 > [1/7] FROM docker.io/library/golang:1.17.3:
------
**error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head "https://registry-1.docker.io/v2/library/golang/manifests/1.17.3": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:46951->[::1]:53: read: connection refused
make: *** [Makefile:72: docker] Error 1**

if anything missing, please guide me.

T&R
Kush Kumar

**Comment by Rory-Z** [comment]
Hi, @kush930 
Apologies for the delay, I've just finished my holiday
It looks like the golang image doesn't support riscv64, so you can't pull it, which causes the build to fail

**Comment by kush930** [comment]
> Hi, @kush930 Apologies for the delay, I've just finished my holiday It looks like the golang image doesn't support riscv64, so you can't pull it, which causes the build to fail You can see [this](https://hub.docker.com/layers/golang/library/golang/1.17.3/images/sha256-1c4136362f61a74d9f64fac90226f9da55d8d6b61c316f71bc837fdffe6275e1?context=explore)

**Comment by kush930** [comment]
Hi all,

**Issue : Not able docker image ekuiper on target riscv(native build).**

root@lavkhush-3:~ekuiper# **make docker**
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.4.0-14-g2f9bba1 -f deploy/docker/Dockerfile . --load
[+] Building 655.9s (8/13)
=> [internal] load build definition from Dockerfile 0.1s
=> => transferring dockerfile: 32B 0.0s
=> [internal] load .dockerignore 0.7s
=> => transferring context: 2B 0.6s
=> [internal] load metadata for docker.io/tonistiigi/xx:golang-riscv 0.0s
=> [internal] load build context 5.1s
=> => transferring context: 797.61kB 3.6s
=> CACHED [1/9] FROM docker.io/tonistiigi/xx:golang-riscv 0.0s
=> [2/9] COPY . /go/kuiper 648.3s
=> [3/9] WORKDIR /go/kuiper 0.3s
=> **ERROR [4/9] RUN apt-get update && apt-get install -y pkg-config libczmq-dev 1.4s**
------
> [4/9] **RUN apt-get update && apt-get install -y pkg-config libczmq-dev:**
#8 1.226 {"msg":"exec the container process: Exec format error","level":"error","time":"2022-01-05T11:16:51.000418472Z"}
------
**error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get update && apt-get install -y pkg-config libczmq-dev]: runc did not terminate sucessfully
make: *** [Makefile:72: docker] Error 1**

I have already installed pkg-config and czmq on my target riscv , binary also created, then also i am facing this issue, please guide me, if anything is missing.

T&R
Kush Kumar

**Comment by Rory-Z** [comment]
It looks like you're using a golang image provided by a third party, I'm not sure what it does, maybe you should ask them

**Comment by kush930** [comment]
> It looks like you're using a golang image provided by a third party, I'm not sure what it does, maybe you should ask them

Thank you Rory-z

**Comment by kush930** [comment]
Hi all,

**Issue:- Not able to  build docker image ekuiper on target riscv(native build).** 


root@lavkhush-3:~/ekuiper# make docker
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.4.1-4-g45bbea6 -f deploy/docker/Dockerfile . --load
[+] Building 526.7s (8/11)                                                                                                      
 => [internal] load build definition from Dockerfile                                                                       4.0s
 => => transferring dockerfile: 1.45kB                                                                                     1.0s
 => [internal] load .dockerignore                                                                                          5.6s
 => => transferring context: 2B                                                                                            3.6s
 => [internal] load metadata for docker.io/tonistiigi/xx:golang                                                            9.8s
 => [internal] load build context                                                                                         75.1s
 => => transferring context: 6.61MB                                                                                       70.3s
 => CACHED [1/7] FROM docker.io/tonistiigi/xx:golang@sha256:03e312d98f8db5a7adbf403882347ee4cb620a97bd445b0cfdc8e6b47d3b3  0.1s
 => [2/7] COPY . /go/kuiper                                                                                              363.8s

 => [3/7] WORKDIR /go/kuiper                                                                                              11.3s
 => ERROR [4/7] RUN apt-get update     && yes | apt-get install pkgconfig libczmq-dev wget     && apt-get clean     && r  56.3s
------                                                                                                                          
 > [4/7] RUN apt-get update     && yes | apt-get install pkgconfig libczmq-dev wget     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*:

**#8 44.35 executable file not found in $PATH: No such file or directory**
------
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get update     && yes | apt-get install pkgconfig libczmq-dev wget     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*]: runc did not terminate sucessfully
make: *** [Makefile:72: docker] Error 1

please guide me guys , if anything is missing.

T&R
lavkhush
