### ISSUE TITLE
How to get the memory footprint of each rule？

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1150]
We created a lot of rules and found that it would cause the kuiper memory OOM

So I want to know which rule is taking up a lot of memory

**Comment by ngjaying** [comment]
There is no specific method to check the memory usage in rule level. Maybe you could try to isolate the rules and monitor. 
Some suggestions:
1. Use [shared source](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/streams.md#share-source-instance-across-rules) for rules which processing the same stream. 
2. Avoid using **long** window.
