### ISSUE TITLE
Subscription to memory topic does not take effect

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1153]
![image](https://user-images.githubusercontent.com/5253435/149452147-029e958e-3489-432b-884b-cbd4d2a34cfc.png)
Created two rules to subscribe to the corresponding topic，rule name ： test1231_agg_attr2_test_pipeline and test1231_agg_attr2_test_pipeline_history

If rule test1231_agg_attr2_test_pipeline is started, then rule test1231_agg_attr2_test_pipeline_history has no data coming in

If rule test1231_agg_attr2_test_pipeline_history is started, then rule test1231_agg_attr2_test_pipeline has no data coming in

why？

**Comment by nickscut** [comment]
![image](https://user-images.githubusercontent.com/5253435/149453646-ca83e72a-3497-419c-bf52-b78aabe07578.png)

After adjusting the memory topic of another stream, the problem is still the same

**Comment by nickscut** [comment]
Is my usage wrong?

**Comment by nickscut** [comment]
Does memory topic support wildcard subscriptions?

**Comment by ngjaying** [comment]
Do you have another rules sink to that memory topic? If not, there will have no data. 
Check an exmaple [here](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/rule_pipeline.md#usage).

> Does memory topic support wildcard subscriptions?

Yes

**Comment by nickscut** [comment]
![image](https://user-images.githubusercontent.com/5253435/149468229-ab597e86-d9c0-45a9-a163-cc6fc7c87c09.png)

![image](https://user-images.githubusercontent.com/5253435/149468263-ac303916-19cf-45ca-bf62-a48a21c3130e.png)
I'm sure the rule always has data written to the memory topic

More puzzling is：
If rule test1231_agg_attr2_test_pipeline is started, then rule test1231_agg_attr2_test_pipeline_history has no data coming in

If rule test1231_agg_attr2_test_pipeline_history is started, then rule test1231_agg_attr2_test_pipeline has no data coming in

**Comment by ngjaying** [comment]
Could you attach your `data/sqliteKV.db`?

**Comment by nickscut** [comment]
> Could you attach your `data/sqliteKV.db`?

[sqliteKV.db.zip](https://github.com/lf-edge/ekuiper/files/7868820/sqliteKV.db.zip)

**Comment by ngjaying** [comment]
You mqtt streams have some relationship? For example, test1231_Int_004 & test1231_Int_004_history. In my environment, these mqtt streams are all independant. I try publish message to these two stream, and both pipeline rules can receive data correctly. It all works well in my experiment. I suggest you to restart eKuiper, so all the metrics are clean. Then try to send one data manually, and check the metrics of the rules in the pipeline to diagnose.

**Comment by nickscut** [comment]
mqtt streams are all independant, After I deleted kuiper, I started the same problem again, I will check it myself。
thanks

**Comment by ngjaying** [comment]
Thanks @nickscut to update the status. Is the problem resolved? Can you share how?
