### ISSUE TITLE
custom source,  why ctx.GetRuleId() return empty?

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1172]
in my custom mqtt source

func subscribe(ms *MQTTSource, client MQTT.Client, ctx api.StreamContext, consumer chan<- api.SourceTuple) {

......
log.Infof("[topicArray] Successfully subscribe to topic: %s, ruleId: %s, opId: %s, instanceId: %s, rootPath: %s",
					topicArray[i], ctx.GetRuleId(), ctx.GetOpId(), ctx.GetInstanceId(), ctx.GetRootPath())
......
}
 I  want to print ruleId, but ctx.GetRuleId(), ctx.GetOpId() return empty

My usage is wrong?

**Comment by nickscut** [comment]
func (ms *MQTTSource) Close(ctx api.StreamContext) error {

	ctx.GetLogger().Infof("Mqtt Source instance %d Done, ruleId:%s, opId:%s",
		ctx.GetInstanceId(), ctx.GetRuleId(), ctx.GetOpId())
	if ms.conn != nil && ms.conn.IsConnected() && ms.conSel == "" {
		ms.conn.Disconnect(5000)
	}
	if ms.conSel != "" {
		ctx.ReleaseConnection(ms.conSel)
	}
	return nil
}

time="2022-02-09 17:36:52" level=info msg="Mqtt Source instance 0 Done, **ruleId:, opId:**" file="source/mqtt_source.go:355" source_pool=mqtt.pressure_0119_TwoAttrAgg

**Comment by ngjaying** [comment]
Hi @nickscut, I think you are using shared source. Thus, the source itself does not bind to a single rule/op, so that the return ruleId and opId are empty. What do you want to do with ruleId/opId in your source?

**Comment by nickscut** [comment]
I want to try to solve this problem，[https://github.com/lf-edge/ekuiper/issues/1166](url)

I want to record the correspondence of topic, ruleId, consume

**Comment by ngjaying** [comment]
We will assign a ruleId and opId for shared source instance to be able to identify the source instance.
