### ISSUE TITLE
Support Kafka Source and Sink

### ISSUE THREAD

**Issue by yai-dev** [lf-edge/ekuiper#1175]
using [segmentio/kafka-go](https://github.com/segmentio/kafka-go) for Kafka source and sink support.

**Comment by ngjaying** [comment]
Great idea, thanks for brining this up. This could be provided as a plugin. Would you consider to contribute?

**Comment by suenchunyu** [comment]
> Great idea, thanks for brining this up. This could be provided as a plugin. Would you consider to contribute?

Yep, but what confuses me is whether I should include it as part of the extensions package?

**Comment by suenchunyu** [comment]
> > Great idea, thanks for brining this up. This could be provided as a plugin. Would you consider to contribute?
> 
> Yep, but what confuses me is whether I should include it as part of the extensions package?

😒Forget about it, I'll try to put it in the extensions package first.
