### ISSUE TITLE
In EdgexFoundry ,the version of ekuiper is 1.4., if i want to use tdengine,what version of tdengine should i choose

### ISSUE THREAD

**Issue by 1486756632** [lf-edge/ekuiper#1177]
In EdgexFoundry ,the version of ekuiper is 1.4., if i want to use tdengine,what version of tdengine should i choose

**Comment by SuperRxan** [comment]
eKuiper 对 tdengine 是以插件形式支持的, 需要用到 tdengine 的客户端驱动。
用户在使用插件时，需要安装 tdengine client 到宿主机上，然后插件才能工作。其中tdengine client的版本是由用户自己指定
，是由 tdengine server 决定的，意味着tdengine client 与 server 版本号必须一致。
可参考这里的说明 https://github.com/lf-edge/ekuiper/blob/master/docs/zh_CN/extension/native/sinks/tdengine.md#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6

建议您用 1.4 及以后的 kuiper。tdengien 用2.2 及以后版本，目前最新的tdengien为2.4.0.7。如果您用tdengine server 2.4.0.7, 那么安装 kuiper 的 tdengien 插件时，需要指定安装参数为 2.4.0.7

**Comment by watjt** [comment]
@[SuperRxan](https://github.com/SuperRxan)你好，可以提供一个详细一点的tdengine插件安装教程吗？我通过Makefile中提供的方式重新做了一个镜像还是不行，步骤：1. make sinks/tdengine，2. make docker。新容器跑起来日志报错：error in sink sink tdengine not found" file="node/sink_node.go:363" rule=demoRule
