### ISSUE TITLE
Running into performance issues when using shared mqtt connection 

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1179]
Using shared mqtt connection method, create 90 rules, subscribe to 90 mqtt topics, each topic has 200 qps, so a total of 1.8w qps

![image](https://user-images.githubusercontent.com/5253435/154462758-73c33761-775e-40e5-b797-aa89ab1f12cb.png)

The actual qps is less than 1w

![image](https://user-images.githubusercontent.com/5253435/154463074-6ecd7238-97b5-4def-9690-7d29da4d1de0.png)
You can see that tcp recv-q has data accumulation
it should be caused by insufficient consumption capacity of the receiving end

Is there an optimization method? Increase the concurrency of the rule? Increase the size of the consumer channel?

**Comment by nickscut** [comment]
![image](https://user-images.githubusercontent.com/5253435/154607976-76cc8177-f63a-457b-9721-a0973b77a58f.png)

I try to Increase the channel buffer and  Improve the concurrency of rules

Test doesn't work

**Comment by nickscut** [comment]
i think should modify mqtt_source.yaml
![image](https://user-images.githubusercontent.com/5253435/154610655-0869189d-cfd4-44df-963c-11e3a86aafb2.png)

**Comment by nickscut** [comment]
i think should modify mqtt_source.yaml
![image](https://user-images.githubusercontent.com/5253435/154610771-b994b04b-e4d9-415e-963c-71650ae95547.png)

**Comment by jinfahua** [comment]
What's your CPU usage of your server?

**Comment by nickscut** [comment]
16 cores are deployed, but only 3 are occupied

**Comment by jinfahua** [comment]
One possible solution is that you can have several rules, and use the shared subscription as describe in this document - https://www.emqx.io/docs/en/v4.3/advanced/shared-subscriptions.html.

**Comment by nickscut** [comment]
> hi nickscut, what is your wechat ID, we can talk offline
yinxlscut

**Comment by SuperRxan** [comment]
can find your id, please add me Rxan555

**Comment by nickscut** [comment]
![image](https://user-images.githubusercontent.com/5253435/154669407-5dd477c4-fc30-44f0-b642-9021356c64c3.png)
The packet capture shows that the receiving buffer is full, which should be caused by insufficient consumption of the receiver.

**Comment by ngjaying** [comment]
@nickscut It's likely a backpressure, not the problem of the mqtt source. To diagnose this, you could get the status of your rules and check the metrics to see which op has the longest process latency

{
    "source_demo_0_records_in_total":5,
    "source_demo_0_records_out_total":5,
    "source_demo_0_exceptions_total":0,
    "source_demo_0_process_latency_ms":0,
    "source_demo_0_buffer_length":0,
    "source_demo_0_last_invocation":"2020-01-02T11:28:33.054821",
    ... 
    "op_filter_0_records_in_total":5,
    "op_filter_0_records_out_total":2,
    "op_filter_0_exceptions_total":0,
    "op_filter_0_process_latency_ms":0,
    "op_filter_0_buffer_length":0,
    "op_filter_0_last_invocation":"2020-01-02T11:28:33.054821",
    ...
}

**Comment by nickscut** [comment]
The problem is configured with 10 connectionSelectors to solve the performance, the maximum link is 1.5w qps

thanks very much
