### ISSUE TITLE
TDengine plugin support for writing multiple tables with one rule

### ISSUE THREAD

**Issue by watjt** [lf-edge/ekuiper#1189]
**What would you like to be added/modified**:

当前基于个人理解的情况分析：
按照TDengine的一些数据模型建议是“每一种类型的数据采集点需要建立一个超级表”，我理解的是一个resouce需要一张表。edgex通过deviceResources的配置采集的数据封装成了Event发布到了Message Bus，所以表名应该是和Event.SourceName强相关，现在TDengine sink配置只能一条规则指定输出到一张表，这样就需要创建非常多的规则和表，在设备数量较多时配置麻烦，容易出错，后期也不好维护。

例子：
假设我有一个可以采集整数随机数的设备：
Device：Random-Integer-Device
deviceResources：Int8，Int16，Int32，Int64
其中Int64 Event：
{
  "apiVersion": "v2",
  "id": "c16716d2-fae3-4be0-a831-cda966a43a3f",
  "deviceName": "Random-Integer-Device",
  "profileName": "Random-Integer-Device",
  "sourceName": "Int64",
  "origin": 1645255682665528300,
  "readings": [
    {
      "id": "5130f289-fe2f-48c1-8b34-0be075c59bdb",
      "origin": 1645255682665528300,
      "deviceName": "Random-Integer-Device",
      "resourceName": "Int64",
      "profileName": "Random-Integer-Device",
      "valueType": "Int64",
      "value": "3597644989184675085"
    }
  ]
}

需求：
我只需要配置这个设备(SELECT Int8,Int16,Int32,Int64, meta(origin) AS origin FROM demoStream WHERE meta(deviceName)=\"Random-Integer-Device\";)、或者这类设备(SELECT Int8,Int16,Int32,Int64, meta(origin) AS origin FROM demoStream WHERE meta(profileName)=\"Random-Integer-Device\";)的规则就行，当有符合规则的数据到达时可以自动将数据输出到对应的表，如果没有表可以自动创建。如下面的输出信息，这里就应该创建Int8，Int16，Int32，Int64四张超级表，并将数据写到对应的子表。
上面两个=句sql的输出：
time="2022-02-24 12:13:07" level=info msg="sink result for rule log: [{\"Int32\":1848228685,\"origin\":1645704787775620784}]" file="sink/log_sink.go:30" rule=log
time="2022-02-24 12:13:07" level=info msg="sink result for rule log: [{\"Int8\":-103,\"origin\":1645704787783355184}]" file="sink/log_sink.go:30" rule=log
time="2022-02-24 12:13:07" level=info msg="sink result for rule log: [{\"Int16\":-5670,\"origin\":1645704787786572244}]" file="sink/log_sink.go:30" rule=log
time="2022-02-24 12:13:07" level=info msg="sink result for rule log: [{\"Int64\":-2617264970078728365,\"origin\":1645704787829588048}]" file="sink/log_sink.go:30" rule=log

**Why is this needed**:
让使用和维护更简单

**Comment by ngjaying** [comment]
@watjt 这里每条输出都是只写到一个表里，只是这个表名是动态的。这样理解对吗？

**Comment by watjt** [comment]
> @watjt 这里每条输出都是只写到一个表里，只是这个表名是动态的。这样理解对吗？

对的，上面的sql会过滤出：Int8,Int16,Int32,Int64 四种resource的数据，需要将这四种数据分别写到对应的4张表里

**Comment by ngjaying** [comment]
We have updated the doc, https://ekuiper.org/docs/zh/latest/rules/sinks/plugin/tdengine.html#%E8%A7%84%E5%88%99-actions-%E8%AF%B4%E6%98%8E Please chekc if it meets your requirement
