### ISSUE TITLE
String comparison failing in JSON_path_exists

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1194]
**Environment**:
- eKuiper version (e.g. `1.3.0`):  1.4.1-alphine
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:
    Below is my JSON :{
    "clientId": "Shell123",
    "surveyList": [
        {
            "date": 1644484164,
            "flag": "checked"
        }
    ]
}
    json_path_exists(surveyList,\"$..[? (@.flag== checked)]\") --> this one should give me output as flag is == checked but it is not evaluating  true. Please help me

**Comment by ngjaying** [comment]
Try this `json_path_exists(surveyList,"$[? @.flag==\"checked\"]")`

**Comment by sujith1994** [comment]
{
	"triggered": false,
	"id": "pipelines_cathodicprotectionsurvey",
	"sql": "SELECT CASE WHEN (isPersonQualifiedOQP != false) AND (pipelineId != \"pipe32\") AND (json_path_exists(surveyList,\"$..[? (@.flag==\"checked\")]\"))= TRUE THEN \"Success\" ELSE \"failure#CathodicProtectionreport \" END as status_msg,correlationId FROM pipelines_cathodicprotectionsurvey",
	"actions": [
		{
			"log": {}
		}
]
}

Below is the error :Update rule error: Parse SQL SELECT CASE WHEN (isPersonQualifiedOQP != false) AND (pipelineId != "pipe32") AND (json_path_exists(surveyList,"$..[? (@.flag=="checked")]"))= TRUE THEN "Success" ELSE "failure#CathodicProtectionreport " END as status_msg,correlationId FROM pipelines_cathodicprotectionsurvey error: found function call "json_path_exists", expected ), but with "checked"..

**Comment by sujith1994** [comment]
<img width="296" alt="Screenshot 2022-02-28 124622" src="https://user-images.githubusercontent.com/76031439/155940342-dfb99903-8ec5-4aa6-9d4b-340800bc14c0.png">

i have added the rule image..and below is the error:

Update rule error: Parse SQL SELECT CASE WHEN (isPersonQualifiedOQP != false) AND (pipelineId != "pipe32") AND (json_path_exists(surveyList,"$..[? (@.flag=="checked")]"))= TRUE THEN "Success" ELSE "failure#CathodicProtectionreport " END as status_msg,correlationId FROM pipelines_cathodicprotectionsurvey error: found function call "json_path_exists", expected ), but with "checked"..

**Comment by ngjaying** [comment]
You may need to escape \" to \\\" inside the quotes. And could you plese change the jsonpaht, you are still using the old one. The below works for me:
```
{
  "id": "ruleTest",
  "sql": "SELECT json_path_exists(surveyList,\"$[? @.flag==\\\"checked\\\"]\") AS a FROM demo",
  "actions": [{
    "log": {
    }
  }]
}
```

**Comment by sujith1994** [comment]
Thanks @ngjaying . This looks works for me as well
