### ISSUE TITLE
JSON_path functions help

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1207]
Please give me some examples for the following JSON_PATH functions.

1)in
2)=~

Below is my example which is not working.
1)"sql": "SELECT * FROM demo where json_path_exists(demo,\"[? (@.size nin ['s','m'])]\")"

Stream is :-> CREATE STREAM demo(clientId STRING,isPersonQualifiedOQP BOOLEAN,size ARRAY(STRING)) WITH (datasource = \"demo\", FORMAT = \"json\", STRICT_VALIDATION = \"FALSE\")"

data send :-> '{"clientId":"Shell123","isPersonQualifiedOQP":true,"size":["so","mo"]}'

**Comment by ngjaying** [comment]
What's your purpose here? According to the jsonpath syntax, the filter clause can only be used for a list. For example, ``$.size[?(@!="so"&&@!="mo")]``

**Comment by sujith1994** [comment]
Ok, got the resolution for the list matching. 
how do I check against a regular expression?

size:['SMALL','LARGE','EXTRA LARGE']
inside size array, if any of the values contains letter 'L'

**Comment by ngjaying** [comment]
Close as it is inactive for months
