### ISSUE TITLE
How to get twin data from KubeEdge 1.9.2

### ISSUE THREAD

**Issue by liveej** [lf-edge/ekuiper#1231]
I followed this article, but only got null output:
[看KubeEdge和Kuiper携手实现边缘流式数据处理](https://bbs.huaweicloud.com/blogs/239175)

KubeEdge Version:1.9.2
Kuiper Version: 1.4.4

### KubeEdge raw twin data
topic: $hw/events/device/modbus-heater/twin/update/result
data:
```
{
  "event_id": "",
  "timestamp": 1650013336869,
  "twin": {
    "temperature": {
      "actual": {
        "value": "100",
        "metadata": {
          "timestamp": 1650013336869
        }
      },
      "optional": false,
      "metadata": {
        "type": "int"
      }
    }
  }
}
```

### kuiper output
topic: kuiper/result
data:
```
[
  {
    "__meta": {
      "messageid": "0",
      "topic": "$hw/events/device/modbus-heater/twin/update"
    }
  }
]
```

###  Kuiper stream
create stream demo () WITH (FORMAT="JSON",DATASOURCE="$hw/events/device/+/twin/update")
### deviceModels.json
```
{
	"deviceModels": [{
		"name": "modbus-heater",
		"properties": [{
			"name": "temperature",
			"dataType": "int"
		}, {
			"name": "heat-on",
			"dataType": "boolean"
		}]
	}]
}
```

### action:
```
{
  "sql": "SELECT data->temperature->value FROM demo",
  "actions": [
    {
      "log": {}
    },
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "kuiper/result",
        "qos": 1,
        "clientId": "demo"
      }
    }
  ]
}
```

**Comment by ngjaying** [comment]
Thanks for opening this issue. It seems your SQL select does not match the data structure.

Your SQL select `data->temperature->value` means select the `data.temperature.value` in the json structure.
But the raw data does not have that structure. According to your paste data, you may need to select `twin->temperature->actual->value`.

**Comment by liveej** [comment]
> 

Thanks,it worked!
