### ISSUE TITLE
how to get json key from stream mqtt

### ISSUE THREAD

**Issue by xiaoyang-chen** [lf-edge/ekuiper#1238]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:, json like 
{
  "event_id": "",
  "timestamp": 1649994373726,
  "twin": {
    "power-on": {
      "value": "true",
    }
  }
}
the stream input json like above, I need the string "power-on", how can I get it using sql or jsonPath

**Comment by xiaoyang-chen** [comment]
@ngjaying

**Comment by ngjaying** [comment]
Try
`SELECT "power-on"->value FROM youstream`

**Comment by xiaoyang-chen** [comment]
> Try `SELECT "power-on"->value FROM youstream`

by the way, the follow rule cause service kuiper in my test machine

SELECT mqtt(topic) as topic, `timestamp` as ts, json_path_query_first(collect(*)[0], "$.*") as twin_attr_name, json_path_query(twin, "$..actual.value")[0] as twin_attr_val, json_path_query(twin, "$..actual.metadata.timestamp")[0] as twin_attr_ts, json_path_query(twin, "$..metadata.type")[0] as twin_attr_type, json_path_query(twin, "$..optional")[0] as twin_attr_optional FROM demo

log:
● kuiper.service - emqx daemon
     Loaded: loaded (/lib/systemd/system/kuiper.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-04-21 13:58:58 CST; 13min ago
   Main PID: 853 (code=exited, status=2)

4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator.project(0xc0001f0e00, 0x7, 0x8, 0xc0002deb58, 0xc000356de0, 0xc000010078, 0xc0005ba030)
4月 21 13:58:58 V3490 sh[853]:         github.com/lf-edge/ekuiper/internal/topo/operator/project_operator.go:119 +0x1ff
4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator.(*ProjectOp).Apply(0xc000081ea0, 0x15b7958, 0xc0002ea3c0, 0x13d2a60, 0xc000356de0, 0xc000010078, 0xc0005ba030, 0x1, 0x14864b0)
4月 21 13:58:58 V3490 sh[853]:         github.com/lf-edge/ekuiper/internal/topo/operator/project_operator.go:44 +0x5ee
4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).doOp(0xc00085f3c0, 0x15b7958, 0xc0001d0c00, 0xc000142900)
4月 21 13:58:58 V3490 sh[853]:         github.com/lf-edge/ekuiper/internal/topo/node/operations.go:121 +0x4b3
4月 21 13:58:58 V3490 sh[853]: created by github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).Exec
4月 21 13:58:58 V3490 sh[853]:         github.com/lf-edge/ekuiper/internal/topo/node/operations.go:84 +0x1d3
4月 21 13:58:58 V3490 systemd[1]: kuiper.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
4月 21 13:58:58 V3490 systemd[1]: kuiper.service: Failed with result 'exit-code'.

**Comment by xiaoyang-chen** [comment]
> Try `SELECT "power-on"->value FROM youstream`

the json will dynamic change, the string "power-on" will dynamic change, like
{
"event_id": "",
"timestamp": 1649994373726,
"twin": {
"temperature": {
"value": "true",
}
}
}

**Comment by xiaoyang-chen** [comment]
> > Try `SELECT "power-on"->value FROM youstream`
> 
> by the way, the follow rule cause service kuiper crash in my test machine
> 
> SELECT mqtt(topic) as topic, `timestamp` as ts, json_path_query_first(collect(_)[0], "$._") as twin_attr_name, json_path_query(twin, "$..actual.value")[0] as twin_attr_val, json_path_query(twin, "$..actual.metadata.timestamp")[0] as twin_attr_ts, json_path_query(twin, "$..metadata.type")[0] as twin_attr_type, json_path_query(twin, "$..optional")[0] as twin_attr_optional FROM demo
> 
> log: ● kuiper.service - emqx daemon Loaded: loaded (/lib/systemd/system/kuiper.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Thu 2022-04-21 13:58:58 CST; 13min ago Main PID: 853 (code=exited, status=2)
> 
> 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator.project(0xc0001f0e00, 0x7, 0x8, 0xc0002deb58, 0xc000356de0, 0xc000010078, 0xc0005ba030) 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator/project_operator.go:119 +0x1ff 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator.(*ProjectOp).Apply(0xc000081ea0, 0x15b7958, 0xc0002ea3c0, 0x13d2a60, 0xc000356de0, 0xc000010078, 0xc0005ba030, 0x1, 0x14864b0) 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/operator/project_operator.go:44 +0x5ee 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).doOp(0xc00085f3c0, 0x15b7958, 0xc0001d0c00, 0xc000142900) 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/node/operations.go:121 +0x4b3 4月 21 13:58:58 V3490 sh[853]: created by github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).Exec 4月 21 13:58:58 V3490 sh[853]: github.com/lf-edge/ekuiper/internal/topo/node/operations.go:84 +0x1d3 4月 21 13:58:58 V3490 systemd[1]: kuiper.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 4月 21 13:58:58 V3490 systemd[1]: kuiper.service: Failed with result 'exit-code'.

should I open a new issue and provide the env that cause kuiper panic? @ngjaying

**Comment by ngjaying** [comment]
> the json will dynamic change, the string "power-on" will dynamic change, like { "event_id": "", "timestamp": 1649994373726, "twin": { "temperature": { "value": "true", } } }
> 
> I want to write a rule to adapt to it, and get the string like $.twin.first, and when the string "power-on" in the twin I get "power-on", when json is like json above mention, I get "temperature". the json key not the json value

Do you mean you want to iterate over the "twin" map to get the result. If you need a string result, you can do it by settign [sink's dataTemplate property](https://ekuiper.org/docs/en/latest/rules/overview.html#sinks-actions) to convert the format. It adopts [go template syntax](https://stackoverflow.com/questions/21302520/iterating-through-map-in-template) which can iterate over map to transform the format.

**Comment by ngjaying** [comment]
> Need I open a new issue and provide the env that cause kuiper panic? @ngjaying

What's the version do you use?

**Comment by xiaoyang-chen** [comment]
> > Need I open a new issue and provide the env that cause kuiper panic? @ngjaying
> 
> What's the version do you use?

ioct@V3490:~$ kuiper --version
Connecting to 127.0.0.1:20498... 
Kuiper version 1.4.4

**Comment by xiaoyang-chen** [comment]
> > the json will dynamic change, the string "power-on" will dynamic change, like { "event_id": "", "timestamp": 1649994373726, "twin": { "temperature": { "value": "true", } } }
> > I want to write a rule to adapt to it, and get the string like $.twin.first, and when the string "power-on" in the twin I get "power-on", when json is like json above mention, I get "temperature". the json key not the json value
> 
> Do you mean you want to iterate over the "twin" map to get the result. If you need a string result, you can do it by settign [sink's dataTemplate property](https://ekuiper.org/docs/en/latest/rules/overview.html#sinks-actions) to convert the format. It adopts [go template syntax](https://stackoverflow.com/questions/21302520/iterating-through-map-in-template) which can iterate over map to transform the format.

tks, I will try it

**Comment by xiaoyang-chen** [comment]
already fix, close this issue
