### ISSUE TITLE
Updated/Deleted rule logic not affecting in the backend (kuiper alphine 1.3.1)

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1248]
I have created a rule and it's given me the result properly , but after the update on the same rule it still executes the old logic not the updated logic (ps : it's synatx and logics correct)

One more issue  : i have bunch of rule running and for results i'm looking at the /logs where i can see the deleted rules are still executing  (ps: through post man call i have deleted the rule and verfied in GET call that it's not present)

This is not a consistant issue..it's occurs sometime and restarting the docker container solves the issue
I have faced the issue in docker version kuiper alphine 1.3.1 , kindly give an update or step by step procedure to erase this issue out

**Comment by ngjaying** [comment]
Do you have test cases to reproduce the problems?

Also, could you please try with the latest version. Thanks.

**Comment by sujith1994** [comment]
@ngjaying as I mentioned, it comes sometimes and NOT comes in a sequential manner .
currently, I'm using 1.4.x where I don't see this issue in updating the rule.

could you please let me know what is the cause behind it and how this issue is not coming in 1.4.x ?
i have to be bit more confident in using 1.4.x and these kind of issues won't occur again

**Comment by ngjaying** [comment]
There are some fixes against REST API and rule runtime since 1.3.1, you can check the source code history for detail and try to pinpoint the issue.

**Comment by sujith1994** [comment]
@ngjaying Thanks for the reply. i will test well in 1.4.x
