### ISSUE TITLE
Failed to pass parameters to aggregate functions

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1249]
select AssetCode as assetCode, window_start() as winStart, window_end() as ts, stattime(Value, 1024, winStart, ts) as calValue from EL_MODEL_ElValue_4711015124 where Quality = 0 and AttributeName = "Estate" and AttributeGroupName = "group1" group by assetCode, TUMBLINGWINDOW(MI, 1);

stattime is a platform custom function，I want to pass the start and end time of the window to the function

restart rule error: unknown field ts 

![image](https://user-images.githubusercontent.com/5253435/165067822-cf11b56b-4102-4a39-8ec7-82926b1f36ae.png)

**Environment**:

- eKuiper version (`1.4.4`): 
- Hardware configuration (`mac`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by nickscut** [comment]
This problem only occurs if the stream defines a schema

**Comment by ngjaying** [comment]
Thanks, we'll take a look.

**Comment by nickscut** [comment]
select AssetCode as assetCode, window_start() as winStart, window_end() as winEnd, (stattime(object_construct("assetCode",AssetCode,"attributeCode",AttributeCode,"ts",`Timestamp`, "value", Value, "winLen", 1), 1024,winStart,winEnd)) as calValue from EL_MODEL_EState_4711015124 where Quality = 0 and AttributeName = "EState" and AttributeGroupName = "group1" group by assetCode, TUMBLINGWINDOW(MI, 1);

Want to pass the start and end time of the aggregation window to stattime, is there any other way?

**Comment by nickscut** [comment]
(stattime(object_construct("assetCode",AssetCode,"attributeCode",AttributeCode,"ts",Timestamp, "value", Value, "winLen", 1,"winStart", winStart), 1024))

This also prompts an error to write

**Comment by ngjaying** [comment]
@nickscut  Does the temporary fix work for you? If so, we still need to merge the changes into the product, so reopen this.
