### ISSUE TITLE
Regex In SQL

### ISSUE THREAD

**Issue by sujith1994** [lf-edge/ekuiper#1263]
Is it possible to use regex in SQL statements? if yes... please give an example of it

**Comment by ngjaying** [comment]
There are functions like regexp_matches, check https://ekuiper.org/docs/en/latest/sqls/built-in_functions.html#string-functions

**Comment by sujith1994** [comment]
@ngjaying . Can you please confirm the syntax is correct here ?
does the case insensitive syntax is correct?
{
	"id": "RegexCheck",
	"sql": "SELECT CASE WHEN json_path_exists(pipelineList,\"$..[? (@.pipelineId =~ \\\"/abc/i\\\")]\") AND correlationId =\"abccorr123rrt\"  THEN \"Success\" ELSE \"failure#rule conditions not met\" END as status_msg,correlationId FROM controlroom",
	"actions": [
		{
			"log": {}
		},
		{
			"mqtt": {
				"server": "tcp://localhost:60020",
				"topic": "resulttest"
			}
		}
	]
}

**Comment by ngjaying** [comment]
Is it working for you?

**Comment by ngjaying** [comment]
Close for inactive.
