### ISSUE TITLE
Can I compile the version of windows?

### ISSUE THREAD

**Issue by Robinsir** [lf-edge/ekuiper#1270]
Will it be a problem to recompile  into the Windows Platform，Unfamiliar with go language

**Comment by ngjaying** [comment]
It can compile and run in Windows. The known limitation is that the native plugins are not working due to the limitation of go itself. You can also consider running in docker of windows

**Comment by Robinsir** [comment]
> It can compile and run in Windows. The known limitation is that the native plugins are not working due to the limitation of go itself. You can also consider running in docker of windows

Thank you for your reply！
