### ISSUE TITLE
The resource url can not be found

### ISSUE THREAD

**Issue by AetherNeo** [lf-edge/ekuiper#1273]
File: [/docs/zh_CN/tutorials/ai/tensorflow_lite_tutorial.md](https://ekuiper.org/docs/zh/latest/tutorials/ai/tensorflow_lite_tutorial.html

https://www.emqx.io/downloads/kuiper-plugins/v1.1.2/debian/functions/labelImage_amd64.zip 
This url is in the doncument which used to download plugins, but now the page is 404

**Comment by SuperRxan** [comment]
the package download path has beed updated, try this one 
wget https://packages.emqx.net/kuiper-plugins/1.1.2/debian/functions/labelImage_amd64.zip
