### ISSUE TITLE
Can dataTemplate implement the following functions？

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#1279]
Two sinks in one rule, rest sink and mqtt sink

Is there a way to achieve this through dataTemplate, a piece of data is only sent to mqtt, not to rest sink？

**Comment by nickscut** [comment]
"{\"table\":\"%s\",\"data\":[\"{{.assetCode}}\",{{.window_start}}, {{.window_end}}, {{.calValue}}]}";

I want to realize that when the window_start value is greater than 0, it is sent to the rest sink, but it can be sent to the mqtt sink regardless of whether the window_start is greater than 0

**Comment by ngjaying** [comment]
You can specify different dataTempate for different sinks. In the dataTemplate, you should be able to do some filter with `if` syntax. There is a property `omitEmpty` in sink to not sending out if the result is empty, but it is check against the data before transforming by dataTemplate. You may need to customize rest sink to deal with empty transformed data to let it not sending.

**Comment by nickscut** [comment]
Understood， thanks！
