### ISSUE TITLE
Feature Request : support new type for to cast conversion functions: cast(readings,"map")

### ISSUE THREAD

**Issue by MonicaisHer** [lf-edge/ekuiper#1285]
**What would you like to be added/modified**:
I would like to ask for a cast(readings, "map") [conversion function](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/built-in_functions.md#conversion-functions). 

**Why is this needed**:
I published some readings from [openvino](https://github.com/openvinotoolkit/openvino) to [edgex-device-mqtt](https://github.com/edgexfoundry/device-mqtt-go), and it published readings to [edgex](https://github.com/edgexfoundry/edgex-go) :
```json
{
  "objects":[
    {
      "detection":{
        "bounding_box":{
          "x_max":1.0,
          "x_min":0.15396976470947266,
          "y_max":1.0,
          "y_min":0.1287054717540741
        },
        "confidence":0.5291339159011841,
        "label":"bird",
        "label_id":2
      },
      "h":209,
      "roi_type":"bird",
      "w":271,
      "x":49,
      "y":31
    }
  ],
  "resolution":{
    "height":240,
    "width":320
  },
  "timestamp":28285074096
}
```

Due to turning [MQTT topic level](https://github.com/edgexfoundry/device-mqtt-go/blob/main/cmd/res/configuration.toml#L126) on, I got invalida JSON readings with escape from edgex-device-mqtt:
```json
{\"objects\":[{\"detection\":{\"bounding_box\":{\"x_max\":1.0,\"x_min\":0.013755321502685547,\"y_max\":0.9996117949485779,\"y_min\":0.13620954751968384},\"confidence\":0.847626805305481,\"label\":\"train\",\"label_id\":18},\"h\":207,\"roi_type\":\"train\",\"w\":316,\"x\":4,\"y\":33}],\"resolution\":{\"height\":240,\"width\":320},\"timestamp\":30681462808}
```

I tried some functions to process invalid JSON readings in ekuiper's rule, which use edgex as stream:
```
# create a stream
create stream deviceMqttStream '() WITH (FORMAT="JSON",TYPE="edgex")'

# 1.
Create rule error : Parse rule 
{
  "sql":"SELECT regexp_replace(json, "\\\"" , """) as result from EdgeXStream",
 "actions": [
    {
     "log":{}
   },
    {
      "edgex": {
       "connectionSelector": "edgex.redisMsgBus",
        "topicPrefix": "rules-events",
        "messageType": "event",
        "profileName": "ekuiperProfile",
        "deviceName": "ekuiper",        
        "contentType": "application/json"
      }
    }
  ]
} error : invalid character '\\' after object key:value pair..

# 2.
regexp_replace(json, "\", "")
error: found function call "regexp_replace", expected ), but with "\") from EdgeXStream".

# 3.
regexp_replace(json, "\\\\\"" , "\"")
I got invalid JSON with triple escapes now: {\\\"label\\\":\\\"car\\\"}
```
I could not find a way to make a invalid JSON obeject (string) to a valid JSON obejct. It would be nice if there is a conversion function cast(readings,"map").

Thank you in advance!

**Comment by ngjaying** [comment]
@MonicaisHer The dataTemplate may address your problem: https://ekuiper.org/docs/en/latest/rules/overview.html#sinks-actions

**Comment by ngjaying** [comment]
`SELECT json_path_query(json, "$") AS result FROM EdgeXStream`  This can convert json string to an object

**Comment by MonicaisHer** [comment]
@ngjaying Thank you!
 
`SELECT json_path_query(json, "$") AS result FROM EdgeXStream` works for me!

I also tried setting `"dataTemplate": "{{.json}}"` in my edgex sink, but I didn't see a difference in the result. Does the dataTemplate work for edgex sink?

**Comment by ngjaying** [comment]
Yes, dataTemplate is not parsed in EdgeX sink now. We will fix this
