### ISSUE TITLE
Offline storage for sink

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#1289]
Design update https://github.com/lf-edge/ekuiper/wiki/Feature-1289-Data-Caching-Mechanism

**Comment by antouanbg** [comment]
is the problem same getting Cannot fetch plugin list from https://www.emqx.io/downloads/kuiper-plugins/1.0.2/debian/sinks, with status error: 404 when we try to install the plugin from the web management interface?

**Comment by ngjaying** [comment]
No, this is about the error handling for sink. If network failure or other failure causes sink failure, we will save the data in memory + disk and resend when the failures are recovered. We will update more detail later.

The problem you mentioned is because we migrate plugin storage to aws, and it now doesn't support to access the directory level. 1.0.2 is too old, the new versions of dashboard should not have this error any more.

**Comment by ngjaying** [comment]
What version do you use? This problem should have disappeared since 1.4.x. Here is the docker hub link https://registry.hub.docker.com/r/emqx/ekuiper-manager

**Comment by antouanbg** [comment]
Thank you! I updated to the latest gratest!
