### ISSUE TITLE
I create multiple rules  in edgex with ekuiper 1.5, why is only the last rule in effect?

### ISSUE THREAD

**Issue by zhichuanhe** [lf-edge/ekuiper#1290]
I create multiple rules  in edgex with ekuiper 1.5, why is only the last rule in effect?

**Comment by ngjaying** [comment]
As discussed in WeChat group, the EdgeX source has configured to use MQTT with the same client id. Thus, only one connection can be established due to the client id conflict. Delete the configuration for client id fix this problem.

**Comment by zhichuanhe** [comment]
yes
