### ISSUE TITLE
Problem with grpc in external function

### ISSUE THREAD

**Issue by VeddySama** [lf-edge/ekuiper#1313]
**Sorry this sentence is from google translate.**

**I have a problem with grpc using external functions**.
**The content of the proto file is as follows**：

string name = 3373707;

int32 size = 3530753;

double resolution = 526288726;

string xUnit = 113463836;

string yUnit = 114387357;

string zUnit = 115310878;

repeated double xValue = 240178216;

repeated double yValue = 211549065;

message ListOfListsOfDoubles {
  repeated ListOfDoubles listOfDoubles = 1;
}

message ListOfDoubles {
  repeated double doubles=1;
}

ListOfListsOfDoubles ZValue = 9;
ListOfDoubles ZValueDoubles = 10;

ListOfListsOfDoubles DValue = 11;
ListOfDoubles DValueDoubles = 12;

**The returned data is as follows:**

{
  "code": 200,
  "data": {
    "ZValue": {
    },
    "ZValueDoubles": {
    },
    "DValue": {
    },
    "DValueDoubles": {
    }
  },
  "success": true,
  "message": "Test request succeeded"
}

**As long as there is no ListOfDoubles in ZValue, ekuiper will report the following error:**

goroutine 16 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        C:/Program Files/Go/src/runtime/debug/stack.go:16 +0x19
github.com/lf-edge/ekuiper/pkg/infra.SafeRun.func1()
        E:/Go/ekuiper/pkg/infra/saferun.go:32 +0x45
panic({0x17ee9c0, 0x1ad7ad0})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
reflect.Value.Index({0x17d8ac0?, 0x2136700?, 0x0?}, 0x0?)
        C:/Program Files/Go/src/reflect/value.go:1366 +0x16d
github.com/lf-edge/ekuiper/pkg/cast.ToTypedSlice({0x17d8ac0, 0x2136700?}, 0xc00024cc80, {0x1965bb8, 0x3}, 0x6d?)
        E:/Go/ekuiper/pkg/cast/cast.go:831 +0x133
github.com/lf-edge/ekuiper/internal/service.decodeField({0x17d8ac0?, 0x2136700?}, 0xc0003a5900?, 0x8?)
        E:/Go/ekuiper/internal/service/schema.go:574 +0x3a5
github.com/lf-edge/ekuiper/internal/service.decodeMessageField({0x17d8ac0?, 0x2136700?}, 0xc0003a5900, 0x2c?, 0x0?)
        E:/Go/ekuiper/internal/service/schema.go:519 +0x33
github.com/lf-edge/ekuiper/internal/service.decodeMessage(0x1adebd0?, 0xc000425950)
        E:/Go/ekuiper/internal/service/schema.go:512 +0xef
github.com/lf-edge/ekuiper/internal/service.decodeSubMessage({0x1964220?, 0xc0004d2c30?}, 0x1964220?, 0x1?)
        E:/Go/ekuiper/internal/service/schema.go:620 +0x205
github.com/lf-edge/ekuiper/internal/service.decodeField({0x1964220?, 0xc0004d2c30?}, 0xc0003a5680?, 0xa8?)
        E:/Go/ekuiper/internal/service/schema.go:578 +0x3b0
github.com/lf-edge/ekuiper/internal/service.decodeMessageField({0x1964220?, 0xc0004d2c30?}, 0xc0003a5680, 0x17?, 0x68?)
        E:/Go/ekuiper/internal/service/schema.go:519 +0x33
github.com/lf-edge/ekuiper/internal/service.decodeMessage(0x1adebd0?, 0xc000425860)
        E:/Go/ekuiper/internal/service/schema.go:512 +0xef
github.com/lf-edge/ekuiper/internal/service.decodeSubMessage({0x1964220?, 0xc0004d2c00?}, 0x1964220?, 0x0?)
        E:/Go/ekuiper/internal/service/schema.go:620 +0x205
github.com/lf-edge/ekuiper/internal/service.decodeField({0x1964220?, 0xc0004d2c00?}, 0xc00040c000?, 0x48?)
        E:/Go/ekuiper/internal/service/schema.go:578 +0x3b0
github.com/lf-edge/ekuiper/internal/service.decodeMessageField({0x1964220?, 0xc0004d2c00?}, 0xc00040c000, 0x20?, 0xfb?)
        E:/Go/ekuiper/internal/service/schema.go:519 +0x33
github.com/lf-edge/ekuiper/internal/service.decodeMessage(0xd67778?, 0xc000425c20)
        E:/Go/ekuiper/internal/service/schema.go:512 +0xef
github.com/lf-edge/ekuiper/internal/service.(*wrappedProtoDescriptor).ConvertReturnMessage(0x1adebd0?, {0xc000576e4c?, 0x4?}, 0xc0004afc30?)
        E:/Go/ekuiper/internal/service/schema.go:280 +0x33
github.com/lf-edge/ekuiper/internal/service.(*grpcExecutor).InvokeFunction(0xc00006ddc0, {0x1?, 0xc00024d638?}, {0xc000576e4c, 0x4}, {0xc0004afc30, 0x1, 0x1})
        E:/Go/ekuiper/internal/service/executors.go:182 +0x714
github.com/lf-edge/ekuiper/internal/service.(*ExternalFunc).Exec(0x182dd80?, {0xc0004afc30?, 0xc0004b2dc0?, 0xc0002b40c0?}, {0x1ae8cd8?, 0xc0000045e8?})
        E:/Go/ekuiper/internal/service/externalFunc.go:31 +0x50
github.com/lf-edge/ekuiper/internal/xsql.ExecFunc({0xc0003b5768, 0x4}, {0x1aded50, 0xc0004b2dc0}, {0xc0004afc30, 0x1, 0x1}, {0x1ae8cd8, 0xc0000045e8})
        E:/Go/ekuiper/internal/xsql/func_invoker.go:53 +0x125
github.com/lf-edge/ekuiper/internal/xsql.(*FunctionValuer).Call(0x1849d20?, {0xc0003b5768, 0x4}, 0x4?, {0xc0004afc30, 0x1, 0x1})
        E:/Go/ekuiper/internal/xsql/funcValuer.go:60 +0xbf
github.com/lf-edge/ekuiper/internal/xsql.multiValuer.Call({0xc000735440?, 0x3, 0x0?}, {0xc0003b5768, 0x4}, 0x1862760?, {0xc0004afc30, 0x1, 0x1})
        E:/Go/ekuiper/internal/xsql/valuer.go:346 +0x118
github.com/lf-edge/ekuiper/internal/xsql.(*ValuerEval).Eval(0xc0000045a0, {0x1adc978?, 0xc000172b40?})
        E:/Go/ekuiper/internal/xsql/valuer.go:511 +0xaef
github.com/lf-edge/ekuiper/internal/topo/operator.project({0xc000356280, 0x1, 0xc000735380?}, 0x1ad8e80?)
        E:/Go/ekuiper/internal/topo/operator/project_operator.go:122 +0xef
github.com/lf-edge/ekuiper/internal/topo/operator.(*ProjectOp).Apply(0xc0004b2340, {0x1ae8a80?, 0xc0002b40c0?}, {0x1906640?, 0xc000735380}, 0x21d68f83d01?, 0x0?)
        E:/Go/ekuiper/internal/topo/operator/project_operator.go:45 +0x21d
github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).doOp(0xc000356400, {0x1ae8a80, 0xc0002b4000}, 0xc000621810?)
        E:/Go/ekuiper/internal/topo/node/operations.go:130 +0x508
github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).Exec.func1.1()
        E:/Go/ekuiper/internal/topo/node/operations.go:87 +0x50
github.com/lf-edge/ekuiper/pkg/infra.SafeRun(0x0?)
        E:/Go/ekuiper/pkg/infra/saferun.go:43 +0x62
github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).Exec.func1()
        E:/Go/ekuiper/internal/topo/node/operations.go:86 +0x7c
created by github.com/lf-edge/ekuiper/internal/topo/node.(*UnaryOperator).Exec
        E:/Go/ekuiper/internal/topo/node/operations.go:85 +0x19b

**How should this situation be handled
thanks**

**Comment by VeddySama** [comment]
> @VeddySama The error message is basically saying that the receiving data mismatch the protobuf definition. If something is not required, you can put an optional decorator in your proto file like the doc https://developers.google.com/protocol-buffers/docs/proto?hl=en#simple

I tried to add optional to ZValue/ZValueDoubles/DValue/DValueDoubles but it doesn't seem to work. If you don't transmit these, you will still get an error, and the documentation says that optional and repeated can have zero times.

**Comment by ngjaying** [comment]
Could you please attach your proto file and a sample input json or map that can trigger this problem?

**Comment by VeddySama** [comment]
[proto.zip](https://github.com/lf-edge/ekuiper/files/9016135/proto.zip)
json:
{"p":{"a":1}}

**Comment by ngjaying** [comment]
Thank you, we'll have a look

**Comment by ngjaying** [comment]
PR here https://github.com/lf-edge/ekuiper/pull/1315

**Comment by VeddySama** [comment]
thanks

**Comment by VeddySama** [comment]
> PR here #1315

sorry,I just pulled the updated code of 1.6.0, and there is still a problem. Maybe what I described before is not clear. This problem occurs when grpc calls the external service and receives external service data, that is, when DecodeMessage is used.

**Comment by ngjaying** [comment]
Could you please attach the error log?

**Comment by VeddySama** [comment]
> Could you please attach the error log?

This is my /etc/services file
[services.zip](https://github.com/lf-edge/ekuiper/files/9068411/services.zip)

![image](https://user-images.githubusercontent.com/49411287/177903735-19ca1cc2-4b04-4de6-8610-6365191102e6.png)

![image](https://user-images.githubusercontent.com/49411287/177904612-dd5b33d2-689c-4404-9e1b-285a500b943d.png)

**Comment by ngjaying** [comment]
@VeddySama This is another problem actually. It seems your return message does not match the proto definition. Do you have a sample output hex string? Maybe you can try to decode it [here](https://yura415.github.io/js-protobuf-encode-decode/) to check if the protobuf/message can match.

**Comment by VeddySama** [comment]
> @VeddySama This is another problem actually. It seems your return message does not match the proto definition. Do you have a sample output hex string? Maybe you can try to decode it [here](https://yura415.github.io/js-protobuf-encode-decode/) to check if the protobuf/message can match.

There is something wrong with my return data, thank you for your help
