### ISSUE TITLE
sql alisa work abnormal

### ISSUE THREAD

**Issue by SuperRxan** [lf-edge/ekuiper#1329]
sql:

select lag(Uint16) as lastValue, Uint16 as now, lastValue/now as rate from uint16

 lastValue/now as rate work abnormal

**Environment**: Mac

- eKuiper version (e.g. `1.3.0`):  1.6.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

sql:

select lag(Uint16) as lastValue, Uint16 as now, lastValue/now as rate from uint16

 lastValue/now as rate work abnormal

**How to reproduce it (as minimally and precisely as possible)**:

sql:

select lag(Uint16) as lastValue, Uint16 as now, lastValue/now as rate from uint16

 lastValue/now as rate work abnormal

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
Accordign to SQL92, the alias identifier cannot be used in the select cluase. Because the definition of all fields are considered to be at the same time. Close this as invalid.
