### ISSUE TITLE
Hope the rule doesn't stop when it encounters an error

### ISSUE THREAD

**Issue by JoshRong** [lf-edge/ekuiper#1332]
When I use the rule, there will be some errors when the content is sent incorrectly. I hope that the error can still continue to run instead of requiring me to restart the rule.

**Comment by ngjaying** [comment]
Need more time to design

**Comment by ngjaying** [comment]
Now rules can auto restart with the configured strategy, check this out https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/overview.md#rule-restart-strategy
