### ISSUE TITLE
Invalid cache properties error comes from sink

### ISSUE THREAD

**Issue by MonicaisHer** [lf-edge/ekuiper#1361]
Invalid cache properties come from sink:
- invalid cache properties: bufferPageSize must be positive
- memoryCacheThresholdTooSmall: memoryCacheThreshold must be greater than or equal to bufferPageSize
- maxDiskCacheTooSmall: maxDiskCache must be greater than bufferPageSize

**Environment**:

- eKuiper version (e.g. `1.6.0`): 
- Hardware configuration (e.g. `lscpu`): amd64
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04
- Others:

**What happened and what you expected to happen**:
Rules are stopped by cache errors. They are expected to run without error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install and setup ekuiper and edgex stack:

download snap packaging for edgex-ekuiper 1.6.0 version:
https://github.com/canonical/edgex-ekuiper-snap/suites/7770661283/artifacts/326850811
```
sudo snap install edgex-ekuiper_1.4.4+snap.2+git2.d4283bb_amd64.snap --devmode
sudo snap install edgexfoundry
sudo snap install edgex-device-virtual
sudo snap install edgex-app-service-configurable

sudo snap connect edgexfoundry:edgex-secretstore-token edgex-ekuiper:edgex-secretstore-token

sudo snap restart edgex-ekuiper
sudo snap start edgex-device-virtual
sudo snap start edgex-app-service-configurable
```
2. Create a stream and rules:
```
# stream 1
edgexfoundry.kuiper-cli create stream stream1 '()WITH(FORMAT="JSON",TYPE="edgex",SHARED="false")'

# rule 1 
edgex-ekuiper.kuiper-cli create rule rule_log '
{
   "sql":"SELECT * from stream1",
   "actions":[
      {
         "log":{
            
         }
      }
   ]
}' 

# rules 2
edgex-ekuiper.kuiper-cli create rule rule_edgex_message_bus '
{
   "sql":"SELECT * from stream1",
   "actions": [
      {
         "edgex": {
            "connectionSelector": "edgex.redisMsgBus",
            "topicPrefix": "edgex/events/device", 
            "messageType": "request",
            "deviceName": "device-test"
         }
      }
   ]
}'
```
3.Check rules status:
```
$ edgex-ekuiper.kuiper-cli show rules
time="2022-08-11 16:05:10" level=info msg="Specified Kuiper base folder at location /var/snap/edgex-ekuiper/x2.\n" file="conf/path.go:100"
Connecting to 127.0.0.1:20498... 
[
  {
    "id": "rule_edgex_message_bus",
    "name": "rule_edgex_message_bus",
    "status": "Stopped: invalid cache properties: Get multiple errors: \nbufferPageSize:bufferPageSize must be positive\nmemoryCacheThresholdTooSmall:memoryCacheThreshold must be greater than or equal to bufferPageSize\nmaxDiskCacheTooSmall:maxDiskCache must be greater than bufferPageSize."
  },
  {
    "id": "rule_log",
    "name": "rule_log",
    "status": "Stopped: invalid cache properties: Get multiple errors: \nbufferPageSize:bufferPageSize must be positive\nmemoryCacheThresholdTooSmall:memoryCacheThreshold must be greater than or equal to bufferPageSize\nmaxDiskCacheTooSmall:maxDiskCache must be greater than bufferPageSize."
  }
]
```

**Anything else we need to know?**:
This error has only happened since the 1.6.0 version.

**Comment by ngjaying** [comment]
@MonicaisHer There is an incompatible change in the sink configuration in etc/kuiper.yaml as stated in the release note. I guess you did not update the etc/kuiper.yaml file

**Comment by farshidtz** [comment]
Isn't a minor release expected to be backward compatible with respect to all external APIs (incl. configuration files)? With this breaking change, upgrading from an older 1.x.x version to 1.6.0 will result in errors.

**Comment by ngjaying** [comment]
Did you ship the etc/kuiper.yaml file when installing the snap package? We recommend to update the shipped etc/kuiper.yaml to the latest version then the testing rule should work as before.

**Comment by farshidtz** [comment]
For the snap, the configuration files get deployed on the host on install time. The user can modify them and add/remove fields. On an automatic upgrade, the files don't get replaced with new versions because this will lead to loss of user-defined configurations. Only fresh installation would receive the new configurations. 

Similarly when running this in a Docker container, the user would mount a volume with a custom copy of the configuration files. A minor upgrade to eKuiper should continue to work with user's old configuration files. Otherwise, automated upgrades will simply fail.

Thanks @ngjaying. IMO, this should be fixed and only enforced in a major upgrade.
