### ISSUE TITLE
Hope to support batch acquisition of rules and their status

### ISSUE THREAD

**Issue by heyHui2018** [lf-edge/ekuiper#1385]
Now, to get status, I need to get rules first, and then traverse rules to get status. 

It is hoped that ekuiper can provide an api to get status in batch to improve efficiency. 

It would be better if ekuiper can provide an api to get both rules and status in batch.

**Comment by ngjaying** [comment]
Suggest to use prometheus to get the full status. Check this out: https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/tutorials/usage/monitor_with_prometheus.md
