### ISSUE TITLE
About passing struct parameters to external functions

### ISSUE THREAD

**Issue by VeddySama** [lf-edge/ekuiper#1425]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

The data structure from the custom data source is

```json
{
    "name": "x",
    "size": 1024
}
```

External functions need to pass in the following parameters

```protobuf
message Request {
  Data data = 1;
  string method = 2;
}

message Data {
  string name = 1;
  int32 size = 2;
}

message Response {
  bool success = 1;
  string message = 2;
  int64 code = 3;
}

service TestService {
  rpc testFun(Request) returns (Response) {
    option (google.api.http) = {
      post: "/test"
      body: "*"
    };
  }
}
```

I am using graph rules

How do I pass the data from the datasource as a structure to the external function

```
"testFun(?, \"POST\")"
```

**Comment by ngjaying** [comment]
Make sure your data from the source itself or one of its field matching the request structure and just pass it to the function. For example, if you have the data like：
```json
{
"payload":{"data":{"name":"myname","size":1}, "method":"mymethod"}
}
```
Pass to the func by `testFun(payload)`. 

Given your current data structure, you can pass by

```
testFun(object_construct("data", object_construct("name", name, "size", size), "method", "post"))
```

**Comment by VeddySama** [comment]
> Make sure your data from the source itself or one of its field matching the request structure and just pass it to the function. For example, if you have the data like：
> 
> ```json
> {
> "payload":{"data":{"name":"myname","size":1}, "method":"mymethod"}
> }
> ```
> 
> Pass to the func by `testFun(payload)`.
> 
> Given your current data structure, you can pass by
> 
> ```
> testFun(object_construct("data", object_construct("name", name, "size", size), "method", "post"))
> ```

Thank you very much for your answer, the problem has been solved, the document also describes the object_construct function
