### ISSUE TITLE
Unable to create stream for array with dict

### ISSUE THREAD

**Issue by snzhaoch** [lf-edge/ekuiper#1452]
**Environment**:

- eKuiper version:  lfedge/ekuiper:1.5-slim
- OS: Centos7.6.1810
- Others:
  - docker version: 20.10.17
  - manager: emqx/ekuiper-manager:1.5  

**What happened and what you expected to happen**:
I need use window function with event time, and date structure is a little complex, eg: 

```
{
    "msg_id": 77723123139,
    "time": 1666319677.4842129, 
    "payload": [
        {"name": "ZhangSan", "age": 14},
        {"name": "LiSi", "age": 21}
    ]
}
```

but raise exception when I create stream

**How to reproduce it (as minimally and precisely as possible)**:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/34681764/197103973-c1bf4c89-9ed0-4590-8fed-008dcd5b9cc1.png">

**Comment by ngjaying** [comment]
eKuiper manager is discontinued. Please use CLI or REST API. If you need UI, please reach out for commercial support.
