### ISSUE TITLE
detect offline iot sensor

### ISSUE THREAD

**Issue by pqingshuang** [lf-edge/ekuiper#1470]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi Guys, 

I have a user case that I have some IoT sensors keep posting data to MQTT topic with device ID and other parameters like Co2 and Humidity. Is it possible to set rules that can report IoT sensors that being not active for a while(lets say, three hours)

Thank you so much

**Comment by ngjaying** [comment]
Is it possible to use a tumblingWindow which will trigger in a regular time interval to detect? Like `SELECT \"empty\" as state FROM demo Group By TumblingWindow(ss, 3600) Having count(*) == 0`. Currently, this is not working if there is no events in a timewindow, it won't trigger. We can provide a config to switch on if this can meet your requirement.

**Comment by revozhang** [comment]
> 

Hi ngjaying, this was what I was trying to do some time back. If you can turn this feature on that would be fantastic. Thanks.
