### ISSUE TITLE
Empty window messages can be returned normally

### ISSUE THREAD

**Issue by ivanbearcat** [lf-edge/ekuiper#1486]
- eKuiper version:
  1.7.1

- Hardware configuration:
![image](https://user-images.githubusercontent.com/7564049/200748305-ff108caa-67ae-4ead-91a9-5d8f45d9a69d.png)

- OS (e.g. `cat /etc/os-release`):
  CentOS 8 Linux

I need to return the message when the window message is 0. 
I tested the following statement:
![image](https://user-images.githubusercontent.com/7564049/200749118-2784cb0b-6a2c-42df-a969-0038acb2d05e.png)
When multiple conditions are added after group by, the empty window message will not be returned normally.
Remove the condition and return normally.
![image](https://user-images.githubusercontent.com/7564049/200748577-b46b81ea-ef1c-4787-ab87-e957d9a17027.png)

**Comment by ngjaying** [comment]
This looks like work as design. Because when count == 0, there is actually no entry in the group, thus we cannot selec out the unexisting group value like productId.
