### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by qiulian111** [lf-edge/ekuiper#1493]
when i running the rule and sending mqtt messgaes to ekuiper, it shows 'fatal error: concurrent map writes' and exited 

**Environment**:
- eKuiper version : 1.7.0
- Hardware configuration:
Architecture:         armv7l
Byte Order:           Little Endian
CPU(s):               6
On-line CPU(s) list:  0-2
Off-line CPU(s) list: 3-5
Thread(s) per core:   1
Core(s) per socket:   3
Socket(s):            1
Model:                5
Model name:           ARMv7 Processor rev 5 (v7l)
CPU max MHz:          1104.0000
CPU min MHz:          600.0000
BogoMIPS:             48.00
Flags:                half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae

- Others:
log file and rules as below:
[log.txt](https://github.com/lf-edge/ekuiper/files/10028287/log.txt)
[sourceAndRules.txt](https://github.com/lf-edge/ekuiper/files/10028298/sourceAndRules.txt)

**Comment by ngjaying** [comment]
Fixed at v1.7.2, please try and feel free to reopen for any problems.

**Comment by qiulian111** [comment]
V1.7.2 still has the problem "fatal error: concurrent map read and map write"
[log.txt](https://github.com/lf-edge/ekuiper/files/10051878/log.txt)

**Comment by qiulian111** [comment]
@ngjaying error logs are different , rules are the same

**Comment by ngjaying** [comment]
Merge the fix to v1.7.3 branch. You could try by making from the source code. Thank you
