### ISSUE TITLE
Sink will report an error when I use the LAG function in a CASE statement.

### ISSUE THREAD

**Issue by ivanbearcat** [lf-edge/ekuiper#1514]
- eKuiper version (e.g. `1.3.0`): 
1.7.1
- Hardware configuration (e.g. `lscpu`):
centos8

Sink will report an error when I use the LAG function in a CASE statement.
![142420f004fe6a5f13033c5cc3f60d6](https://user-images.githubusercontent.com/7564049/202688219-04f74dfa-258d-45a0-87a5-d044160e9705.jpg)
![48b80cab2849cf2567fd5540e9e7cd7](https://user-images.githubusercontent.com/7564049/202688250-f3ff71de-264a-4523-a6b8-f37e8e1b5d73.jpg)
Remove the red box and it will work.

**Comment by ngjaying** [comment]
This is reproducible.  The root cause of the problem is that the second lag function in WHERE has an implicit dependency of the first lag call in the case statement, which requires the latter to run before the later one.
