### ISSUE TITLE
If I set a kuiper manager, will the original rest api being blocked?

### ISSUE THREAD

**Issue by pqingshuang** [lf-edge/ekuiper#1532]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I found that if i deploy a kuiper manager, and connect it to ekuiper, i cannot make any change via host:9081. It will report connection refused. 

Is it possible that I can use both UI and rest api to add/update rule?

**Comment by ngjaying** [comment]
Surely you can. I guess your host/ip is not correct when using REST API. If you run eKuiper in docker, remember to export its port.

**Comment by ngjaying** [comment]
Close this as no reponse, feel free to reopen if you still have the problem.

**Comment by pqingshuang** [comment]
Yes, I run into the probelm because i didnt expose the docker port to host port, thanks for your response
