### ISSUE TITLE
Functions from portable plugin not deployed at startup

### ISSUE THREAD

**Issue by webfrank** [lf-edge/ekuiper#1618]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.8.0
- Hardware configuration (e.g. `lscpu`): docker container on linux
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

I packaged an image based on official ekuiper 1.8-slim adding portable plugin files 

I added a ruleset as /kuiper/data/init.json to be deployed at startup. 

One of the rules uses a function exported by the plugin and cannot be loaded. If I remove the use of the function everything works as sources and sinks are already registered. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a portable plugin which exports a function and create a ruleset with a rule using the function. 
Add plugin and ruleset as init.json and start kuiperd, the rule will not be registered as the function is missing. 

**Anything else we need to know?**:

If I deploy the plugin as zip using cli or rest everything works.

**Comment by superrxan** [comment]
hi @webfrank 
thanks for reporting. we have reproduced this bug, will fix in 1.8.1
