### ISSUE TITLE
Usage of tfLite function and video source

### ISSUE THREAD

**Issue by webfrank** [lf-edge/ekuiper#1625]
Hi,
  I was tring to use a video source and tfLite function to create an object detection pipeline.

I'm able to configure the video source using a rtsp camera but cannot use the tfLite function in a query like:

`SELECT tfLite('model', self) FROM video`

where 'model' has been uploaded as model.tflite and 'video' is the source.

Using the video source I only get some logs from ffmpeg starting, if I switch the source to a MQTT topic where I send binary image I got this error:

`time="2023-02-03 15:53:03" level=info msg="sink result for rule inference: {\"error\":\"run Select error: call func tfLite error: tensorflow function requires 1 tensors but got 2\"}" file="sink/log_sink.go:31" rule=inference`

Is tfLite able to process animage or it requires a different input?

A real-life example would be appreciated.

**Comment by ngjaying** [comment]
Hi Francesco, 

In the tfLite function, the tflite model itself should only accept a certain tensor dimensions that usershould know prior to using it. Uses need to preprocess the input arg to meet the tensor requirement. For example, when using the tflite example model [Mobilenet_V1_1.0_224](https://www.tensorflow.org/lite/examples/image_classification/overview#choosing-a-model-architecture), it requires an input of 224x224 pixels. eKuiper provide an image plugin with resize function to do this preprocessing.

```
SELECT tfLite(\"label\", resize(self, 224, 224, true) as result FROM tfdemo
```

This will resize the input image to 224 * 224 and feed it to the tfLite model.

Thanks for trying this out. We definitely need to add tutorials and more preprocess/postprocess function in the future.
