### ISSUE TITLE
Unknown operator type for script node in graph

### ISSUE THREAD

**Issue by revozhang** [lf-edge/ekuiper#1627]
When creating graph with script node in it
```
{
    "type": "operator",
    "nodeType": "script",
    "props": {
        "script": "function exec(msg, meta) { result = {value: 343}; return result;}"
    }
}
```
returns error 
```
"Create rule topo error: unknown operator type script" file="server/rest.go:71
```

**Comment by ngjaying** [comment]
Hello @revozhang

**Comment by revozhang** [comment]
I built it with script and now it works! Thanks.

**Comment by junf-liu** [comment]
> Hello Script 节点未内置到默认的 package/docker 映像中，因为它会增加大小。您可以使用 -slim docker 镜像或使用 build 标签脚本进行构建

Hello, I am still having this error using tag to build containers for the 1.13.4-slim image

error:4000
messsage:unknown operator type script
