### ISSUE TITLE
install influx2 failed

### ISSUE THREAD

**Issue by zhangyongxianggithub** [lf-edge/ekuiper#1739]
install influx2 failed, get 403 response code
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.9.0
- Hardware configuration (e.g. `lscpu`): amd64
- OS (e.g. `cat /etc/os-release`): centos
- Others:

I install ekuiper(1.9.0) /ekuier-manager(latest) in docker on my mac(intel) 。when I install influx2 plugin，I select sinks， then select and then select influx2，a url occur in a input box named file automatically，and then I click Submit，I get 403 error

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/19661416/230546506-14abd708-f3d4-4888-a10e-9a6459dff197.png">

**Comment by ngjaying** [comment]
Could you provide more detail? How do you install?

**Comment by zhangyongxianggithub** [comment]
> Could you provide more detail? How do you install?

I have reedited this question and provided more details

**Comment by ngjaying** [comment]
The influx2 is not built properly, we will update and upload soon.

**Comment by superrxan** [comment]
just upload the plugin. please try again

**Comment by zhangyongxianggithub** [comment]
> just upload the plugin. please try again
I try again and get a fellow error

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/19661416/230588654-2d3d6803-32f6-4fac-84c4-52dde5b781d3.png">

**Comment by superrxan** [comment]
please uninstall the plugin 、restart the ekuiperd and install again.
if this error still happen, please try this  
[influx2_amd64.zip](https://github.com/lf-edge/ekuiper/files/11178166/influx2_amd64.zip)

you just need upload the plugin zip into ekuiper and select it when register influx2
![image](https://user-images.githubusercontent.com/33817352/230593902-de683f86-149b-4684-881b-421c346af589.png)

![image](https://user-images.githubusercontent.com/33817352/230594129-88af17f2-1b41-4814-9bcd-630a67a96518.png)

![image](https://user-images.githubusercontent.com/33817352/230594204-4ca6202f-c97d-46f7-8f3b-0763d98dbda0.png)

**Comment by zhangyongxianggithub** [comment]
> please uninstall the plugin 、restart the ekuiperd and install again. if this error still happen, please try this [influx2_amd64.zip](https://github.com/lf-edge/ekuiper/files/11178166/influx2_amd64.zip)
> 
> you just need upload the plugin zip into ekuiper and select it when register influx2 ![image](https://user-images.githubusercontent.com/33817352/230593902-de683f86-149b-4684-881b-421c346af589.png)
> 
> ![image](https://user-images.githubusercontent.com/33817352/230594129-88af17f2-1b41-4814-9bcd-630a67a96518.png)
> 
> ![image](https://user-images.githubusercontent.com/33817352/230594204-4ca6202f-c97d-46f7-8f3b-0763d98dbda0.png)

It works, thanks very much
