### ISSUE TITLE
Compression/decompression for file connectors

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#1746]
File sink needs the compression to save space.

**What would you like to be added/modified**:

- Compression property for file sink
- Decompression property for file source

**Why is this needed**:
Save space.

**Comment by carlclone** [comment]
Should we create a new file type called 'compressed'? the delimiter seems to be a problem here ,  I was thinking these formats : `lengthOfCompressedBytes | compressAlgorithm | compressedBytes`

or use [avro](https://avro.apache.org/) directly

**Comment by carlclone** [comment]
maybe i overcomplicate it , i was thinking after the json data get compressed , it will become an unstructure byte array , and it can not be separate  after append to  a same file

**Comment by ngjaying** [comment]
In the source side, the operations are reverted: Decompress -> decode.  Just make sure the compression method is lossless, the data can be read correctly.

**Comment by carlclone** [comment]
you mean decompress the whole file when source ? but i am not sure those compress algorithm support append operation when sink , one possible way i can think of is decompress file and append new sink data , then recompress the whole file data .

**Comment by ngjaying** [comment]
Oh, I see. I would like the file sink decompress happens to the whole file, not to a single event. In implementation, I don't know if it can compress incrementally, maybe depends on the compression method. We need to think about that when starting this work.
