### ISSUE TITLE
Feature request: Bearer token authentication via external plug-in

### ISSUE THREAD

**Issue by bnevis-i** [lf-edge/ekuiper#1757]
**What would you like to be added/modified**:

I would like the ability to add a bearer token to outgoing http requests that has been obtained by calling an external plugin module (e.g. a shell script, executable, or other)

**Why is this needed**:

EdgeX 3.0 recently added microservice-level authentication,
and some users use eKuiper to invoke REST APIs of EdgeX core services.
Today, these HTTP requests are performed without authentication,
which means that that such uses require disabling the new security feature.

See: https://github.com/edgexfoundry/edgex-go/issues/4508

It would be very useful to be able to inject a bearer token into outgoing requests,
and since this is a bearer token, the token may be target-specific and have a relative short TTLs,
thus the token must be requestable on a per-request basis.

**Comment by ngjaying** [comment]
@bnevis-i We supports dynamic token and token refresh as documented here https://ekuiper.org/docs/en/latest/guide/sinks/builtin/rest.html. I am not sure if this can fit into 
Core Command request. Do you have doc about the authentication process of Core Command？We can have a try.

I think core command can also be triggered by message bus, this is another alternative way that we plan to update to the docs.

**Comment by bnevis-i** [comment]
Will investigate.  Thank you.

**Comment by bnevis-i** [comment]
@ngjaying 

I did the following but I am getting some errors I don't understand:

I read `ekuiper/docs/en_US/guide/sinks/builtin/rest.md` and modified my rules as follows:

```
cat > rule << EOF
{
   "id":"rest-rule-0",
   "sql":"SELECT * FROM edgexsource WHERE Uint8>=0",
   "actions":[
      {
         "rest":{
            "url":"http://edgex-core-command:59882/api/v2/device/name/Random-Integer-Device/Int16",
            "method":"PUT",
            "dataTemplate":"{\"Int16\":\"123\"}",
            "sendSingle":false,
            "headers": {
              "Authorization": "Bearer {{.access_token}}"
            },
            "oauth": {
              "access": {
                "url": "http://127.0.0.1/api/token",
                "expire": "150"
              }
            }
         }
      }
   ]
}
EOF

curl -X POST -H "Content-Type: application/json" http://localhost:59720/rules -d @rule
```

I created a small flask server to respond to /api/token with an OAuth2 token response similar to that in <https://connect2id.com/products/server/docs/api/token#token-response>

Kuiper seems to be successfully parse the token response:
```
time="2023-04-19 23:18:54" level=info msg="Got access token map[access_token:eyJhbGciOiJFUzM4NCIsImtpZCI6IjRkMGZmMDkxLTU2MzAtM2ViMi0xNjM0LWM0ZDg2NmU1M2U2ZiJ9.eyJhdWQiOiJlZGdleCIsImV4cCI6MTY4MTk0NjQ2MSwiaWF0IjoxNjgxOTQ1NTYxLCJpc3MiOiIvdjEvaWRlbnRpdHkvb2lkYyIsIm5hbWUiOiJydWxlcy1lbmdpbmUiLCJuYW1lc3BhY2UiOiJyb290Iiwic3ViIjoiYjkxMGZhNTAtZTgzOS04MGZmLWFhM2ItNGQ0ZjBmMDU2ZjEyIn0.1UI23Eya8x42V1viU4JttnU55T45yJOG96CMrPSCY2O-S9CE5tVsT-jL-0gSpRvreoviZLtkHi4pHvRTO90Rw4or3TW3gv0XW73Vu4Y7KiRlllNNIM3z8Nu5gtc1yZT7 expires_in:300 token_type:Bearer]" file="http/client.go:243" rule=none
time="2023-04-19 23:18:54" level=info msg="Opening HTTP pull source with conf &{Url:http://edgex-core-command:59882/api/v2/device/name/Random-Integer-Device/Int16 Method:PUT Body: BodyType:json Headers:map[Authorization:Bearer {{.access_token}}] InsecureSkipVerify:true CertificationPath: PrivateKeyPath: RootCaPath: Timeout:5000 DebugResp:false ResponseType:code OAuth:map[access:map[expire:150 url:http://127.0.0.1/api/token]] Interval:10000 Incremental:false SendSingle:false HeadersTemplate: HeadersMap:map[Authorization:Bearer {{.access_token}}]}" file="http/rest_sink.go:38" rule=rest-rule-0
```

However, the following is coming out of the logs:
```
time="2023-04-20 00:05:57" level=warning msg="sink collect error: rest sink headers template decode error: fail to parse the header entry Authorization: template: sink:1:9: executing \"sink\" at <.access_token>: can't evaluate field access_token in type []map[string]interface {}: rest sink fails to send out the data: method=PUT path=\"http://edgex-core-command:59882/api/v2/device/name/Random-Integer-Device/Int16\" request_body=\"{\"Int16\":\"123\"}\"" file="node/sink_node.go:183" rule=rest-rule-0
```

What am I doing wrong?

**Comment by ngjaying** [comment]
@bnevis-i Please set sendSingle to true, otherwise, the data is a []map and the template cannot find {{.access_token}}
