### ISSUE TITLE
Written rule for single device, but sink deploys and run rules to actuate multiple devices

### ISSUE THREAD

**Issue by vediyappan-hcl** [lf-edge/ekuiper#1762]
I have a EdgeX use case where:

1. I send a string from a device via app-service-config,
2. Based on the string received in rules engine, I need to actuate a command to other devices. i.e., if "one" is received I need to turn on GPIO1, if "two" is received I need to turn on GPIO2.

I have added the rules. But when I receive "one", I expect GPIO1 alone need to be turned on, but it actuates the GPIO2 also. I have listed the stream creation, rule and rule1.txt file below. Same way I have rule2 created to turn on another device. Can someone point out where the problem is?

**Stream creation:**

`bin/kuiper create stream demo"() WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"`

**Rule:**

`bin/kuiper create rule myrule1 -f rule1.txt`

**rule1.txt**

```
{
  "sql": "SELECT * FROM demo WHERE myvar = one",
  "actions": [
    {
      "rest": {
        "url": "http://localhost:59882/api/v2/device/name/<deviceName>/<resourceName>",
        "method": "put",
        "dataTemplate": "{\"<resourceName>\":\"true\"}"
      }
    },
    {
      "log":{}
    }
  ]
}

```

**Comment by Rui-Gan** [comment]
hi, could you give me some log information?

**Comment by ngjaying** [comment]
@vediyappan-hcl Check this out: https://ekuiper.org/docs/en/latest/guide/sinks/overview.html#common-properties
The rest url property can use dynamic properties to publish to dynamic urls

**Comment by ngjaying** [comment]
Close this as no response, reopen it if you still have problems.
