### ISSUE TITLE
CHANGED_COLS() function output empty object when nothing changed

### ISSUE THREAD

**Issue by carlclone** [lf-edge/ekuiper#1775]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  latest
- Hardware configuration (e.g. `lscpu`): amd64
- OS (e.g. `cat /etc/os-release`): mac
- Others:

**What happened and what you expected to happen**:
CHANGED_COLS() function output empty object when nothing changed , is this normal ? seems different from doc demo .

now:
SELECT CHANGED_COLS("", true, temperature) FROM a

stream input:
{"temperature": 30, "humidity" : 20}
{"temperature": 30, "humidity" : 20}
{"temperature": 30, "humidity" : 20}
{"temperature": 60, "humidity" : 20}

![image](https://user-images.githubusercontent.com/22807972/231932704-ed533c81-0c12-40f6-8549-21da1ddccc5b.png)
![image](https://user-images.githubusercontent.com/22807972/231932775-e7a154f9-79d0-4525-877b-e8a987677c74.png)

expected:
![image](https://user-images.githubusercontent.com/22807972/231933285-32a4793b-5e09-405f-a7b9-053d2dee06e0.png)
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
It was expected. You can add omitIfEmpty to filter out empty output

```
###
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rule1",
  "sql": "SELECT CHANGED_COLS(\"\", true, temperature) FROM demo",
  "actions": [{
    "mqtt": {
      "server": "tcp://syno.home:1883",
      "topic": "changed/rule1",
      "omitIfEmpty": true,
      "sendSingle": true
    }
  }]
}
```

**Comment by carlclone** [comment]
thanks
