### ISSUE TITLE
Rule node "switch" can not route message correctly according to defined conditions.

### ISSUE THREAD

**Issue by thomasliub** [lf-edge/ekuiper#1782]
Hi guys,

I am tring the "switch" role node. And there is issue found.
When I set two conditions, only the first one can be checked and the logic looks like not as expected.
[rule_2023-4-14 18_11_22.txt](https://github.com/lf-edge/ekuiper/files/11231876/rule_2023-4-14.18_11_22.txt)

**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.9.0
- Hardware configuration (e.g. `lscpu`): amd64 32GRAM
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04
- Others:

**What happened and what you expected to happen**:
I expect the message can be routed to correct sinck based on the condition checked.

**How to reproduce it (as minimally and precisely as possible)**:
I am attaching the rule and stream data.
Stream data:
@starship:/service/ekuiper$ mosquitto_sub -t "ubiot/ts_data"
{"device": "deviceA", "data": {"switch_A": false, "switch_B": false, "time": "2023-04-14 18:15:08"}}
{"device": "deviceB", "data": {"KGG": 65538, "PhV_phsA": 196612, "PhV_phsB": 327686, "time": "2023-04-14 18:15:08"}}
{"device": "deviceA", "data": {"switch_A": false, "switch_B": false, "time": "2023-04-14 18:15:19"}}

Rule file:
Attached

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
Confirm it is a flow editor problem, will route it to the eKuiper manager team.

**Comment by ngjaying** [comment]
Fixed in eKuiper manager 1.9.1
