### ISSUE TITLE
file sink line format incorrect when sink close and reopen

### ISSUE THREAD

**Issue by carlclone** [lf-edge/ekuiper#1815]
when a file is written by sink before and maybe because the ekuiper restart ,  it will reopen the file and append to it , the `\n` is missed at this time because the sink.Written==false

the output of test case:
```
        expected	 "{\"key\":\"value1\"}\n{\"key\":\"value2\"}" 
        but got		 "{\"key\":\"value1\"}{\"key\":\"value2\"}"
```

here is my test case :
```
	err = sink.Configure(map[string]interface{}{
				"path":               tmpfile.Name(),
				"fileType":           tt.ft,
				"hasHeader":          true,
				"format":             f,
				"rollingNamePattern": "none",
				"compress":           tt.compress,
			})
			if err != nil {
				t.Fatal(err)
			}
			err = sink.Open(ctx)
			if err != nil {
				t.Fatal(err)
			}

			// Test collecting a map item
			m := map[string]interface{}{"key": "value1"}
			if err := sink.Collect(vCtx, m); err != nil {
				t.Errorf("unexpected error: %s", err)
			}


			sink.Close(ctx)
			sink = &fileSink{}
			err = sink.Configure(map[string]interface{}{
				"path":               tmpfile.Name(),
				"fileType":           tt.ft,
				"hasHeader":          true,
				"format":             f,
				"rollingNamePattern": "none",
				"compress":           tt.compress,
			})
			if err != nil {
				t.Fatal(err)
			}
			err = sink.Open(ctx)
			if err != nil {
				t.Fatal(err)
			}
			// Test collecting another map item
			m = map[string]interface{}{"key": "value2"}
			if err := sink.Collect(ctx, m); err != nil {
				t.Errorf("unexpected error: %s", err)
			}
			if err = sink.Close(ctx); err != nil {
				t.Errorf("unexpected close error: %s", err)
			}
```

**Environment**:

- eKuiper version (e.g. `1.3.0`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by carlclone** [comment]
suggestion: not allow append to a file when it is closed , two file status (in_progressing , finished ) ,  which also makes the compress algorithm has more  choice (no need to support append)  , but may require a lot of work . 

reference : https://nightlies.apache.org/flink/flink-docs-release-1.13/zh/docs/connectors/datastream/file_sink/

**Comment by ngjaying** [comment]
About suggestion 1, why it may require a lot of work? Is it a good idea to just let it always override an existing file?

**Comment by carlclone** [comment]
just a rough guess , maybe not .   you mean the data before restart does not need retain ?

**Comment by ngjaying** [comment]
Yes, when open a file to write, open with os.O_TRUNC
```
file, err := os.OpenFile("file.txt", os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0644)
```

**Comment by carlclone** [comment]
> Yes, when open a file to write, open with os.O_TRUNC
> 
> ```
> file, err := os.OpenFile("file.txt", os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0644)
> ```

is this final decision ? can i create a pull request

**Comment by ngjaying** [comment]
You are so fast. I think we can do like this. Just remember to document it.

**Comment by ngjaying** [comment]
Try to add a comment if you're working on it
