### ISSUE TITLE
failed : network Error : dial tcp 127.0.0.1:1883: connect: connection refused " file="mqtt/mqtt.go:126"

### ISSUE THREAD

**Issue by ZSYun** [lf-edge/ekuiper#1850]
Environment:

- eKuiper version: lfedge/ekuiper:1.4.4-alpine
- OS: Ubuntu 22.10

What happened and what you expected to happen:
When I created a rule with source from edgex_redis and its action is to connect to a mqtt broker, I got error `The connection to mqtt broker tcp://127.0.0.1:1883 failed : network Error : dial tcp 127.0.0.1:1883: connect: connection refused " file="mqtt/mqtt.go:126`. 
I have no idea how to deal with this issue.

Here is my action setting
![image](https://user-images.githubusercontent.com/57034816/236638565-05463a4b-c807-42c1-9fbb-6f6388fa66ea.png)

Here is my mqtt-broker setting
![image](https://user-images.githubusercontent.com/57034816/236638684-79fafef3-9507-4503-a980-958a050d1163.png)

Here is my docker compose file regarding ruleengine
![image](https://user-images.githubusercontent.com/57034816/236639275-778c61a2-5961-402c-bbfb-2f528d5a99a3.png)

Thanks in advance!

**Comment by ZSYun** [comment]
I change the docker compose as belows
![image](https://user-images.githubusercontent.com/57034816/236640629-9825e471-5b32-4919-93e6-b220dd4b42d9.png)

and setting the action
![image](https://user-images.githubusercontent.com/57034816/236640681-3594c872-288f-40e5-a416-1caf641600a5.png)

It's resolved!

**Comment by ngjaying** [comment]
Just as the error message said, 172.17.0.3 is not accessible. Remember your eKuiper is running in a docker container, not your host machine, make sure it can connect to your broker.

**Comment by ZSYun** [comment]
Thank you! I'm not very familiar with docker networking. It's the host issue and now the problem is well solved.
