### ISSUE TITLE
Add JSON output option to `cli` command

### ISSUE THREAD

**Issue by dcmartin** [lf-edge/ekuiper#186]
Provide option for `cli` command to output JSON rather than human-readable-text (HRT).  For example, currently the output for `docker exec -it kuiper bin/cli describe stream motion` where `motion` is one defined stream, results in:

```
Fields
--------------------------------------------------------------------------------
device	string
camera	string
count	bigint

DATASOURCE: +/+/+/event/end/+
FORMAT: JSON
```

A structured result in JSON would be much more efficient for automating interactions with the CLI in scripts, as well as to provide a simple ReSTful API (which I am about to do).

**Comment by ngjaying** [comment]
> Provide option for `cli` command to output JSON rather than human-readable-text (HRT). For example, currently the output for `docker exec -it kuiper bin/cli describe stream motion` where `motion` is one defined stream, results in:
> 
> ```
> Fields
> --------------------------------------------------------------------------------
> device	string
> camera	string
> count	bigint
> 
> DATASOURCE: +/+/+/event/end/+
> FORMAT: JSON
> ```
> 
> A structured result in JSON would be much more efficient for automating interactions with the CLI in scripts, as well as to provide a simple ReSTful API (which I am about to do).

There is a RESTful API in place, check https://github.com/emqx/kuiper/tree/master/docs/en_US/restapi

**Comment by dcmartin** [comment]
Excellent!  +1 on the REST API.  I will make use of it.  Nonetheless, I think it would be great to have the CLI also provide the option to produce JSON output.

**Comment by jinfahua** [comment]
@dcmartin Are you interested in developing feature ``CLI also provide the option to produce JSON output`` ?  :-)
