### ISSUE TITLE
Call for function implementations

### ISSUE THREAD

**Issue by Yisaer** [lf-edge/ekuiper#1869]
There are some functions we haven't supported in eKuiper. Here are some functions we listed group by the priority. It's always welcome if someone helps to support any of the unimplemented function.

Here is the example for implementation array and object functions https://github.com/lf-edge/ekuiper/pull/1871

If you have any interest for implementing the above functions, plz comment on this issue first in order to avoid do the duplicated work.

## Array functions

https://rockset.com/docs/array-functions/

### High

 * [x] ARRAY_POSITION
 * [x] LENGTH
 * [x] SLICE
 * [x] ELEMENT_AT
 * [x] ARRAY_CONTAINS
 * [x] ARRAY_SORT
 * [x] ARRAY_CONCAT

### Medium

 * [x] ARRAY_CREATE
 * [x] ARRAY_REMOVE
 * [x] ARRAY_LAST_POSTION
 * [x] ARRAY_CONTAINS_ANY
 * [x] ARRAY_INTERSECT
 * [x] ARRAY_UNION
 * [x] ARRAY_MAX
 * [x] ARRAY_MIN
 * [x] ARRAY_EXCEPT
 * [x] REPEAT
 * [x] SEQUENCE

### LOW

 * [x] CARDINALITY
 * [x] ARRAY_FLATTEN
 * [x] ARRAY_DISTINCT
 * [x] ARRAY_MAP
 * [x] ARRY_JOIN
 * [x] ARRAY_SHUFFLE

## Object functions

https://rockset.com/docs/object-functions/

### High

 * [x] ELEMENT_AT
 * [x] LENGTH
 * [x] KEYS
 * [x] VALUES

### Medium

 * [x] OBJECT
 * [x] ZIP
 * [x] ITEMS
 * [x] MERGE
 * [ ] ERASE

**Comment by wangxye** [comment]
Hi, I am interested in this issue. Can I do this task?

**Comment by ngjaying** [comment]
@wangxye Sure, welcome

**Comment by Yisaer** [comment]
> Hi, I am interested in this issue. Can I do this task?

sure, please declare the functions u want to implement before start coding.

**Comment by wangxye** [comment]
I can start with the medium and low priorities of array functions.

**Comment by Tannic-Paprika** [comment]
Hi, I am interested in solving the high and medium priorities of array functions.

**Comment by Yisaer** [comment]
> Hi, I am interested in solving the high and medium priorities of array functions.

Hi, The rest array functions in `Medium` are in working, could u help to work on `array_sort` or `array_concat`?

**Comment by Tannic-Paprika** [comment]
Yeah sure

**Comment by Tannic-Paprika** [comment]
Can you please tell me in which code or where do I exactly implement these functions?

**Comment by hantmac** [comment]
HI, I support `ARRAY_SORT` in this pr https://github.com/lf-edge/ekuiper/pull/2176

**Comment by ngjaying** [comment]
All added. Great teamwork!
