### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by twomorehours** [lf-edge/ekuiper#1890]
File: [/docs/zh_CN/guide/rules/overview.md](https://ekuiper.org/docs/zh/latest/guide/rules/overview.html)

the word "水槽" should be "sink"

**Comment by ngjaying** [comment]
Thank. Welcome to create a PR to fix it?

**Comment by twomorehours** [comment]
> Thank. Welcome to create a PR to fix it?

Okay, I will submit a PR.
