### ISSUE TITLE
rule stop for "EOF error"

### ISSUE THREAD

**Issue by ZSYun** [lf-edge/ekuiper#1893]
I came across these EOF error when running the rule.
![image](https://github.com/lf-edge/ekuiper/assets/57034816/c3223732-df86-46be-ab1d-8af3e675758f)

How can I resolve this problem?

**Comment by ngjaying** [comment]
The MQTT broker close your connection. Could you check your broker log?

**Comment by ngjaying** [comment]
Close as no response. Please reopen it if you still have problems.
