### ISSUE TITLE
why my graph rule dose not work

### ISSUE THREAD

**Issue by zhangyongxianggithub** [lf-edge/ekuiper#1938]
fellow is my graph rule
```json
{
  "id": "rule3",
  "graph": {
    "nodes": {
      "stream_source": {
        "type": "source",
        "nodeType": "mqtt",
        "props": {
          "confKey": "mqtt",
          "datasource": "demo1",
          "format": "json",
          "shared": false
        }
      },
      "window": {
        "type": "operator",
        "nodeType": "window",
        "props": {
          "type": "slidingwindow",
          "unit": "ss",
          "size": 1,
          "interval": 0
        }
      },
      "join": {
        "type": "operator",
        "nodeType": "join",
        "props": {
          "from": "window",
          "joins": [
            {
              "name": "demo2",
              "on": "window.device=demo2.device",
              "type": "full"
            }
          ]
        }
      },
      "sink": {
        "type": "sink",
        "nodeType": "mqtt",
        "props": {
          "server": "tcp://xxx.x.x.x:1883",
          "topic": "result",
          "protocolVersion": "3.1.1",
          "qos": 0,
          "insecureSkipVerify": false,
          "runAsync": false,
          "omitIfEmpty": false,
          "sendSingle": true,
          "bufferLength": 1024,
          "enableCache": false,
          "format": "json"
        }
      }
    },
    "topo": {
      "sources": ["stream_source"],
      "edges": {
        "stream_source": ["window"],
        "window": ["join"],
        "join": ["sink"]
      }
    }
  }
}
```
I hava created a table named demo2 before rule submitted, when I pub message to demo1 via mqtt client, the message pass through source，window，pass into join, but nothing go out of join node, why join does not work
![image](https://github.com/lf-edge/ekuiper/assets/19661416/5c5701f5-4ec7-48a3-8d89-efa6a500b54f)

**Comment by ngjaying** [comment]
You need two streams to join. An example:

```json
{
  "id": "rule1",
  "name": "Group Rule",
  "graph": {
    "nodes": {
      "device1": {
        "type": "source",
        "nodeType": "mqtt",
        "props": {
          "datasource": "devices/1/messages",
          "timestamp": "ts"
        }
      },
      "device2": {
        "type": "source",
        "nodeType": "mqtt",
        "props": {
          "datasource": "devices/2/messages",
          "timestamp": "ts"
        }
      },
      "window": {
        "type": "operator",
        "nodeType": "window",
        "props": {
          "type": "tumblingwindow",
          "unit": "ms",
          "size": 600
        }
      },
      "joinop": {
        "type": "operator",
        "nodeType": "join",
        "props": {
          "from": "device1",
          "joins": [
            {
              "name": "device2",
              "type": "inner",
              "on": "abs(device1.ts - device2.ts) < 200"
            }
          ]
        }
      },
      "groupop": {
        "type": "operator",
        "nodeType": "groupby",
        "props": {
          "dimensions": ["device1.humidity"]
        }
      },
      "countop": {
        "type": "operator",
        "nodeType": "aggfunc",
        "props": {
          "expr": "count(*)"
        }
      },
      "pick": {
        "type": "operator",
        "nodeType": "pick",
        "props": {
          "fields": ["device1.humidity", "count"]
        }
      },
      "mqtt": {
        "type": "sink",
        "nodeType": "mqtt",
        "props": {
          "server": "tcp://syno.home:1883",
          "topic": "devices/result"
        }
      },
      "log": {
        "type": "sink",
        "nodeType": "log",
        "props": {}
      }
    },
    "topo": {
      "sources": ["device1", "device2"],
      "edges": {
        "device1": ["window"],
        "device2": ["window"],
        "window": ["joinop"],
        "joinop": ["groupop"],
        "groupop": ["countop"],
        "countop": ["pick"],
        "pick": ["mqtt", "log"]
      }
    }
  },
  "options": {
    "isEventTime": true,
    "lateTolerance" : 0
  }
}
```

**Comment by zhangyongxianggithub** [comment]
> You need two streams to join. An example:
> 
> ```json
> {
>   "id": "rule1",
>   "name": "Group Rule",
>   "graph": {
>     "nodes": {
>       "device1": {
>         "type": "source",
>         "nodeType": "mqtt",
>         "props": {
>           "datasource": "devices/1/messages",
>           "timestamp": "ts"
>         }
>       },
>       "device2": {
>         "type": "source",
>         "nodeType": "mqtt",
>         "props": {
>           "datasource": "devices/2/messages",
>           "timestamp": "ts"
>         }
>       },
>       "window": {
>         "type": "operator",
>         "nodeType": "window",
>         "props": {
>           "type": "tumblingwindow",
>           "unit": "ms",
>           "size": 600
>         }
>       },
>       "joinop": {
>         "type": "operator",
>         "nodeType": "join",
>         "props": {
>           "from": "device1",
>           "joins": [
>             {
>               "name": "device2",
>               "type": "inner",
>               "on": "abs(device1.ts - device2.ts) < 200"
>             }
>           ]
>         }
>       },
>       "groupop": {
>         "type": "operator",
>         "nodeType": "groupby",
>         "props": {
>           "dimensions": ["device1.humidity"]
>         }
>       },
>       "countop": {
>         "type": "operator",
>         "nodeType": "aggfunc",
>         "props": {
>           "expr": "count(*)"
>         }
>       },
>       "pick": {
>         "type": "operator",
>         "nodeType": "pick",
>         "props": {
>           "fields": ["device1.humidity", "count"]
>         }
>       },
>       "mqtt": {
>         "type": "sink",
>         "nodeType": "mqtt",
>         "props": {
>           "server": "tcp://syno.home:1883",
>           "topic": "devices/result"
>         }
>       },
>       "log": {
>         "type": "sink",
>         "nodeType": "log",
>         "props": {}
>       }
>     },
>     "topo": {
>       "sources": ["device1", "device2"],
>       "edges": {
>         "device1": ["window"],
>         "device2": ["window"],
>         "window": ["joinop"],
>         "joinop": ["groupop"],
>         "groupop": ["countop"],
>         "countop": ["pick"],
>         "pick": ["mqtt", "log"]
>       }
>     }
>   },
>   "options": {
>     "isEventTime": true,
>     "lateTolerance" : 0
>   }
> }
> ```

but one of join expression is a table not a mqtt stream？

**Comment by ngjaying** [comment]
Do you mean you want to join stream and table? That is only supported since 1.10. And you'll need to define a lookup table before using it in Graph. Scan table is not supported.

Example:
1. Define the table
```
###
POST http://{{host}}/tables
Content-Type: application/json

{"sql":"CREATE TABLE alertTable() WITH (DATASOURCE=\"alertVal\", TYPE=\"redis\", KIND=\"lookup\", KEY=\"id\")"}
```
2. Rule
```
{
  "id": "ruleAlert",
  "graph": {
    "nodes": {
      "demo": {
        "type": "source",
        "nodeType": "mqtt",
        "props": {
          "sourceType": "stream",
          "sourceName": "demo"
        }
      },
      "alertTable": {
        "type": "source",
        "nodeType": "memory",
        "props": {
          "sourceType": "table",
          "sourceName": "alertTable"
        }
      },
      "joinop": {
        "type": "operator",
        "nodeType": "join",
        "props": {
          "from": "demo",
          "joins": [
            {
              "name": "alertTable",
              "type": "inner",
              "on": "demo.deviceKind = alertTable.id"
            }
          ]
        }
      },
      "log": {
        "type": "sink",
        "nodeType": "log",
        "props": {}
      }
    },
    "topo": {
      "sources": ["demo", "alertTable"],
      "edges": {
        "demo": ["joinop"],
        "alertTable": ["joinop"],
        "joinop": ["log"]
      }
    }
  }
}
```

**Comment by zhangyongxianggithub** [comment]
> ble is not supported.

OK，thanks， but when I submit the source def using sourceName and sourceType，ekuiper response an error like empty topic

**Comment by ngjaying** [comment]
> > ble is not supported.
> 
> OK，thanks， but when I submit the source def using sourceName and sourceType，ekuiper response an error like empty topic

You'll need to create the stream with that name prior to create this graph rule; Just like using SQL rule, create the stream/table before creating the rule. Then, make sure your stream has the `dataSource` property set. If the type is mqtt, no dataSource set will get that empty topic error. Example: 

```
### The stream to update state
POST http://{{host}}/streams
Content-Type: application/json

{"sql":"CREATE STREAM stateStream() WITH (TYPE=\"mqtt\",FORMAT=\"json\",DATASOURCE=\"demo/state\",SHARED=\"true\");"}
```

**Comment by ngjaying** [comment]
Is this ok for you? I'll close this since no response. Please reopen it if you still find problems.
