### ISSUE TITLE
MQTT5 support

### ISSUE THREAD

**Issue by vincent-vinf** [lf-edge/ekuiper#1940]
**What would you like to be added/modified**:
MQTT5 support.
According to the [documentation](https://ekuiper.org/docs/en/latest/guide/sources/builtin/mqtt.html#protocolversion), ekuiper only supports mqtt 3.1 and 3.1.1. Is there any plan to support mqtt5?

**Why is this needed**:

We need new features of mqtt5, such as shared subscriptions.

**Comment by ngjaying** [comment]
Thanks for raising this problem. We will investigate. If you only need shared subscription, you can use EMQX broker which can support it with 3.1.1 client.

**Comment by ngjaying** [comment]
After some research, we did not find mature MQTT v5 go client. We may need to pause and wait until we have  suitable client.
