### ISSUE TITLE
window_start() return current system time when testing with "isEventTime": true

### ISSUE THREAD

**Issue by xiaoyanc** [lf-edge/ekuiper#1976]
Regarding the window function window_start() there is an issue when testing with TUMBLINGWINDOW and "isEventTime": true. During the first trigger of the window, window_start() returns the current system time instead of the normal window trigger start time base on eventTime. Subsequent triggers of window_start() return the expected window trigger start time.

**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.8.1 and 1.10.0
- Hardware configuration (e.g. `lscpu`): using docker test
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

The window_start() in the first record was the current system time.
I expected it was the normal window trigger start time base on eventTime. 

**How to reproduce it (as minimally and precisely as possible)**:
streams:
{ "sql": "create stream edge_app_source() WITH (FORMAT=\"JSON\", DATASOURCE=\"edge-app-source\", KEY=\"deviceId\", TIMESTAMP=\"ts\", SHARED=\"true\")" }
{ "sql": "create stream app_internal_comp1() WITH (FORMAT=\"JSON\", DATASOURCE=\"app_internal_comp1\", TYPE=\"memory\", KEY=\"deviceId\", TIMESTAMP=\"ts\")" }
{ "sql": "create stream app_internal_comp2() WITH (FORMAT=\"JSON\", DATASOURCE=\"app_internal_comp2\", TYPE=\"memory\", KEY=\"deviceId\", TIMESTAMP=\"ts\")" }

rules:
{
    "id": "app_internal_comp1",
    "sql": "SELECT CASE  WHEN online = false THEN -1  WHEN EPPIncrement < 0.2 THEN 0  WHEN (EPPIncrement >= 0.2) AND (EPPIncrement <= 0.5) THEN 1  WHEN EPPIncrement >= 0.5 THEN 2  ELSE nil END as WorkingStatus, * FROM edge_app_source",
    "actions": [
        {
            "memory": {
                "sendSingle": true,
                "topic": "app_internal_comp1"
            }
        },
        {
            "log": {}
        }
    ]
}

{
    "id": "app_internal_comp2",
    "sql": "SELECT CASE  WHEN true THEN (lag(WorkingStatus) OVER (PARTITION BY deviceId WHEN isNull(WorkingStatus)=false))  ELSE nil END as LastWorkingStatus, * FROM app_internal_comp1",
    "actions": [
        {
            "memory": {
                "sendSingle": true,
                "topic": "app_internal_comp2"
            }
        },
        {
            "log": {}
        }
    ]
}

{
    "id": "app_workingstatus_sum1",
    "sql": "SELECT CASE WHEN LastWorkingStatus=2 THEN sum(cast(DurationInstant, \"bigint\")) ELSE 0 END as DurationWork, CASE WHEN LastWorkingStatus=1 THEN sum(cast(DurationInstant, \"bigint\")) ELSE 0 END as DurationStandby, CASE WHEN LastWorkingStatus=0 THEN sum(cast(DurationInstant, \"bigint\")) ELSE 0 END as DurationShutdown, CASE WHEN LastWorkingStatus=-1 THEN sum(cast(DurationInstant, \"bigint\")) ELSE 0 END as DurationOffline, CASE WHEN LastWorkingStatus=2 THEN sum(cast(EPPIncrement, \"float\")) ELSE 0.0 END as WorkEPP, CASE WHEN LastWorkingStatus=1 THEN sum(cast(EPPIncrement, \"float\")) ELSE 0.0 END as StandbyEPP, CASE WHEN LastWorkingStatus=0 THEN sum(cast(EPPIncrement, \"float\")) ELSE 0.0 END as ShutdownEPP, window_start() as tsStart, window_end() as tsEnd, window_end()-60000 as ts, deviceId, modelId FROM app_internal_comp2 GROUP BY deviceId, LastWorkingStatus, TUMBLINGWINDOW(mi, 1)",
    "actions": [
        {
            "mqtt": {
                "sendSingle": true,
                "server": "tcp://mqtt-broker:1883",
                "topic": "app_workingstatus_sum1"
            }
        }
    ],
    "options": {
        "isEventTime": true,
        "lateTolerance": 100
    }
}

Test data:
mosquitto_pub -h 127.0.0.1 -p 1883 -t edge-app-source -m \
'{
  "deviceId": "462752654293008397",
  "modelId": "461751264330448915",
  "ts" : 1684810000000,
  "online": true,
  "EPPIncrement": 0,
  "DurationInstant": 0,
  "Ia": 10
}'

mosquitto_pub -h 127.0.0.1 -p 1883 -t edge-app-source -m \
'{
  "deviceId": "462752654293008397",
  "modelId": "461751264330448915",
  "ts" : 1684810001000,
  "online": true,
  "EPPIncrement": 0.15,
  "DurationInstant": 1000,
  "Ia": 20
}'

mosquitto_pub -h 127.0.0.1 -p 1883 -t edge-app-source -m \
'{
  "deviceId": "462752654293008397",
  "modelId": "461751264330448915",
  "ts" : 1684810002000,
  "online": true,
  "EPPIncrement": 0.35,
  "DurationInstant": 1000,
  "Ia": 30
}'

mosquitto_pub -h 127.0.0.1 -p 1883 -t edge-app-source -m \
'{
  "deviceId": "462752654293008397",
  "modelId": "461751264330448915",
  "ts" : 1684810082000,
  "online": true,
  "EPPIncrement": 0.65,
  "DurationInstant": 80000,
  "Ia": 36
}'

mosquitto_pub -h 127.0.0.1 -p 1883 -t edge-app-source -m \
'{
  "deviceId": "462752654293008397",
  "modelId": "461751264330448915",
  "ts" : 1684810182000,
  "online": true,
  "EPPIncrement": 0.75,
  "DurationInstant": 100000,
  "Ia": 37
}'

window result:
mosquitto_sub -h 127.0.0.1 -p 1883 -t app_workingstatus_sum1
{"DurationOffline":0,"DurationShutdown":0,"DurationStandby":0,"DurationWork":0,"ShutdownEPP":0,"StandbyEPP":0,"WorkEPP":0,"deviceId":"462752654293008397","modelId":"461751264330448915","ts":1684809960000,"tsEnd":1684810020000,"tsStart":1686101302288}
{"DurationOffline":0,"DurationShutdown":2000,"DurationStandby":0,"DurationWork":0,"ShutdownEPP":0.5,"StandbyEPP":0,"WorkEPP":0,"deviceId":"462752654293008397","modelId":"461751264330448915","ts":1684809960000,"tsEnd":1684810020000,"tsStart":1686101302288}
{"DurationOffline":0,"DurationShutdown":0,"DurationStandby":80000,"DurationWork":0,"ShutdownEPP":0,"StandbyEPP":0.65,"WorkEPP":0,"deviceId":"462752654293008397","modelId":"461751264330448915","ts":1684810080000,"tsEnd":1684810140000,"tsStart":1684810080000}

**Anything else we need to know?**:
This issue was also found in the the simple time window rule:
{
    "id": "app_w1",
    "sql": "SELECT avg(EPPIncrement) as avg1, window_start() as tsStart, window_end() as tsEnd, window_end()-60000 as ts, deviceId as device_id, modelId as model_id FROM edge_app_source GROUP BY deviceId, TUMBLINGWINDOW(mi, 1)",
    "actions": [
        {
            "mqtt": {
                "sendSingle": true,
                "server": "tcp://mqtt-broker:1883",
                "topic": "app_w1"
            }
        }
    ],
    "options": {
        "isEventTime": true,
        "lateTolerance": 100
    }
}

**Comment by ngjaying** [comment]
Thank you. We'll take a look
