### ISSUE TITLE
source props in graph rule

### ISSUE THREAD

**Issue by loleek** [lf-edge/ekuiper#1989]
Here's a confuse about why not allow inject source configurations from graph rule in props field.
For example, if I create a mqtt source in graph rule, I cannot set server / username / password in props field, but given a conf_key or use default config from etc/mqtt_source.yaml?
Thanks.

**Comment by ngjaying** [comment]
@loleek Currently, the source configuration can be changed in props field. Here is an example:

```json
{
"id": "rule1",
"name": "simple rule",
"graph": {
"nodes": {
"demo": {
"type": "source",
"nodeType": "mqtt",
"props": {
"datasource": "demo",
"timestamp": "ts",
"server": "tcp://syno.home:1883"
}
},
"filter": {
"type": "operator",
"nodeType": "filter",
"props": {
"expr": "temperature > 30"
}
},
"log": {
"type": "sink",
"nodeType": "log",
"props": {}
}
},
"topo": {
"sources": [
"demo"
],
"edges": {
"demo": [
"filter"
],
"filter": [
"log"
]
}
}
}
}
```

**Comment by loleek** [comment]
Thanks. I will try it. Does the mqtt username and password change in the same way?
