### ISSUE TITLE
Not getting control: "text" value as arg in exec fn of custom functions

### ISSUE THREAD

**Issue by Jislin-Anna** [lf-edge/ekuiper#2000]
- eKuiper version: 1.10.0.

I ran eKuiper in Docker and created a custom function called `Point_Within`. The function has four parameters, where the first two are field names and the third and fourth arguments are  text values that the first arguments are checked against. However, the third and fourth arguments are nil values as they are not passed in message.

To reproduce the issue, I modified the `echo.json` file for the custom function `echo` by replacing the `control` field with `"text"`.

Here is the updated `echo.json` content:

```json
{
	"about": {
	  "trial": false,
	  "author": {
		"name": "EMQ",
		"email": "contact@emqx.io",
		"company": "EMQ Technologies Co., Ltd",
		"website": "https://www.emqx.io"
	  },
	  "helpUrl": {
		"en_US": "https://ekuiper.org/docs/en/latest/sqls/custom_functions.html",
		"zh_CN": "https://ekuiper.org/docs/zh/latest/sqls/custom_functions.html"
	  },
	  "description": {
		"en_US": "",
		"zh_CN": ""
	  }
	},
	"name": "echo",
	"functions": [
	  {
		"name": "echo",
		"example": "echo(col1 )",
		"hint": {
		  "en_US": "The parameter value is output as it is.",
		  "zh_CN": "原样输出参数值。"
		},
		"args": [
		  {
			"name": "data",
			"hidden": false,
			"optional": false,
			"control": "text",
			"type": "string",
			"hint": {
			  "en_US": "The data to echo.",
			  "zh_CN": "字段名"
			},
			"label": {
			  "en_US": "Field",
			  "zh_CN": "字段"
			}
		  }
		],
		"return": {
		  "type": "string",
		  "hint": {
			"en_US": "Echoed string",
			"zh_CN": "回声值"
		  }
		},
		"node": {
		  "category": "function",
		  "icon": "iconPath",
		  "label": {
			"en_US": "Echo",
			"zh_CN": "回声"
		  }
		}
	  }
	]
}
```

Please note that it appears that none of the custom functions are currently producing correct results when a text field is used.

**Comment by ngjaying** [comment]
Are you talking about using the function in eKuiper manager? What are the steps to reproduce the problem?

**Comment by Jislin-Anna** [comment]
> Are you talking about using the function in eKuiper manager? What are the steps to reproduce the problem?

Step 1: Replace echo.json , arg[0].control as "text" and build the docker image.
Step 2: create a flow using ekuiper manager, give expr=echo(abc).
Result should be echo:"abc" instead Iam getting echo: null as no field named 'abc' was present in the message sent.
I compared it with power function where in power(x,y) y is a constant in a flow. The same is not reflected in echo function even when I gave "control": "text" in echo.json. Please refer the issue for full echo.json.

**Comment by ngjaying** [comment]
Looks like a UI problem.  I can pass over the problem to the UI team. But please note that eKuiper manager is not part of this open source project.

**Comment by Jislin-Anna** [comment]
> Looks like a UI problem. I can pass over the problem to the UI team. But please note that eKuiper manager is not part of this open source project.

Not a UI Problem. Even if I create the flow using api, same issue is occuring. the problem is that custom functions are not providing control:"text" fields as args in exec function.

**Comment by ngjaying** [comment]
ah, that's not related to the json file. I was misled. So echo(abc) here abc is a field/name. It expects the data has that field of type string. If you need a string literal, use echo("abc")

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jislin-Anna** [comment]
Thank you. Its working
