### ISSUE TITLE
Manager ui is where ?

### ISSUE THREAD

**Issue by gedw99** [lf-edge/ekuiper#2004]
Is the manager ui open ? 

Thanks …

**Comment by gedw99** [comment]
I wanted to add some gui related to seeing what the nats control plane is configured as

**Comment by ngjaying** [comment]
@gedw99 I am sorry that manager UI is not open source. Do you want to integrate it with nats？

**Comment by gedw99** [comment]
Yes exactly. 

You did a great job on the data transformation design

**Comment by ngjaying** [comment]
What integration are you doing? We are happy to help if needed.

**Comment by gedw99** [comment]
Just need to integrate with nats .

i already build a gui for nats Control plane and data plane and can built a gui on top of your stuff via nats.

Nats gui talks to nats Server / Cluster  and then to any system it controls . Very much like a command and control system used for penetration testing.

Using this https://github.com/choria-io/asyncjobs . It’s the primary runner of everything else.

**Comment by ngjaying** [comment]
Thanks. I'll close this issue. If you need commercial support for UI, I can introduce the UI team to you.
