### ISSUE TITLE
Cannot download sinks plugins

### ISSUE THREAD

**Issue by solekubi** [lf-edge/ekuiper#2009]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.10.1

When I downloaded tdengin plugins, error 403 was reported，but other plugins were fine, for example influx2

![image](https://github.com/lf-edge/ekuiper/assets/15035534/1428e3c0-6144-479c-ab03-16249988b897)

**Comment by ngjaying** [comment]
tdengine client does not support alpine, thus we do not provide pre-built plugin in alpine. Please use slim image if you need it.
