### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by oucb** [lf-edge/ekuiper#2020]
<img width="748" alt="image" src="https://github.com/lf-edge/ekuiper/assets/1532209/9ca399e0-e7cf-466c-8306-038d41b9a790">

<img width="1112" alt="image" src="https://github.com/lf-edge/ekuiper/assets/1532209/1bfacccd-460a-4a72-a66c-2f19ef211ca9">

**Comment by xjasonlyu** [comment]
Dockerfiles have been moved to `deploy/docker/Dockerfile-*`.

- Dockerfile: https://github.com/lf-edge/ekuiper/blob/master/deploy/docker/Dockerfile

**Comment by ngjaying** [comment]
Thanks, we'll update the docker hub page.
