### ISSUE TITLE
Some dependencies of eKuiper are outdated and vunlnerable

### ISSUE THREAD

**Issue by hotjuicew** [lf-edge/ekuiper#2030]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.10.1
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):linux/amd64
- Others:

**What happened and what you expected to happen**:

eKuiper has some CVE vulnerabilities scanned by security scanners in its dependencies. It is recommended to update the Go modules to enhance security.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

<img width="376" alt="屏幕截图 2023-06-26 214112" src="https://github.com/lf-edge/ekuiper/assets/101414955/e73cb298-c009-44cb-a0d3-179a680b09f8">
<img width="369" alt="屏幕截图 2023-06-26 214220" src="https://github.com/lf-edge/ekuiper/assets/101414955/19483371-755f-4f7d-bb4d-5fdfb5a41aed">

**Comment by ngjaying** [comment]
Do you have a link? 
We usually update the dependencies before a new minor release. Some of the dependencies already archive, do you have any suggestions for how to deal with them.

**Comment by hotjuicew** [comment]
This is a built-in security scan of Docker images. For the archived dependencies, it is recommended to find alternative dependencies that are similar.
