### ISSUE TITLE
【Function to get the rule start time】 add a function to get the rule start time

### ISSUE THREAD

**Issue by Jimmy-Wen** [lf-edge/ekuiper#2040]
There is a scenario where the data needs to be clear 5 minutes before the rule starts，my idea is to compare timestamps with case when statements，however, the rule  start time {start_time} cannot be obtained.
The pseudo-code is as follows，
SELECT CASE WHEN ts - {start_time} < 5min THEN 0 ELSE THEN a END as a

That requires ekuiper to add a function to get the rule start time

**Comment by Jimmy-Wen** [comment]
when will v1.11 be released？

**Comment by ngjaying** [comment]
> when will v1.11 be released？

Please check the roadmap https://wiki.lfedge.org/display/EKUIPER/Feature+Roadmap
Or milestones https://github.com/lf-edge/ekuiper/milestones
