### ISSUE TITLE
Hopping Window, support for hops longer than window length

### ISSUE THREAD

**Issue by YGao01** [lf-edge/ekuiper#2047]
Hi all,

As discussed in the weekly meeting today (2023.06.30), we hope that the hopping window in eKuiper could support hops longer than window length. 

For example, we need a task to be executed every 60 seconds, and the task takes 10 seconds each time. Therefore, we need something like HOPPINGWINDOW(ss, 10, 60). Hope this could be considered.

Thanks!

**Comment by Yisaer** [comment]
I think `HOPPINGWINDOW(ss, 10, 60)` is supported now.
