### ISSUE TITLE
Make is not working in Windows

### ISSUE THREAD

**Issue by FishPancake** [lf-edge/ekuiper#2074]
File: [/docs/zh_CN/operation/compile/compile.md](https://ekuiper.org/docs/zh/latest/operation/compile/compile.html)

**Comment by ngjaying** [comment]
Makefile is not supported in Windows by default.  Suggest to use linux, WSL or install MinGW. Or you can use go build command in the Makefile directly.

**Comment by FishPancake** [comment]
不好意思，我对go不太了解，我现在安装了MinGW之后执行make，报错make: *** [Makefile:23: build_prepare] Error 1

> Makefile is not supported in Windows by default. Suggest to use linux, WSL or install MinGW. Or you can use go build command in the Makefile directly.默认情况下，Makefile 在 Windows 中不受支持。建议使用linux，WSL或安装MinGW。或者你可以直接在 Makefile 中使用 go build 命令。

**Comment by FishPancake** [comment]
在windows中编译，需要对makefile进行哪些修改呢

**Comment by ngjaying** [comment]
> 在windows中编译，需要对makefile进行哪些修改呢

跟 Go 没有关系，是 windows 本身就不支持 Makefile。中间遇到的报错应该大部分都是 Makefile 支持相关的，建议直接去搜索。在 Windows 下，用 WSL 没有问题。实在不想装，在目录创建完成后（看 Makefile 里的build_prepare部分），直接执行 go build

```
go build -trimpath -ldflags="-s -w -X main.Version=1.11.0 -X main.LoadFileType=relative" -o kuiperd cmd/kuiperd/main.go
```
