### ISSUE TITLE
Stream command error: option 'format=can' is invalid

### ISSUE THREAD

**Issue by maulik9898** [lf-edge/ekuiper#2092]
When I tried to create stream with "can" format it gives me error.

`{
    "sql": "CREATE STREAM canDemo () WITH (TYPE=\"can\" , FORMAT=\"can\", SHARED=\"TRUE\", SCHEMAID=\"dbc\")"

}`

`Stream command error: option 'format=can' is invalid
`

**Environment**:

- eKuiper version (e.g. `1.3.0`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
Dear @maulik9898 ,  the CAN source is not open source yet, it is currently a commercial plugin provided by EMQ company. I can help to connect if you need commercial support. Thanks.

**Comment by maulik9898** [comment]
Which commercial product is this part of .?

**Comment by ngjaying** [comment]
Can you contact me by email (huangjy@emqx.io) or slack? Thanks.

**Comment by ngjaying** [comment]
Close as no response.
