### ISSUE TITLE
Complete SQL functions for math and time

### ISSUE THREAD

**Issue by xjasonlyu** [lf-edge/ekuiper#2094]
**What would you like to be added/modified**:

Add and complete similar MySQL/Postgres-style math and time functions in eKuiper:

- [x] https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html
- [x] https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html

Current missing mathematical funcitons
- [x] conv
- [x] cot
- [x] crc32
- [x] degrees
- [x] format
- [x] radians

**Why is this needed**:

Easy for time and math manipulation when using SQL functions.

**Comment by yai-dev** [comment]
@xjasonlyu Hi there, i will help to time functions for eKuiper and i'm working on it. (this comment is for mark purpose only :))

**Comment by ngjaying** [comment]
Still lack some math functions.

**Comment by AyushK-101** [comment]
@ngjaying I would like to work on this, could you tell me about some of the math functions that are yet to be added.

**Comment by ngjaying** [comment]
> @ngjaying I would like to work on this, could you tell me about some of the math functions that are yet to be added.

@AyushK-101 Thank you. I updated the issue to list all missing math functions. Please check.

**Comment by ngjaying** [comment]
> @ngjaying can i please work on this issue?

Sure, please comment about what function are you working on once started

**Comment by SmartPotter** [comment]
@ngjaying, I want to work on the degrees mathematical function, May I know what exactly you are looking for?

**Comment by ShikhaaT44** [comment]
Can i work on any functions which are yet unclaimed to work upon? I'm interested on working on degrees function
