### ISSUE TITLE
CAST function is not supported with bytea

### ISSUE THREAD

**Issue by manikandan-harman** [lf-edge/ekuiper#2123]
CAST function is not supported with bytea

**Environment**:

- eKuiper version : 1.9
- Hardware configuration: 4 core/16 GB RAM 
- OS : Windows/Docker
- Others:

**What happened and what you expected to happen**:
I am not able to create a rule with cast function as cast(col, "bytea") as per documentation https://ekuiper.org/docs/en/latest/sqls/functions/transform_functions.html#cast

Expected behavior: Should able to create a rule with cast(col, "bytea")
**How to reproduce it (as minimally and precisely as possible)**:
When you try to create a rule using ekuiper manager (version: 1.9) or eKuiper API like sql statement as SELECT CAST(base64image,\"bytea\") FROM mqttstream
**Anything else we need to know?**:
eKuiper rule creation API gives 400 bad request with below error message:
invalid rule json: Parse SQL SELECT CAST(*,"bytea") FROM mqttstream error: Expect one of following value for the 2nd parameter: bigint, float, string, boolean, datetime..

**Comment by manikandan-harman** [comment]
Could you please provide me the ETA, if possible, when this will be available? or is there any short-term solution till this issue be fixed? I know that PR is ready already.

**Comment by ngjaying** [comment]
This will be included in 1.11 release planned in mid-August. We will also release a pre-release like 1.11.0-alpha.2 recently.
