### ISSUE TITLE
Add ROW_NUMBER support

### ISSUE THREAD

**Issue by vol-ale** [lf-edge/ekuiper#2136]
**What would you like to be added/modified**:
Add `ROW_NUMBER` support to be able to get the row index inside temporal windows

**Why is this needed**:
To compare two sequences.

**Possible scenario**:
Let's assume we have a sequence of some values `[0.2, 0.3, 0.4, 0.5, 0.3]` we want to compare against an incoming stream of data. We can store this sequence in some lookup table like this
| rule_id | index | value |
|--------|--------|-------|
| my_rule |  1     |  0.2 |
| my_rule |  2     |  0.3 |
| my_rule |  3     |  0.4 |
| my_rule |  4     |  0.5 |
| my_rule |  5     |  0.3 |

and `JOIN` it with the incoming stream using the following query:
```sql
SELECT
  stream.object_id,
  SQRT(SUM(POW(stream.value - pattern.value, 2))) as distance
FROM stream
LEFT JOIN pattern
  ON pattern.id = rule_id() AND pattern.index = ROW_NUMBER
GROUP BY COUNTWINDOW(5,1) -- window size requals to the pattern size
WHERE distance < 0.5
```
I'm not certain, maybe there is some other way how to achieve this using the existing functionality.

**Comment by ngjaying** [comment]
Add to 1.11 milestone

**Comment by Yisaer** [comment]
For now we have supported `row_number` function in select fields, so in your case, we can create the rules like following:

First rule sink the results into memory sink:
```sql
SELECT
  stream.object_id,
  SQRT(SUM(POW(stream.value - pattern.value, 2))) as distance,
  row_number() as number,
  pattern.index
FROM stream
LEFT JOIN pattern
  ON pattern.id = rule_id() 
GROUP BY COUNTWINDOW(5,1) -- window size requals to the pattern size
WHERE distance < 0.5
```

Second rule read the data from the memory sink and filter by its condition:
```sql
select object_id, distance from memory where index = number
```
