### ISSUE TITLE
Source SQL Sink: Target Database URL Issue for MS SQL Server

### ISSUE THREAD

**Issue by manikandan-harman** [lf-edge/ekuiper#2137]
When I try to configure the Source SQL sink with MS SQL server connection string as below format throwing error: "{"status": "stopped", "message": "Stopped: dburl.Parse XXX ": invalid character "\\" in host name."}"

sqlserver://username:password@140.210.204.147\SQLExpress/testdb

**Environment**:
eKuiper version : 1.9
eKuiper Manager version : 1.9
Hardware configuration: 4 core/16 GB RAM
OS : Windows/Docker
Others:

**What happened and what you expected to happen**:
When I try to create source SQL stream and server URL mentioned as "140.210.204.147\SQLExpress" as Server name, Rule is stopped. When I create a Server name which includes '\' symbol should work as expected 
**How to reproduce it (as minimally and precisely as possible)**:
Create a connection string in this format: 
sqlserver://username:password@140.210.204.147\SQLExpress/testdb
**Anything else we need to know?**:
Format of MS SQL Server Name: ServerName\SQLExpress
Here **\SQLExpress** is causing issue..

**Comment by Yisaer** [comment]
according to the example in https://github.com/microsoft/go-mssqldb as following:

```
sqlserver://sa@localhost/SQLExpress?database=master&connection+timeout=30
```

 I think you should use `/SQLEXpress` instead of `\SQLExpress` here

**Comment by manikandan-harman** [comment]
Thank you [Yisaer], This worked for me in ekuiper but not in SSMS. Actual purpose is achieved. Closing this ticket
