### ISSUE TITLE
Can it support Triton Server as External Function

### ISSUE THREAD

**Issue by silenceli** [lf-edge/ekuiper#2146]
We hope that ekuiper can support calling tritonserver services. Although ekuiper currently supports custom grpc external function, we find it difficult to obtain the tritonserver client proto file and we feel that you are also unable to convert the data obtained from select into the lowest level rpc request of tritonserver. 
One solution we can think of is to extend a new type of external function, such as tritonserver, which only needs to provide input and output shapes、ip and port，which similar to the deepstream nvinferserver element.

**Comment by silenceli** [comment]
Perhaps we have another solution, which is to add a custom function (developed with Python, for example). Within this function, we can use the tritonserver Python SDK to call remote tritonserver services.

**Comment by ngjaying** [comment]
> One solution we can think of is to extend a new type of external function, such as tritonserver, which only needs to provide input and output shapes、ip and port，which similar to the deepstream nvinferserver element

I know very little about Triton Server, so my question may be silly. 
In this solution, why you don't need to know the proto file?

**Comment by silenceli** [comment]
Since Triton provides official SDKs for Python/C++ and other languages, which encapsulate gRPC, you don't need to know about the input and output at the gRPC level.

triton client demo:
```
import grpc
import tritonclient.grpc as grpc_client
from tritonclient.utils import triton_to_np_dtype

# 创建连接到 Triton Server 的 gRPC 客户端
channel = grpc.insecure_channel("localhost:8001")
client = grpc_client.InferenceServerClient(channel)

# 发送 inference 请求
inputs = []
outputs = []
inputs.append(grpc_client.InferInput('input', [1, 3, 224, 224], "FP32"))
outputs.append(grpc_client.InferRequestedOutput('output'))
inputs[0].set_data_from_numpy(np.random.randn(1, 3, 224, 224).astype(np.float32))
results = client.infer(model_name='resnet50', inputs=inputs, outputs=outputs)

# 处理 inference 结果
output_data = results.as_numpy('output')
```

**Comment by ngjaying** [comment]
Great. Is Triton Server suitable to run in edge device or phone? We are interested to support it. Would you like to work together with us to push this forward?

**Comment by ngjaying** [comment]
Use schema-less external function. Check https://ekuiper.org/docs/en/latest/extension/external/external_func.html#external-function
