### ISSUE TITLE
The relationship between help files and cross-references is confusing, is it possible to reorganize the document catalog

### ISSUE THREAD

**Issue by wkliu19** [lf-edge/ekuiper#2167]
File: [/docs/zh_CN/installation.md](https://ekuiper.org/docs/zh/latest/installation.html)

**Comment by ngjaying** [comment]
Sure. Do you have some ideas? The doc is also open source, feel free to submit your changes.

**Comment by ngjaying** [comment]
We have just reconstruct the doc, please check it out. Comments are welcome!
