### ISSUE TITLE
Creating customized portable plugin in Ekuiper is not working

### ISSUE THREAD

**Issue by LeyaT-Harman** [lf-edge/ekuiper#2175]
I need to create a customized portable plugin. 
To start with , I have used the existing sample code of python and compressed the pysam folder with the revert function code. (https://github.com/lf-edge/ekuiper/tree/master/sdk/python/example/pysam )
Tried to upload the folder through ekuiper dashboard but getting an error of "Invalid or missing json file". 
I have also tried with Go using the countPlusOne zipped code. I downloaded the existing code and tried to upload it.
Getting the error as "Invalid so or conf file missing". 

![image](https://github.com/lf-edge/ekuiper/assets/142020132/efa06894-66dc-4d03-8c63-b6f0bbfc35a3)

Please suggest on the same

**Comment by ngjaying** [comment]
@LeyaT-Harman The pysam.json must reside in the root of the zip file. A common mistake is to have a directory in the root. pysam.zip -> pysam.json  instead of pysam.zip -> pysam dir -> pysam.json.

**Comment by LeyaT-Harman** [comment]
Hi,

I have tried keeping the json file as mentioned below… Now getting the error for the function file. I have also tried to keep the charLen.json inside the functions folder still getting the same error

***@***.***

***@***.***

Regards,
Leya

From: ngjaying ***@***.***>
Sent: Monday, August 14, 2023 12:24 PM
To: lf-edge/ekuiper ***@***.***>
Cc: Thankachan, Leya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lf-edge/ekuiper] Creating customized portable plugin in Ekuiper is not working (Issue #2175)

[EXTERNAL EMAIL]

@LeyaT-Harman<https://github.com/LeyaT-Harman> The pysam.json must reside in the root of the zip file. A common mistake is to have a directory in the root. pysam.zip -> pysam.json instead of pysam.zip -> pysam dir -> pysam.json.

**Comment by ngjaying** [comment]
Attach my pysam.zip for your reference.
[pysam.zip](https://github.com/lf-edge/ekuiper/files/12333939/pysam.zip)

**Comment by LeyaT-Harman** [comment]
Hi,

Thanks for sharing the sample. I tried to replace the revert.py and revert.json files in you folder with my files and modified the pysam.py and pysam.json with the new function names. But again I got the same response. Can you please guide ?
***@***.***

Regards,
Leya
From: ngjaying ***@***.***>
Sent: Monday, August 14, 2023 4:19 PM
To: lf-edge/ekuiper ***@***.***>
Cc: Thankachan, Leya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lf-edge/ekuiper] Creating customized portable plugin in Ekuiper is not working (Issue #2175)

[EXTERNAL EMAIL]

Attach my pysam.zip for your reference.
pysam.zip<https://github.com/lf-edge/ekuiper/files/12333939/pysam.zip>

**Comment by ngjaying** [comment]
> 

The name of plugin and symbols must match between the json file and the python files. You can do a search for the symbol to be replaced and try to replace all to your new name.

**Comment by ngjaying** [comment]
Close this one as it is inactive for more than 2 weeks. Feel free to reopen if you still encounter problems.
