### ISSUE TITLE
How about supporting databend as the ekuiper sink ?

### ISSUE THREAD

**Issue by hantmac** [lf-edge/ekuiper#2178]
**What would you like to be added/modified**:
Support [databend](https://github.com/datafuselabs/databend) as the ekuiper sink.

**Why is this needed**:
Databend is an open-source Elastic and Workload-Aware modern cloud data warehouse that focuses on Low-Cost and Low-Complexity for your massive-scale analytics needs. It is an open-source alternative to Snowflake, Databend is crafted in Rust, enabling superior performance and efficiency. I think databend is very suitable for massive IOT data store.

**Comment by ngjaying** [comment]
Great idea. However, we do not have the knowledge of databend. Would you like to contribute this sink? Or we can work together to make it. I suppose this could be a shipped plugin with automatic build in our CI.

**Comment by hantmac** [comment]
> 

Sounds great! I would like to try to make a pr for this sink.
