### ISSUE TITLE
Cannot download sinks plugins 

### ISSUE THREAD

**Issue by zouyuxuan** [lf-edge/ekuiper#2210]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
eKuiper version:lfedge/ekuiper:1.10-slim
ekuiper-manager version:emqx/ekuiper-manager:latest
![image](https://github.com/lf-edge/ekuiper/assets/33485252/d46a0f04-4a37-424e-bf65-b15764916ed6)
downloading the tdengine plugin on the web page reports an error,but the plugin source file of tdengine is found under the mount directory
![image](https://github.com/lf-edge/ekuiper/assets/33485252/d4ad8259-814b-496a-bc17-3fa5ec48e8fd)

**Comment by ngjaying** [comment]
Problem happens when installing tdengine runtime. Please check the log for the installation error.

**Comment by zouyuxuan** [comment]
time="2023-08-28 02:58:06" level=warning msg="No readings are processed for the event, so ignore it." file="edgex/edgex_source.go:213" rule=test
time="2023-08-28 02:58:06" level=info msg="err:exit status 8 stdout: stderr:+ [ -z 1.10.2 ]\n+ url=https://www.taosdata.com/assets-download/TDengine-client-1.10.2-Linux-x64.tar.gz\n+ uname -m\n+ [ x86_64 = aarch64 ]\n+ zip=TDengine-client.tar.gz\n+ wget -T 280 -O TDengine-client.tar.gz https://www.taosdata.com/assets-download/TDengine-client-1.10.2-Linux-x64.tar.gz\n--2023-08-28 02:58:06--  https://www.taosdata.com/assets-download/TDengine-client-1.10.2-Linux-x64.tar.gz\nResolving www.taosdata.com (www.taosdata.com)... 101.200.125.16\nConnecting to www.taosdata.com (www.taosdata.com)|101.200.125.16|:443... connected.\nHTTP request sent, awaiting response... 404 Not Found\n2023-08-28 02:58:06 ERROR 404: Not Found.\n\n" file="native/manager.go:551"
time="2023-08-28 02:58:06" level=error msg="sinks plugins create command error: fail to install plugin: exit status 8" file="server/rest.go:76"

**Comment by ngjaying** [comment]
You must specify the tdengine version number

**Comment by zouyuxuan** [comment]
I set the version of tdengine, the error log is “wget -T 280 -O TDengine-client.tar.gz https://www.taosdata.com/assets-download/TDengine-client-3.1.0.3-Linux-x64.tar.gz”
but I downloaded the client address from tdengine is **https://www.taosdata.com/assets-download/3.0/TDengine-client-3.1.0.3-Linux-x64.tar.gz**

**Comment by zouyuxuan** [comment]
![image](https://github.com/lf-edge/ekuiper/assets/33485252/f87f9c8a-76a2-4f5c-8c42-4f00cdcddcdf)

I changed the url address but it doesn't work

**Comment by ngjaying** [comment]
looks like tdengine change their download location, you can update the install.sh by yourself. And feel free to push a PR once you get it work. Thank you.

**Comment by zouyuxuan** [comment]
I downloaded the installation package from **https://packages.emqx.net/kuiper-plugins/1.10.2/debian/sinks/tdengine_amd64.zip**, changed the install.sh url path, and reported an error after commit
**time="2023-08-28 07:49:00" level=error msg="plugin tdengine open error: plugin.Open(\"/kuiper/plugins/sinks/tdengine@1.10.2.so\"): /kuiper/plugins/sinks/tdengine@1.10.2.so: undefined symbol: taos_consume" file="native/manager.go:725"
time="2023-08-28 07:49:00" level=error msg="sinks plugins create command error: fail to install plugin: cannot open /kuiper/plugins/sinks/tdengine@1.10.2.so: plugin.Open(\"/kuiper/plugins/sinks/tdengine@1.10.2.so\"): /kuiper/plugins/sinks/tdengine@1.10.2.so: undefined symbol: taos_consume" file="server/rest.go:76"**

**Comment by ngjaying** [comment]
Oh, this plugin only supports td v2. There is an issue for v3 support #2054

**Comment by zouyuxuan** [comment]
It worked, thank you very much

**Comment by lzh123** [comment]
I have the same question. how can I do it?
 the kuiper-manage download url is : https://packages.emqx.net/kuiper-plugins/1.10.2/debian/sinks/tdengine_amd64.zip
and  the tdengine_client version is 2.6.0.0 . 
 log:
nnector/go/wrapper/field_test.go\nTDengine-client-2.6.0.0/connector/go/wrapper/setconfig_test.go\nTDengine-client-2.6.0.0/connector/go/wrapper/stmt.go\nTDengine-client-2.6.0.0/connector/go/wrapper/taosc_test.go\nTDengine-client-2.6.0.0/connector/go/bench/\nTDengine-client-2.6.0.0/connector/go/bench/sql_test.go\nTDengine-client-2.6.0.0/connector/go/bench/valgrind/\nTDengine-client-2.6.0.0/connector/go/bench/valgrind/README.md\nTDengine-client-2.6.0.0/connector/go/bench/valgrind/main.go\nTDengine-client-2.6.0.0/connector/go/bench/README.md\nTDengine-client-2.6.0.0/connector/go/go.sum\nTDengine-client-2.6.0.0/connector/go/README-CN.md\nTDengine-client-2.6.0.0/connector/go/README.md\nTDengine-client-2.6.0.0/connector/go/examples/\nTDengine-client-2.6.0.0/connector/go/examples/taoslogtail/\nTDengine-client-2.6.0.0/connector/go/examples/taoslogtail/taoslogtail.go\nTDengine-client-2.6.0.0/connector/go/examples/uint/\nTDengine-client-2.6.0.0/connector/go/examples/uint/uint.go\nTDengine-client-2.6.0.0/connector/go/examples/ns/\nTDengine-client-2.6.0.0/connector/go/examples/ns/ns.go\nTDengine-client-2.6.0.0/connector/go/examples/taoslogpump/\nTDengine-client-2.6.0.0/connector/go/examples/taoslogpump/taoslogpump.go\nTDengine-client-2.6.0.0/connector/go/examples/README.md\nTDengine-client-2.6.0.0/connector/go/errors/\nTDengine-client-2.6.0.0/connector/go/errors/errors.go\nTDengine-client-2.6.0.0/connector/go/common/\nTDengine-client-2.6.0.0/connector/go/common/change.go\nTDengine-client-2.6.0.0/connector/go/common/const.go\nTDengine-client-2.6.0.0/connector/go/common/sql.go\nTDengine-client-2.6.0.0/connector/go/.git\nTDengine-client-2.6.0.0/connector/taos-jdbcdriver-2.0.38-dist.jar\n stderr:+ '[' -z 2.6.0.0 ]\n+ url=https://www.taosdata.com/assets-download/TDengine-client-2.6.0.0-Linux-x64.tar.gz\n+ uname -m\n+ '[' x86_64 '=' aarch64 ]\n+ zip=TDengine-client.tar.gz\n+ wget -T 280 -O TDengine-client.tar.gz https://www.taosdata.com/assets-download/TDengine-client-2.6.0.0-Linux-x64.tar.gz\nConnecting to www.taosdata.com (101.200.125.16:443)\nsaving to 'TDengine-client.tar.gz'\nTDengine-client.tar.   1% |                                | 98043  0:01:30 ETA\nTDengine-client.tar.  29% |*********                       | 2591k  0:00:04 ETA\nTDengine-client.tar.  46% |**************                  | 4047k  0:00:03 ETA\nTDengine-client.tar.  59% |*******************             | 5263k  0:00:02 ETA\nTDengine-client.tar.  75% |************************        | 6655k  0:00:01 ETA\nTDengine-client.tar.  91% |*****************************   | 8031k  0:00:00 ETA\nTDengine-client.tar. 100% |********************************| 8774k  0:00:00 ETA\n'TDengine-client.tar.gz' saved\n+ '[' -e TDengine-client.tar.gz ]\n+ dir=TDengine-client\n+ mkdir TDengine-client\n+ tar -xzvf TDengine-client.tar.gz -C ./TDengine-client --strip-components 1\n+ rm TDengine-client.tar.gz\n+ '[' -e TDengine-client ]\n+ cd TDengine-client\n+ ret=\n+ '[' -x ./connector -a '!' -d ./connector ]\n+ '[' -x ./driver -a '!' -d ./driver ]\n+ '[' -x ./examples -a '!' -d ./examples ]\n+ '[' -x ./install_client.sh -a '!' -d ./install_client.sh ]\n+ ././install_client.sh\n/kuiper/plugins/temp/sinks/tdengine/install.sh: line 55: ././install_client.sh: not found\n" file="native/manager.go:570"
time="2023-12-25T09:08:47Z" level=error msg="sinks plugins create command error: fail to install plugin: exit status 127" file="server/rest.go:85"
