### ISSUE TITLE
Incorrect Calculation Result with Tumbling Window in SQL Query

### ISSUE THREAD

**Issue by retoool** [lf-edge/ekuiper#2211]
**Environment**:

- eKuiper version : 1.11

**What happened and what you expected to happen**:
  What happened:
I encountered a discrepancy in the calculation result when using the following SQL query:
```sql
select 
  DevCode as DevCode_Sink,
  DataType as DataType_Sink,
  "WNAC_WdSpd_AVG_10s" as Metric_Sink,
  AVG(Value) as Value_Sink,
  window_end() as Time_Sink 
from iotSource
GROUP BY TUMBLINGWINDOW(ss, 10) FILTER(where Metric = "WNAC_WdSpd"),DevCode
```

What I expected to happen:
I intended to calculate the average of "WNAC_WdSpd" within a tumbling window of size 10 seconds. However, it appears that the calculation result does not align with the left-closed and right-open interval semantics, which is unexpected.

Interestingly, when I switched from using "TUMBLINGWINDOW" to "HOPPINGWINDOW," the calculation result was as expected.

**Comment by Yisaer** [comment]
@retoool 

Could you paste the input and and the result for the both outputs from sql with tumbling window and sql with hopping window in order we can know the expected result from your view.

**Comment by retoool** [comment]
Sure, here's a response you could provide:

Certainly! I'd be happy to provide the input and results for both SQL queries using the tumbling window and hopping window for your reference.

## Input


Local Time | Value
-- | --
17:54:01 | 10.49835
17:54:05 | 10.45806
17:54:10 | 9.52328
17:54:14 | 8.99291
17:54:18 | 10.01893
17:54:23 | 8.91996
17:54:27 | 9.73717
17:54:31 | 10.78512
17:54:36 | 10.74094
17:54:40 | 10.71955
17:54:44 | 9.22239
17:54:49 | 9.05869
17:54:53 | 8.95866
17:54:57 | 10.12559
17:55:02 | 10.0555
17:55:06 | 9.60793
17:55:10 | 10.45217
17:55:15 | 10.95324
17:55:19 | 10.05545
17:55:23 | 9.17934
17:55:28 | 8.85587
17:55:32 | 8.87322
17:55:36 | 8.07647
17:55:40 | 7.66734
17:55:45 | 7.07179
17:55:49 | 6.92314
17:55:53 | 7.32626
17:55:58 | 9.98239



</body>

</html>

## SQL Query with Tumbling Window (Not as Expected):
```sql
select 
  DevCode as DevCode_Sink,
  DataType as DataType_Sink,
  "test0001" as Metric_Sink,
  AVG(Value) as Value_Sink,
  window_end() as Time_Sink 
from iotSource
GROUP BY TUMBLINGWINDOW(ss, 10) FILTER(where Metric = "WNAC_WdSpd" and DevCode = "DTZJJK:PHFC:Q1:W001")
```

Result of Tumbling Window:


Local Time | Value
-- | --
17:54:00 | 11.6136
17:54:20 | 9.50592
17:54:30 | 9.328565
17:54:40 | 10.76303
17:54:50 | 9.14054
17:55:00 | 9.542125
17:55:10 | 9.831715
17:55:20 | 10.504345
17:55:30 | 9.017605
17:55:40 | 8.474845
17:55:50 | 6.997465
17:56:00 | 8.654325


## SQL Query with Hopping Window (Expected Result):
```sql
select 
  DevCode as DevCode_Sink,
  DataType as DataType_Sink,
  "WNAC_WdSpd_AVG_10s" as Metric_Sink,
  AVG(Value) as Value_Sink,
  window_end() as Time_Sink 
from iotSource
GROUP BY HOPPINGWINDOW(ss, 10, 10) FILTER(where Metric = "WNAC_WdSpd" and DevCode = "DTZJJK:PHFC:Q1:W001")
```

Result of Hopping Window:


Local Time | Value
-- | --
17:54:00 | 11.6136
17:54:20 | 9.50592
17:54:30 | 9.328565
17:54:40 | 10.76303
17:54:50 | 9.666876667
17:55:00 | 9.542125
17:55:10 | 9.831715
17:55:20 | 10.48695333
17:55:30 | 9.017605
17:55:40 | 8.474845
17:55:50 | 7.220756667
17:56:00 | 8.654325

**Comment by Yisaer** [comment]
Thanks, after I fixed this problem in https://github.com/lf-edge/ekuiper/pull/2212 and re-tested it with your case, and finally got the expected result.
