### ISSUE TITLE
Kuiper subscribe nats message and reports an error “Unsupported data type .”

### ISSUE THREAD

**Issue by zouyuxuan** [lf-edge/ekuiper#2214]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I use nats stream to publish messages, message body format is `

	var msg types.MessageEnvelope
	str := `{ts:%s,int8:%d,Id:zmj,device:virtual}`
	tdengine := fmt.Sprintf(str, time.Now().Format(time.RFC3339), i)
	byte, _ := json.Marshal(tdengine)
	msg.Versionable.ApiVersion = "v3"
	msg.Payload = byte
	msg.ContentType = "application/json"

	m, _ := json.Marshal(msg)
	if _, err := js.Publish(ctx, "TDENGINE.TEST1", m); err != nil {
		fmt.Println("pub error: ", err)
	}
`

**Comment by ngjaying** [comment]
Your json looks like invalid: Id:zmj, should it be "Id":"zmj".  But you just ignore the error byte, _ := json.Marshal(tdengine)

**Comment by zouyuxuan** [comment]
I printed all the errors, it has nothing to do with the "Id":"zmj", kuiper can't read the msg.ContentType

**Comment by ngjaying** [comment]
Could you please add the step by step description for how to reproduce the problem? eKuiper does not have Nats source, do you mean EdgeX source?

**Comment by ngjaying** [comment]
```go
str := `{ts:%s,int8:%d,Id:zmj,device:virtual}`
tdengine := fmt.Sprintf(str, time.Now().Format(time.RFC3339), 23)
byte, err := json.Marshal(tdengine)
if err != nil {
fmt.Println(err)
}
fmt.Println(string(byte))
result := make(map[string]any)
err = json.Unmarshal(byte, &result)
if err != nil {
fmt.Println(err)
}
fmt.Println(result)
```

This gets error json: cannot unmarshal string into Go value of type map[string]interface {}
Your json is not a valid json string, it is just a string..

**Comment by zouyuxuan** [comment]
I changed the code, there is no problem with Unmarshal, I checked the source code of kuiper **edgex/edgex_source.go** and it has not reached unmarshal yet

           `var msg types.MessageEnvelope
		str := `{ts:%s,int8:%s,id:zmj,device:virtual}`
		tdengine := fmt.Sprintf(str, time.Now().Format(time.RFC3339), strconv.Itoa(i))
		byte, err := json.Marshal(tdengine)
		if err != nil {
			fmt.Println("json marshal err = ", err)
			return
		}
		msg.Payload = byte
		msg.ContentType = "application/json"

		m, err := json.Marshal(msg)
		if err != nil {
			fmt.Println("json marshal msg err = ", err)
			return
		}
		var s types.MessageEnvelope
		err = json.Unmarshal(m, &s)
		if err != nil {
			fmt.Println("json unmarshal err = ", err)
		}
		if _, err := js.Publish(ctx, "TDENGINE.TEST1", m); err != nil {
			fmt.Println("pub error: ", err)
		}`

**Comment by ngjaying** [comment]
I have not looked into eKuiper side. Regarding your json string, it is surely no problem for unmarshall, as a string like "teststring" can be unmarshalled. However, eKuiper only supports if your payload is a real JSON that can be unmarshall to a map, not a string.

**Comment by ngjaying** [comment]
This is a valid json
```json
{"ts":"2023-08-30T09:23:25+08:00","int8":23,"Id":"zmj","device":"virtual"}
```
This is not which is what you are sending, see the markdown complains
```json
{ts:2023-08-30T09:23:25+08:00,int8:23,Id:zmj,device:virtual}
```

**Comment by zouyuxuan** [comment]
I have passed the contentType, but kuiper has not parsed it, and has not parsed the body data yet

                              `
                              case msg, ok := <-messages:
				rcvTime := conf.GetNow()
				if !ok { // the source is closed
					log.Infof("Exit subscription to edgex messagebus topic %s.", es.topic)
					return
				}

				env, ok := msg.(*types.MessageEnvelope)
				if !ok {
					log.Errorf("can not convert interface data to mqtt message.")
					return
				}
				var r interface{}
				switch es.messageType {
				case MessageTypeEvent:
					r = &dtos.Event{}
				case MessageTypeRequest:
					r = &requests.AddEventRequest{}
				}

				if strings.EqualFold(env.ContentType, "application/json") {
					if err := json.Unmarshal(env.Payload, r); err != nil {
						l := len(env.Payload)
						if l > 200 {
							l = 200
						}
						log.Warnf("payload %s unmarshal fail: %v", env.Payload[0:(l-1)], err)
						break
					}
				} else if strings.EqualFold(env.ContentType, "application/cbor") {
					if err := cbor.Unmarshal(env.Payload, r); err != nil {
						l := len(env.Payload)
						if l > 200 {
							l = 200
						}
						log.Warnf("payload %s unmarshal fail: %v", env.Payload[0:(l-1)], err)
						break
					}
				} else {
					log.Errorf("Unsupported data type %s.", env.ContentType)
					break
				}`

**Comment by ngjaying** [comment]
I don't understand your problem by one line description and a bunch of code. If you already identify the problem in the source code, feel free to fix and create a PR. Otherwise, please describe your problem with a detailed step by step description about how to reproduce it. Thanks.

**Comment by Rui-Gan** [comment]
Hi, @zouyuxuan, I believe the issue you're referring to is related to the concept of the message envelope in EdgeX. You can find detailed information about it at the following URL: https://docs.edgexfoundry.org/3.0/design/adr/0023-North-South-Messaging/#message-envelope.

Below is my testing process, for reference only.

stream:
```
bin/kuiper create stream demo '() WITH (type="edgex")'
```

rule:
```
{
	"sql": "SELECT * FROM demo",
	"actions": [{
		"mqtt": {
			"server": "tcp://broker.emqx.io:1883",
			"topic": "demo/test"
		}
	}]
}
```

result:
```
[
  {
    "Id": "zmj",
    "device": "virutal",
    "int8": 1,
    "ts": "2023-09-08T08:27:32Z"
  }
]
```


The program for publishing messages is as follows:
```
        testEvent := dtos.NewEvent("demoProfile", "demo", "demoSource")
	testEvent.Origin = 123
	err = testEvent.AddSimpleReading("device", common.ValueTypeString, "virutal")
	if err != nil {
		fmt.Println("Error adding device to demo: ", err)
	}
	err = testEvent.AddSimpleReading("ts", common.ValueTypeString, time.Now().Format(time.RFC3339))
	if err != nil {
		fmt.Println("Error adding ts to demo: ", err)
	}
	err = testEvent.AddSimpleReading("Id", common.ValueTypeString, "zmj")
	if err != nil {
		fmt.Println("Error adding Id to demo: ", err)
	}
	err = testEvent.AddSimpleReading("int8", common.ValueTypeInt32, int32(1))
	if err != nil {
		fmt.Println("Error adding int8 to demo: ", err)
	}
	data, err := json.Marshal(testEvent)
	if err != nil {
		fmt.Printf("unexpected error MarshalEvent %v", err)
	}
	msg := types.NewMessageEnvelope(data, context.Background())
	msg.ContentType = "application/json"
```

**Comment by ngjaying** [comment]
Closed as no response. Feel free to reopen if you still have problems
