### ISSUE TITLE
No readings are processed for the event, so ignore it

### ISSUE THREAD

**Issue by zouyuxuan** [lf-edge/ekuiper#2226]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
ekuiper flow type is: edgex
configuration group is:nats
listening topic is:edgex/events/device/device-virtual/#
The rule configuration is as follows
![image](https://github.com/lf-edge/ekuiper/assets/33485252/90d012d8-fb74-4665-82f9-f9e8f7cdd2b4)

Nats topic subscribe content
![image](https://github.com/lf-edge/ekuiper/assets/33485252/f8d91e23-1beb-457a-8b84-ee31d690ebb3)

**Comment by ngjaying** [comment]
Thanks for the description. Can you export your rule into a json file in the rule management tab?

**Comment by zouyuxuan** [comment]
{
  "streams": {
    "test": "CREATE STREAM test()WITH (FORMAT=\"json\", CONF_KEY=\"default\", TYPE=\"edgex\", SHARED=\"false\", );\n          "
  },
  "tables": {},
  "rules": {
    "test": "{\"triggered\":true,\"id\":\"test\",\"name\":\"test\",\"sql\":\"SELECT * from test;\",\"actions\":[{\"log\":{\"bufferLength\":1024,\"enableCache\":false,\"format\":\"json\",\"omitIfEmpty\":false,\"runAsync\":false,\"sendSingle\":true}}],\"options\":{\"isEventTime\":false,\"lateTolerance\":1000,\"concurrency\":1,\"bufferLength\":1024,\"sendMetaToSink\":false,\"sendError\":true,\"qos\":0,\"checkpointInterval\":300000,\"restartStrategy\":{\"attempts\":0,\"delay\":1000,\"multiplier\":2,\"maxDelay\":30000,\"jitter\":0.1},\"cron\":\"\",\"duration\":\"\",\"cronDatetimeRange\":null}}"
  },
  "nativePlugins": {},
  "portablePlugins": {},
  "sourceConfig": {
    "edgex": "{\"default\":{\"messageType\":\"event\",\"optional\":{\"ClientId\":\"kuiper-rules-engine\"},\"port\":4222,\"protocol\":\"tcp\",\"server\":\"edgex-nats-server\",\"topic\":\"edgex/events/device/device-virtual/#\",\"type\":\"nats-jetstream\"}}"
  },
  "sinkConfig": {},
  "connectionConfig": {},
  "Service": {},
  "Schema": {}
}

**Comment by Rui-Gan** [comment]
hi, base on your configuration, my log sink successfully receives the following data:
```
time="2023-09-04 05:27:50" level=info msg="sink result for rule myrule: [{\"Int16\":4649}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:27:50" level=info msg="sink result for rule myrule: [{\"Int8\":3}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:27:50" level=info msg="sink result for rule myrule: [{\"Int32\":-159144616}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:27:55" level=info msg="sink result for rule myrule: [{\"Bool\":false}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Float32\":1.816068093270039e+38}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Float64\":-4.587295e+307}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Uint16\":28199}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Uint8\":164}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Uint64\":5986355172763702432}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Uint32\":1561589428}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Int8\":-18}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Int16\":722}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Int64\":-6128680274822970248}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Int32\":-1307428789}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:05" level=info msg="sink result for rule myrule: [{\"Bool\":false}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:15" level=info msg="sink result for rule myrule: [{\"Bool\":false}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:20" level=info msg="sink result for rule myrule: [{\"Int8\":-102}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:20" level=info msg="sink result for rule myrule: [{\"Int32\":-868952112}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:20" level=info msg="sink result for rule myrule: [{\"Int16\":-12932}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:20" level=info msg="sink result for rule myrule: [{\"Int64\":2660425037461654130}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:25" level=info msg="sink result for rule myrule: [{\"Uint32\":3193184367}]" file="sink/log_sink.go:32" rule=myrule
time="2023-09-04 05:28:25" level=info msg="sink result for rule myrule: [{\"Uint64\":1715769222388761729}]" file="sink/log_sink.go:32" rule=myrule
```

I don't quite understand what your problem is. If you are experiencing difficulties receiving data, it is possible that there may be configuration issues in your deployment of EdgeX.

**Comment by ngjaying** [comment]
Close as no response. Feel free to reopen if you still have problems
