### ISSUE TITLE
eKuiper cannot connect to Azure IoT Hub (probably due to missing RenegotiateOnceAsClient)

### ISSUE THREAD

**Issue by tfoldi** [lf-edge/ekuiper#2241]
**Environment**:

- eKuiper version 1.11
- OS (Alpine Linux v3.16
- Others:

**What happened and what you expected to happen**:
When trying to connect to Azure IoT hub the connection establishes but when publishing the first message the server (on Azure side) closes the connection:

```
time="2023-09-07 01:46:06" level=info msg="The connection to mqtt broker tls://iothub-tfoldi.azure-devices.net:8883 client id rpi-tfoldi-1 established" file="mqtt/mqtt_wrapper.go:86"
time="2023-09-07 01:46:06" level=info msg="Reconnecting to mqtt broker tls://iothub-tfoldi.azure-devices.net:8883 client id rpi-tfoldi-1" file="mqtt/mqtt.go:122"
```

**How to reproduce it (as minimally and precisely as possible)**:

Connect to any Azure service using TLS+MQTT

**Anything else we need to know?**:

I am happy to send a PR to include:

```
Renegotiation: tls.RenegotiateOnceAsClient,
```

at

https://github.com/lf-edge/ekuiper/blob/c4d6c64bfe77eab7ebee821657433f97bd463563/internal/pkg/cert/cert.go#L21

However, you might want to make this a config option to enable users to select if they want to support TLS Renegotation or not. It had some security implications in the past. However, hyper scalers enforce its usage (see: https://github.com/golang/go/issues/5742)

**Question**: do you want to fix or shall I send a PR? If you prefer that I make the PR, shall I make `Renegotiation` a config option (Disable - default, Once, Always).

**Comment by ngjaying** [comment]
Thanks @tfoldi for the great insight.
I prefer a PR with a config option.  Maybe add `tlsRenegotiation` option for MQTT source and sink.
