### ISSUE TITLE
WebSocket connectors

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#2248]
Provide WebSocket source or sink by plugin

**Comment by xjasonlyu** [comment]
Why do we support this feature by plugin?

**Comment by ngjaying** [comment]
Some users have to connect data from web socket but not all. So by plugin may be a good idea.

**Comment by ngjaying** [comment]
Yeah, that's also possible. This is just an initiative, it is subject to change during design/implementation.
