### ISSUE TITLE
Load Kafka sink plugin which compiled by myself failed

### ISSUE THREAD

**Issue by silenceli** [lf-edge/ekuiper#2274]
- Version：1.11.2
- host os: debian 10
- arch: amd64
- 编译方法：基于 docker，ghcr.io/lf-edge/ekuiper/base:1.20.2-alpine
- 编译步骤：
1. clone 代码到 /home/lihao.004/ekuiper，切到 tag 1.11.2
2. docker run -it -v /home/lihao.004/ekuiper:/ekuiper ghcr.io/lf-edge/ekuiper/base:1.20.2-alpine sh
3. 进入容器后：
    -  cd /ekuiper/ekuiper
    -  go env -w GOPROXY=https://goproxy.cn,direct
    -  go build -trimpath --buildmode=plugin -o plugins/sinks/kafka.so extensions/sinks/kafka/kafka.go
4. 将 plugins/sinks/kafka.so，及  extensions/sinks/kafka/kafka.json 打包为 kafka.zip
5. 上传到 1.11.2 （使用官方镜像：lfedge/ekuiper:1.11.2） 中，报错：

```
time="2023-09-21 09:10:04" level=info msg="Start to download file https://XXXXXXXX/kafka.zip\n" file="httpx/http.go:158"
time="2023-09-21 09:10:06" level=error msg="plugin kafka open error: plugin.Open(\"/kuiper/plugins/sinks/kafka\"): plugin was built with a different version of package internal/goarch" file="native/manager.go:730"
time="2023-09-21 09:10:06" level=error msg="sinks plugins create command error: fail to install plugin: cannot open /kuiper/plugins/sinks/kafka.so: plugin.Open(\"/kuiper/plugins/sinks/kafka\"): plugin was built with a different version of package internal/goarch" file="server/rest.go:82"
```

**Comment by ngjaying** [comment]
Check this https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#docker-compile

**Comment by silenceli** [comment]
![image](https://github.com/lf-edge/ekuiper/assets/1579708/e0380513-ed7a-43a3-b39d-ab29f75cf277)

can you give me the latest alpine-dev version docker? thx

**Comment by ngjaying** [comment]
No such image yet. If you need such officially shipped plugins, you can download the pre-compiled plugin from ekuiper manager. The url is like https://packages.emqx.net/kuiper-plugins/v1.11.2/debian/sinks/kafka_amd64.zip

**Comment by silenceli** [comment]
I used official kafka sink(https://packages.emqx.net/kuiper-plugins/1.11.2/alpine/sinks/kafka_amd64.zip) which is worked. But I still want to recompile it, because kafka sink plugin do not support `enable_tls` option.

**Comment by silenceli** [comment]
If I want to add a parameter to kafka sink, can I just add a field in kafka.json, and then package it into the kafka.zip package, and it will take effect directly?

**Comment by ngjaying** [comment]
Yes. Looks like you are adding features to Kafka sink, welcome to open a PR. Thanks.

**Comment by manikandan-harman** [comment]
@silenceli are you going to make changes on the kafka plugin to enable the `enable_tls ` option. It's my humble request, we need this ASAP, would you please make this change.

**Comment by ngjaying** [comment]
Already support TLS in 1.12
