### ISSUE TITLE
How to define the same sink in multiple rules (zmq same address but different topics)

### ISSUE THREAD

**Issue by yiyiyaya** [lf-edge/ekuiper#2297]
I defined two rules, the server is the same, the subject is different, the error message is: {"status": "stopped", "message": "Stopped: zmq sink fails to bind to tcp://127.0.0.1:5558: address already in use."}
I guess there may be something wrong with the way I use it. Please tell me the correct way to use it.

**Comment by ngjaying** [comment]
Looks like it is not supported now.  Currently, all sinks will create a new connection but zmq does not allow multiple connections?

**Comment by yiyiyaya** [comment]
See the documentation for supporting connector reuse attributes. Is it feasible to use the connectionSelector attribute to reuse the same connection with multiple sink addresses?[https://ekuiper.org/docs/zh/latest/guide/connector.html](url)

**Comment by ngjaying** [comment]
> See the documentation for supporting connector reuse attributes. Is it feasible to use the connectionSelector attribute to reuse the same connection with multiple sink addresses?[https://ekuiper.org/docs/zh/latest/guide/connector.html](url)

Ah, that only works for MQTT and EdgeX. Other source/sink need code change to adopt to the connectionSelector.

**Comment by yiyiyaya** [comment]
> > See the documentation for supporting connector reuse attributes. Is it feasible to use the connectionSelector attribute to reuse the same connection with multiple sink addresses?[https://ekuiper.org/docs/zh/latest/guide/connector.html](url)
> 
> Ah, that only works for MQTT and EdgeX. Other source/sink need code change to adopt to the connectionSelector.

Got it, thank you very much for your answer

**Comment by ngjaying** [comment]
No problem. Looks like we need a connection poll for zmq to support multiple use of the same connection.
