### ISSUE TITLE
If the rule refers to the custom plug-in, restart the service, and the rule is abnormal

### ISSUE THREAD

**Issue by tansuozhe123** [lf-edge/ekuiper#2301]
<img width="999" alt="8c4c2d6f80742cad0b831caf19a55b7" src="https://github.com/lf-edge/ekuiper/assets/25733524/5a6489b8-0f59-4fe5-8242-a5b034e7de22">
<img width="644" alt="9da271a71ad5cacaff97cdbf6b33bf5" src="https://github.com/lf-edge/ekuiper/assets/25733524/8cf68188-2d28-45d7-8dac-95970bd94651">
<img width="942" alt="53a16d071ed1f1e4b9b1b8f4900fb30" src="https://github.com/lf-edge/ekuiper/assets/25733524/baea5313-16fe-49c4-8c72-427d5f924595">
<img width="978" alt="0b6226a3ca411ce048d25b0cab98684" src="https://github.com/lf-edge/ekuiper/assets/25733524/f8e316f8-cd93-4de0-872a-2b82480c265b">

**Comment by tansuozhe123** [comment]
<img width="617" alt="0c21f8934023eb595827583f277df57" src="https://github.com/lf-edge/ekuiper/assets/25733524/1f21ee01-32ea-4054-8d04-29546fd5761e">
<img width="512" alt="d81bf5a892ce65a1d93a1ea11abd65d" src="https://github.com/lf-edge/ekuiper/assets/25733524/0b480722-5a09-48ae-8cf6-55b7004703ec">
<img width="920" alt="10b7ce6a01fbc898fa7c79da17bb5dd" src="https://github.com/lf-edge/ekuiper/assets/25733524/32a851c9-9d73-4034-a269-77362b1f047c">

**Comment by tansuozhe123** [comment]
Hanging plugins out for persistence still doesn't work

**Comment by zhou0bin** [comment]
我用bin文件，没有用插件，创建规则重启后，也会出现一样的错误
