### ISSUE TITLE
Error when importing ruleset: invalid character 'c' after object key:value pair.

### ISSUE THREAD

**Issue by yiyiyaya** [lf-edge/ekuiper#2312]
The rule template part is \"dataTemplate\": \"{\"content\":{{json (index . 0)}}}\" and the error content is invalid character 'c' after object key:value pair.

**Comment by ngjaying** [comment]
Need to escape " inside quotes, like \"content\"

**Comment by yiyiyaya** [comment]
> Need to escape " inside quotes, like "content"

I wrote the actions part like this:
`\"actions\":[{\"log\":{}},{\"zmq\":{\"server\":\"tcp://127.0.0.1:5551\",\"format\":\"json\",\"topic\":\"temp\",\"sendSingle\": false, \"dataTemplate\": \"{\"content\":{{json (index . 0)}}}\"}}]`

**Comment by ngjaying** [comment]
Looks like the content in template needs double escape \\"content\\" . Try to use and editor to help your convert the quotes. Hand-written is error prone. Or export from an existing eKuiper instance.

**Comment by yiyiyaya** [comment]
It's ok after double escaping, thank you for your help.
