### ISSUE TITLE
The querying quote identifier bug for postgredb

### ISSUE THREAD

**Issue by HungYann** [lf-edge/ekuiper#2313]
**Environment**:

- eKuiper version (e.g. `1.8.0`): 
- Hardware configuration (e.g. `lscpu`): Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz
- OS (e.g. `cat /etc/os-release`): PRETTY_NAME="Ubuntu 23.04"
- Others:

**What happened and what you expected to happen**:
When I use ekuiper to acquire data from postgredb, I find there is a bug in the sql statement.

![image](https://github.com/lf-edge/ekuiper/assets/55868230/c27a2c5f-6e5d-4b85-96e0-ca94e65b42f4)

You can see, there is a quota around ts, like 'ts' and  because the ekuiper  uses quotes around 'ts' in the ORDER BY clause, causing the database system to interpret it as a string constant instead of a column name.

the error log like the picture below:
<img width="1485" alt="image" src="https://github.com/lf-edge/ekuiper/assets/55868230/ae12bc11-9e92-4fc1-8c0d-c691b1b70633">

and when I use the db client to run the sql statement, it also occurs error
<img width="801" alt="image" src="https://github.com/lf-edge/ekuiper/assets/55868230/6c046e61-e56b-4b3e-83ac-5eb71018d8c3">

**How to reproduce it (as minimally and precisely as possible)**:

If u wanna reproduce it, u can use ekuiper to connect postgredb and set both indexField and indexValue. After u have done, u can see the sql statement in the log:

ekuiper stream configuration:

<img width="580" alt="image" src="https://github.com/lf-edge/ekuiper/assets/55868230/206a9c1e-ab77-4c81-ac4a-f2e125eadcd2">

log:
```
select * from ts_kv where ts > '1697010531464' order by 'ts' ASC limit 1
```

**Anything else we need to know?**:

the right statement is `select * from ts_kv where ts > '1697010531464' order by ts ASC limit 1`.  the main point is that the quote identifier around ts should be removed. 

<img width="535" alt="image" src="https://github.com/lf-edge/ekuiper/assets/55868230/9c7bec60-8971-420f-9f53-1c0c6940b98a">

the code position is below

<img width="1204" alt="image" src="https://github.com/lf-edge/ekuiper/assets/55868230/53793d9e-1880-47c7-ba79-8b92d3cffce5">

```go
func (q *CommonQueryGenerator) getOrderby() string {
	if q.IndexField != "" {
		return "order by " + q.quoteIdentifier(q.IndexField) + " ASC "
	}
	return ""
}
```

```go
func (q *CommonQueryGenerator) quoteIdentifier(identifier string) string {
	return "'" + identifier + "'"
}
```

In postgredb, it doesn't support sinlge quote for the field ts. U can use double quote to replace it (single quote for ts) or remove the `q.quoteIdentifier()`

By the way, it's ok for mysql.

**Comment by ngjaying** [comment]
Thanks for the super detailed description! Since you have identify the problem, would you like to submit a PR?
