### ISSUE TITLE
specified wrong type value zero

### ISSUE THREAD

**Issue by junf-liu** [lf-edge/ekuiper#2323]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
作者您好，使用docker拉取的ekuiper镜像，在创建edgex创建数据源时选择zero类型作为消息输入。启动规则时提示“specified wrong type value zero”，请问如何解决？

**Comment by ngjaying** [comment]
ZeroMQ type message bus has been removed for EdgeX v2.

**Comment by junf-liu** [comment]
您好，请问降低EdgeX版本？或者是降低ekuiper版本？想接入zeromq消息，但是使用编译zmq源插件方式集成一直未能接收到消息，想试试使用EdgeX 方式接收zeromq消息，多谢！
