### ISSUE TITLE
need for Cloud management

### ISSUE THREAD

**Issue by cai6489** [lf-edge/ekuiper#2391]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
May I ask if ekuiper has plans for cloud management? If ekuiper is running on multiple edge nodes, how do I ensure that the rules are correctly delivered to the corresponding edge nodes？

**Comment by ngjaying** [comment]
EMQX has a product, could you please contact in https://www.emqx.com/en/contact

**Comment by ngjaying** [comment]
Anyone who looks for eKuiper management, please take a look at this: https://www.emqx.com/en/try?product=neuronex
