### ISSUE TITLE
Incorrect Behavior of eKuiper API for start/stop Rules

### ISSUE THREAD

**Issue by EscanorUt** [lf-edge/ekuiper#2407]
## Environment
- eKuiper version: 1.11.4
- OS: docker-alpine

## Bug Description
The eKuiper API to stop rules is responding with 200 OK HTTP Status when providing inexistent rule id unlike the start API which returns 400 Bad Request HTTP Status

## Expected Behavior
The expected behavior is for the eKuiper stop rule API to return 400 Bad Request HTTP Status when the id provided does not exist.

## Steps to Reproduce
1. Try to stop a rule that does not exist
2. Observe that the API returns a "200 OK" status code instead of the expected "400 Bad Request" status code.

## Additional Information
![image](https://github.com/lf-edge/ekuiper/assets/145465122/f2805012-bd78-4c7f-a5b8-7f86b2a88b85)

**Comment by ngjaying** [comment]
OK, it is reasonable. Currently stop does not check existence. It returns 200 only means the rule is NOT started.
