### ISSUE TITLE
fatal error: runtime: no plugin module data

### ISSUE THREAD

**Issue by tansuozhe123** [lf-edge/ekuiper#2461]
I compiled a rabbitmq plugin, but the system carsh when creating the plugin, error message is as follows：
<img width="908" alt="128e648bd80c2096c97b44d64c0647f" src="https://github.com/lf-edge/ekuiper/assets/25733524/7d0b7cc2-98bb-4fd5-a23d-c4f1bef0696a">

**Comment by tansuozhe123** [comment]
build ekuiper and plugin with cgo enabled

**Comment by ngjaying** [comment]
Are you able to compile and load any plugins like extensions/sources/random

**Comment by tansuozhe123** [comment]
No, now the plugin can be uploaded and unzipled, but it cannot be opened. There is a.so file in the plugins directory, but calling plugin.open () will give an error

**Comment by tansuozhe123** [comment]
Do the go version of the build plugin and the go version of ekuiper have to be the same?

**Comment by ngjaying** [comment]
> Do the go version of the build plugin and the go version of ekuiper have to be the same?

Sure. Not just go version. You'd better to build them in the exact same env. That is the limitation of Go plugin.

**Comment by ngjaying** [comment]
Still build env problem. Please read the plugin tutorial carefully.

**Comment by tansuozhe123** [comment]
ekuiper is compiled using the golang:1.21.0 image. The plugin is compiled locally using the docker container packaged with the golang:1.21.0 image, which is not on the same device. Is there a problem?

**Comment by ngjaying** [comment]
Close for now. Feel free to reopen if encountering problems.
