### ISSUE TITLE
Create an average value using Flow, which failed immediately after running

### ISSUE THREAD

**Issue by junf-liu** [lf-edge/ekuiper#2467]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
The rule fails immediately after being run. The message "interface conversion: interface {} is float64, not []interface 
data is {" age" :30}"
source is mqtt, sink is mqtt, run SQL rule ok

**Comment by ngjaying** [comment]
In Graph API, aggregate function must connect to aggregate node like time window.

**Comment by ngjaying** [comment]
This is working as design for now. Plan to support this usage after implementing #2504
