### ISSUE TITLE
SQLLookup postgresql

### ISSUE THREAD

**Issue by o8oo8o** [lf-edge/ekuiper#2474]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.11.5 +
- Hardware configuration (e.g. `lscpu`): 
- OS  Ubuntu 22.04 Server:
- Others:

**What happened and what you expected to happen**:
SQLLookup postgresql database  nonsupport ”`“ As a field translation
[code](https://github.com/lf-edge/ekuiper/blob/master/extensions/sources/sql/ext/sqlLookup.go#L139)

**Comment by ngjaying** [comment]
Thanks. Since you have identified the problem in the source code, would you mind just fix it by a PR.
