### ISSUE TITLE
Support Needed:support the existence of join and window at the same time

### ISSUE THREAD

**Issue by lpf4254302** [lf-edge/ekuiper#2503]
Now the graph rule does not support the existence of join and window at the same time, because the join output is COLLECTION, and the window input is ROW. In fact, this situation is more common, and there is a solution: Make the script output dynamic, convert COLLECTION to ROW, or make window support COLLECTION directly

**Comment by ngjaying** [comment]
Check #2504 , close this as a duplicate.
