### ISSUE TITLE
/root/go/pkg/mod/github.com/taosdata/driver-go/v2@v2.0.4/wrapper/asynccb.go:7:18: fatal error: taos.h: No such file or directory  #include <taos.h>

### ISSUE THREAD

**Issue by lzh123** [lf-edge/ekuiper#2507]
![image](https://github.com/lf-edge/ekuiper/assets/21017205/f441dbf2-b219-49ed-b092-f2443fec295c)

**Comment by lzh123** [comment]
yum install gcc ;
then go build -trimpath --buildmode=plugin -o plugins/sinks/Tdengine@v1.0.0.so extensions/sinks/tdengine/tdengine.go
but fail,error like before, how can I do it?

**Comment by ngjaying** [comment]
Need to install tdengine client.
