### ISSUE TITLE
Source rate limit

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#2529]
Handle messages at regular rate, by time or by count.

**Comment by yai-dev** [comment]
@ngjaying rate limit for what? http pull source?

**Comment by ngjaying** [comment]
This is a general operator for all kinds of sources. It is run before decoding to limit/down-sample the ingest rate(may be 1 message per us) to a lower qps like 1 message per second. It will prevent unnecessary calculation like decoding (json unmarshall as an example) when the users don't need a verfy high ingest throughput
