### ISSUE TITLE
More array and object functions

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#2530]
- [x] object_pick(key...): Returns a new object containing some of the key-value pairs from an existing object. Example, object `{"a":1,  "b":2, "c":3}`, object_pick('a','c') return `{"a":1,  "c":3}`
- [ ] kvpair_array_to_obj(array, [keyFieldName], [valueFieldName]): Returns a new converting from a kv pair array, such as `[{"key":"key1", "value":1},{"key":"key2", "value":2}]`, to `{"key1":1, "key2":2}`.
- [ ] obj_to_kvpair_array(obj, [keyFieldName], [valueFieldName]): A revert function of kvpair_array_to_obj

**Comment by rextang** [comment]
Hi, I'm interested in this issue. Can I implement these functions?

**Comment by ngjaying** [comment]
> Hi, I'm interested in this issue. Can I implement these functions?

Sure, warm welcome
