### ISSUE TITLE
Ask if json path exists can use string functions

### ISSUE THREAD

**Issue by junf-liu** [lf-edge/ekuiper#2547]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
as follows SELECT name->last FROM demo where json_path_exists(followers, "$.Group1[? (startswith(@.first,'John'))]")
The result is always false

**Comment by ngjaying** [comment]
What's the data?

**Comment by junf-liu** [comment]
I'm sorry, this is data
{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 44},
    {"first": "Roger", "last": "Craig", "age": 68},
    {"first": "Jane", "last": "Murphy", "age": 47}
  ],
    "followers": {
        "Group1": [
            {"first": "John", "last": "Shavor", "age": 22},
            {"first": "Ken", "last": "Miller", "age": 33}
        ],
        "Group2": [
            {"first": "Alice", "last": "Murphy", "age": 33},
            {"first": "Brian", "last": "Craig", "age": 44}
        ]
    },
   "ops": {
       "functionA": {"numArgs": 2},
    "functionB": {"numArgs": 3},
    "functionC": {"variadic": true}
  }
}

**Comment by ngjaying** [comment]
There is no `startswith` in jsonpath. Use `json_path_exists(followers, "$.Group1[?(@.first==\"John\")]")` can work.
