### ISSUE TITLE
error of installing the sink plugin of tdengine

### ISSUE THREAD

**Issue by wzmyx99318** [lf-edge/ekuiper#2558]
**Environment**: docker  lfedge/ekuiper:1.12.3 

**What happened and what you expected to happen**:
The sink plugin of tdengine cannot be installed.

The version of tdengine is 2.6.0.34

If I use the default URL (https://packages.emqx.net/kuiper-plugins/1.12.3/alpine/sinks/tdengine_amd64.zip): 
Report:   sinks plugins create command error: fail to download file https://packages.emqx.net/kuiper-plugins/1.12.3/alpine/sinks/tdengine_amd64.zip: cannot download the file with status: 403 Forbidden

If I use the URL given in doc (https://packages.emqx.net/kuiper-plugins/1.12.3/debian/sinks/tdengine_amd64.zip)
Report:   sinks plugins create command error: fail to install plugin: exit status 127

**Comment by ngjaying** [comment]
I think this is a duplicate of #2314

**Comment by wzmyx99318** [comment]
This is a problem caused by versions of docker images offered by the official team of ekuiper.
#2314 is to create a docker image by himself. So it's not the same.
But it's very lucky for me that after I change the image to 1.12.3-slim, the sink plugin can be installed.
I think more comments should be added for that.

**Comment by ngjaying** [comment]
lol. We just didn't provide the pre-built tdengine plugin for alpine, so users need to build by themselves. #2314 is still calling for help to build that in CI.

**Comment by wzmyx99318** [comment]
Btw, do you have the plan to support tdengine 3.x in the sink plugin?
Ekuiper seems to only support tdengine 2.6 as the latest version.
But you know, 2.6 is published one year ago and 3.x is said to be better than 2.x by the official team of tdengine

**Comment by ngjaying** [comment]
Yes, another issue #2054, call for help
