### ISSUE TITLE
date_calc function not support in the second argument duration like "10h"

### ISSUE THREAD

**Issue by MhamedHr** [lf-edge/ekuiper#2568]
**Environment**:

- eKuiper version (e.g. `1.3.0`): ekuiper:1.11.4
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): Ubunutu[WSL]
- Others:

**What happened and what you expected to happen**:
I can't create rule using `date_calc(date, duration)` function

**How to reproduce it (as minimally and precisely as possible)**:
When i create rule based in this formula : date_calc(varDate, "10h2m") => `varDate` de type datetime

**Anything else we need to know?**:

**Comment by Yisaer** [comment]
@MhamedHr 
Could you provide the rule, input data, actual output result and expected result.

**Comment by yai-dev** [comment]
@MhamedHr Could you provide some more information? When I ran unit tests with your input arguments, there were no errors and the result was as expected.

**Comment by younes199511** [comment]
Hello @yai-dev, @Yisaer,
I had the same error too using eKuiper 1.11.4

![image](https://github.com/lf-edge/ekuiper/assets/44032734/7375324c-e009-40b7-bbe4-c64a8e681e4f)

**Comment by yai-dev** [comment]
@younes199511 @MhamedHr Hi there, I has founded why and create new PR for fix it.
