### ISSUE TITLE
improve function validation

### ISSUE THREAD

**Issue by carlclone** [lf-edge/ekuiper#2588]
in validator_funcs.go , function ValidateTwoNumberArg

```
	if ast.IsFloatArg(args[0]) || ast.IsStringArg(args[0]) || ast.IsTimeArg(args[0]) || ast.IsBooleanArg(args[0]) {
		return ProduceErrInfo(0, "int")
	}
```

since it accept all expression and only int literal , can we rewrite it to 

```
if ast.isLiteral() && !ast.IsIntegerArg() {
		return ProduceErrInfo(0, "int")
	}
```

**Comment by ngjaying** [comment]
Yes, that is the ideal case. The problem is that in schema-less mode, we do not know the arg's type in the parser time.
