### ISSUE TITLE
The path description of the "default Neuron connector configuration" in Chinese document issue.

### ISSUE THREAD

**Issue by xiaozexuan** [lf-edge/ekuiper#2611]
The path description of the "default Neuron connector configuration" in the Chinese document is different from that in the English document.So,which one is correct?

![1707117354146](https://github.com/lf-edge/ekuiper/assets/47739006/32010ff8-4871-4765-bcef-30ca147940ea)

![e05f250fdcbc4485bb54523d93931ef](https://github.com/lf-edge/ekuiper/assets/47739006/11320037-21de-44e7-9475-e899b242c5b2)

**Environment**:

- eKuiper version (e.g. `1.3.0`): lastest
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**Comment by ngjaying** [comment]
Ah, apparently English version is correct. Would you like to fix it? Feel free to open a PR.
