### ISSUE TITLE
go build  plugins sql  unknown directive: toolchain

### ISSUE THREAD

**Issue by gooker** [lf-edge/ekuiper#2627]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

go version
go version go1.20.10 linux/amd64

go build -trimpath --buildmode=plugin -o plugins/sinks/Sql.so extensions/sinks/sql/sql.go
reading go.work: /root/ekuiper-1.12.4/go.work:3: unknown directive: toolchain

**Comment by ngjaying** [comment]
The current master branch needs go 1.21. Check the go.mod file for the required go version

**Comment by gooker** [comment]
> The current master branch needs go 1.21. Check the go.mod file for the required go version

thanks
