### ISSUE TITLE
Incorrect results of computation that has grouped integer division

### ISSUE THREAD

**Issue by EscanorUt** [lf-edge/ekuiper#2628]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.11.4 & 1.12.4
- Hardware configuration:
- OS: Alpine docker image running on Ubuntu 22.04 host
- Others:

**What happened and what you expected to happen**:
When you calculate expression that hast grouped integer division like (6/5)+4, it returns 5 instead of 5.2. 
The grouped integer division is always calculated as an integer even if the result is a float.
**How to reproduce it (as minimally and precisely as possible)**:
Calculate (6/5)+4 with eKuiper

**Comment by ngjaying** [comment]
Try to use 6.0/5. Currently, the calculation just leverage the golang's calculation which will return integer if both operands are integer.
