### ISSUE TITLE
Can not create a rule that starts with '-' prefix and expression between parenthesis 

### ISSUE THREAD

**Issue by younes199511** [lf-edge/ekuiper#2629]
**Environment**:

**Environment**:

- eKuiper version:  1.11.4
- Hardware configuration: Intel I-7 CPU
- OS: Alpine docker image
- Others:

**What happened and what you expected to happen**:
if you try to create a rule with expression that starts with '-' prefix and expression between parenthesis, it is refused and it should be accepted as it is a valid mathematical expression that can be used in any other calculator. 

**How to reproduce it (as minimally and precisely as possible)**:
try to create a rule with -(5+2) for example 
`SELECT -(5+2) as comp_result`

**Anything else we need to know?**:

![image](https://github.com/lf-edge/ekuiper/assets/44032734/595f0b13-559e-4118-bda2-538b8b338de4)

**Comment by ngjaying** [comment]
For simplicity, the unary operator - is not supported. You should be able to use 0-(5+2) as an alternative.

**Comment by younes199511** [comment]
Hello @ngjaying 
Thank you for you answer. Yes there is a work around but i thought that it is a bug as the unary operator is accepted if it is followed by a numeric value like -1*(5+2).
