### ISSUE TITLE
There is some Chinese text on this page

### ISSUE THREAD

**Issue by nrdmao33** [lf-edge/ekuiper#2633]
File: [/docs/en_US/guide/ai/python_tensorflow_lite_tutorial.md](https://ekuiper.org/docs/en/latest/guide/ai/python_tensorflow_lite_tutorial.html)

See https://ekuiper.org/docs/en/latest/guide/ai/python_tensorflow_lite_tutorial.html#%E5%AE%9A%E4%B9%89%E8%A7%84%E5%88%99

**Comment by ngjaying** [comment]
Thanks for reporting this, we will translate and update
