### ISSUE TITLE
ekuiper-manager docker 1.9.x rules cant modify

### ISSUE THREAD

**Issue by gooker** [lf-edge/ekuiper#2637]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.12.4
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): rocky 9.3
- Others:

**What happened and what you expected to happen**:
update ekuiper-manager  dashboard

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://github.com/lf-edge/ekuiper/assets/5688076/b10283bb-da83-4cdc-9da2-1d7b4ec96132)

**Comment by ngjaying** [comment]
Seems like browser cache problem. Log out and login again or run in ignite mode.

**Comment by gooker** [comment]
> Seems like browser cache problem. Log out and login again or run in ignite mode.

I have been using it for a while and it has been like this all along. The editing rules are not convenient. Is it possible to update it if the versions are different and incompatible

![image](https://github.com/lf-edge/ekuiper/assets/5688076/4647da06-e87f-43c3-b9af-06817f292710)

**Comment by ngjaying** [comment]
I am afraid not, manager is not updating now. Anyone who looks for eKuiper management, please take a look at this: https://www.emqx.com/en/try?product=neuronex
