### ISSUE TITLE
Portable plugin mirror example issue

### ISSUE THREAD

**Issue by RyIot3329** [lf-edge/ekuiper#2646]
Hello, I am trying to go through and use the mirror example in the sdk to get used to developing plugins. I can upload the mirror.zip just fine, but when I try to use the echo() function, it gives me an error. Here is the error log:

time="2024-02-27 17:20:30" level=info msg="Start running portable function meta &{Name:mirror Version:v1.0.0 Language:go Executable:/kuiper/plugins/portable/mirror/mirror}" file="runtime/function.go:37"

time="2024-02-27 17:20:30" level=info msg="create control channel" file="runtime/plugin_ins_manager.go:165"

time="2024-02-27 17:21:00" level=error msg="Error creating function can't create new control channel: can't listen on rep socket: listen unix /tmp/plugin_mirror.ipc: bind: read-only file system" file="portable/factory.go:59"

time="2024-02-27 17:21:00" level=info msg="Start running portable function meta &{Name:mirror Version:v1.0.0 Language:go Executable:/kuiper/plugins/portable/mirror/mirror}" file="runtime/function.go:37"

time="2024-02-27 17:21:00" level=info msg="create control channel" file="runtime/plugin_ins_manager.go:165"

time="2024-02-27 17:21:31" level=error msg="Error creating function can't create new control channel: can't listen on rep socket: listen unix /tmp/plugin_mirror.ipc: bind: read-only file system" file="portable/factory.go:59"

time="2024-02-27 17:21:31" level=error msg="Update rule error: Parse SQL SELECT echo(*) from demo; error: Get multiple errors: \nportable plugin:can't create new control channel: can't listen on rep socket: listen unix /tmp/plugin_mirror.ipc: bind: read-only file systemexternal service:service function echo not found." file="server/rest.go:69"

Any suggestions?

**Comment by ngjaying** [comment]
@RyIot3329 Looks like /tmp is readonly in your system. Is it possible to make it writable which is required for portable plugin.

**Comment by RyIot3329** [comment]
So I am using the official docker  container, looks like I have all of the required permissions for tmp

drwxr-xr-x    1 root     root          4096 Feb 27 20:16 .
drwxr-xr-x    1 root     root          4096 Feb 27 20:16 ..
-rwxr-xr-x    1 root     root             0 Feb 27 20:16 .dockerenv
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 bin
drwxr-xr-x    5 root     root           340 Feb 27 20:16 dev
drwxr-xr-x    1 root     root          4096 Feb 27 20:16 etc
drwxr-xr-x    1 root     root          4096 Feb 27 20:16 home
drwxr-xr-x    1 kuiper   kuiper        4096 Feb 22 21:44 kuiper
drwxr-xr-x    7 root     root          4096 Jan 26 14:41 lib
drwxr-xr-x    5 root     root          4096 Jan 26 14:41 media
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 mnt
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 opt
dr-xr-xr-x  431 root     root             0 Feb 27 20:16 proc
drwx------    2 root     root          4096 Jan 26 14:41 root
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 run
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 sbin
drwxr-xr-x    2 root     root          4096 Jan 26 14:41 srv
dr-xr-xr-x   13 root     root             0 Feb 27 20:16 sys
**drwxrwxrwt    2 root     root          4096 Jan 26 14:41 tmp**
drwxr-xr-x    1 root     root          4096 Jan 26 14:41 usr
drwxr-xr-x   12 root     root          4096 Jan 26 14:41 var

I also tried mounting the tmp directory to a local directory and it still throws the Read-only filesystem error

**Comment by ngjaying** [comment]
Are you using default/alpine docker image? The default user is kuiper not root. You can explicitly use root user when starting the container.

**Comment by RyIot3329** [comment]
I am using the alpine version. Ok, I see what you are saying now. Is there a way to be able to use portable plugins as the kuiper user? I don't seem to be able to change ownership of tmp because it is read only.

**Comment by ngjaying** [comment]
If you are going to use python plugin, we would recommend using the slim-python version.

**Comment by RyIot3329** [comment]
Got it. So I ran it with the user: root option and don't get that specific error anymore and the plugin seems to start. But I get this error:

Update rule error: Invalid rule json: Parse SQL SELECT echo(*) from demo; error: portable plugin:plugin executable /kuiper/plugins/portable/mirror/mirror stops with error fork/exec /kuiper/plugins/portable/mirror/mirror: no such file or directory external service:service function echo not found.

This is the ls from the portable/mirror directory

-rw-r--r--    1 root     root          1055 Feb 27 22:04 echo_func.go
-rw-r--r--    1 root     root          1359 Feb 27 22:04 echo_func_test.go
-rw-r--r--    1 root     root          2976 Feb 27 22:04 file_sink.go
-rw-r--r--    1 root     root          1426 Feb 27 22:04 file_sink_test.go
-rw-r--r--    1 root     root           533 Feb 27 22:04 go.mod
-rw-r--r--    1 root     root          3498 Feb 27 22:04 go.sum
-rw-r--r--    1 root     root          1124 Feb 27 22:04 main.go
-rwxr-xr-x    1 root     root       4387172 Feb 27 22:04 mirror
-rw-r--r--    1 root     root           166 Feb 27 22:04 mirror.json
-rw-r--r--    1 root     root          4087 Feb 27 22:04 random_source.go
-rw-r--r--    1 root     root          3015 Feb 27 22:04 random_source_test.go

I am using this repo as an example

https://github.com/lf-edge/ekuiper/tree/master/sdk/go/example/mirror

**Comment by ngjaying** [comment]
@RyIot3329 For go portable plugin, you need to build the executable. In this example, it is "mirror". You can change the executable name by modifying the mirror.json file if needed.

**Comment by RyIot3329** [comment]
Yeah I have run go build -o mirror

Here are the steps I took - 

Cloned eKuiper project
cd into sdk/go/example/mirror
run "go build -o mirror"
zipped up all files into a mirror.zip
Uploaded zip file via kuiper dashboard (this was successful)
Attempted to use the echo function in a SELECT statement 

error: portable plugin:plugin executable /kuiper/plugins/portable/mirror/mirror stops with error fork/exec /kuiper/plugins/portable/mirror/mirror: no such file or directory external service:service function echo not found

I have provided the zip file I am using here
[mirror.zip](https://github.com/lf-edge/ekuiper/files/14435109/mirror.zip)

**Comment by ngjaying** [comment]
@RyIot3329 Can you go into /kuiper/plugins/portable/mirror and run .mirror. It is likely the built executable does not work. When building the executable, try "CGO_ENABLED=0 go build -o mirror"

**Comment by ngjaying** [comment]
Close for no response

**Comment by yoiberdev** [comment]
portable plugin create command error: fail to install plugin: missing mirror
