### ISSUE TITLE
Some rules are ineffective or non-functional.

### ISSUE THREAD

**Issue by Gaurang2811** [lf-edge/ekuiper#2688]
In our implementation with EdgeX Jakarta 2.1, we manage multiple devices, each with various attributes. Our process involves creating CONF_KEY, STREAMS, and RULES using automation code leveraging Kuiper REST APIs. 
Upon device creation, we generate unique CONF_KEYs, STREAMS, and RULES for each attribute. The SQL logic within the RULES may differ based on contextual conditions.

The rules ingest data from Redis as a source and utilize Redis as the sink. However, we've encountered an issue where certain rules fail to trigger intermittently. 
We are facing this intermittent issue with random Rule, we haven't observed any similarity or pattern with the Rules which are not working also restaring the affected Rule resolves the issue.

Our debugging efforts have confirmed that the details in CONF_KEY, Stream, and Rule are correct, rule is in running state, and data is consistently flowing through the input source channel in Redis.
Currently, we have around 300-400 rules running parallelly.

Kuiper version 1.6.3
EdgeX Version 2.1

Attaching Kuiper log, the Rule with ID: RULE_8XP3M5VWQRJG_7MX8KA5DKEE8 is failing for this case.
[kuiper-log.zip](https://github.com/lf-edge/ekuiper/files/14539960/kuiper-log.zip)

**Comment by ngjaying** [comment]
Hi @Gaurang2811 I am sorry that the eKuiper version is too old. Is it possible to upgrade and check?

**Comment by ngjaying** [comment]
Close as no update for one month. Feel free to reopen if you still have questions.
