### ISSUE TITLE
personal information leak in copyright declaration

### ISSUE THREAD

**Issue by Matrix0xCC** [lf-edge/ekuiper#2696]
https://github.com/lf-edge/ekuiper/blob/c627313c9d7837e47418442d9b689c63af2939a2/internal/server/wasm_init.go#L1

**Comment by ngjaying** [comment]
Hi @Matrix0xCC This is intentional. The copyright belongs to the contributors, either personal or company.

**Comment by Matrix0xCC** [comment]
ok
