### ISSUE TITLE
Add Gzip/Brotli compression to REST sink

### ISSUE THREAD

**Issue by webfrank** [lf-edge/ekuiper#2714]
**What would you like to be added/modified**:

Add Gzip/Brotli, or any other compatible compression algorithm, to REST sink.

**Why is this needed**:

When sending large JSON/XML payload, compressing POST would benefit in terms of latency.

**Comment by yai-dev** [comment]
@ngjaying Hi there, is this issue still open and i saw there has releated pr has been closed, can i create pr for this issue?

**Comment by ngjaying** [comment]
@yai-dev I think @carlclone is working on this now. @carlclone Can I assign this to you?

**Comment by yai-dev** [comment]
> @yai-dev I think @carlclone is working on this now. @carlclone Can I assign this to you?

okay, i see this issue has been opened for a long time (about 1 month at least) and this feature is not complex, i will look another issue to be fixing, if @carlclone has long time to not respond, i will try to working on this.

**Comment by carlclone** [comment]
yes , feel free to contribute  , i don't have enough time recently , you can continue this issue

**Comment by yai-dev** [comment]
> yes , feel free to contribute , i don't have enough time recently , you can continue this issue

OK, thx pal
