### ISSUE TITLE
Sliding Window Validation in Graphe Rule

### ISSUE THREAD

**Issue by younes199511** [lf-edge/ekuiper#2725]
**Environment**:

- eKuiper version:  Tested in 1.11.4 - 1.12.7 - 1.13.0
- OS: Alpine docker image running on Ubuntu 22.04 host

**What happened and what you expected to happen**:
When using graph rule, Sliding window validation returns error if delay is not equal de window size

**How to reproduce it (as minimally and precisely as possible)**:
- Try to create the following graph rule
```json
{
    "id": "rule1Graph",
    "name": "Test Condition",
    "graph": {
        "nodes": {
            "demo": {
                "type": "source",
                "nodeType": "edgex",
                "props": {
                    "format": "json"
                }
            },
            "window": {
                "type": "operator",
                "nodeType": "window",
                "props": {
                    "type": "SLIDINGWINDOW",
                    "unit": "ss",
                    "size": 30,
                    "interval":5
                }
            },
            "avgfunc": {
                "type": "operator",
                "nodeType": "aggfunc",
                "props": {
                    "expr": "cast(avg(Temperature), \"string\") as comp_result"
                }
            },
            "pick": {
                "type": "operator",
                "nodeType": "pick",
                "props": {
                    "fields": [
                        "comp_result"
                    ]
                }
            },
            "logOut": {
                "type": "sink",
                "nodeType": "log",
                "props": {}
            }
        },
        "topo": {
            "sources": [
                "demo"
            ],
            "edges": {
                "demo": [
                    "window"
                ],
                "window": [
                    "avgfunc"
                ],
                "avgfunc": [
                    "pick"
                ],
                "pick": [
                    "logOut"
                ]
            }
        }
    }
}
```

![image](https://github.com/lf-edge/ekuiper/assets/44032734/b49f6e9c-1248-48cb-acb0-be06f9ab45c1)

**Anything else we need to know?**:
The bug is not reproductible when using sql rule 

![image](https://github.com/lf-edge/ekuiper/assets/44032734/5efa3bc4-d8f6-4b12-a72a-8fd019cea2f7)

**Comment by ngjaying** [comment]
Hi @younes199511 slidingWindow the 3rd argument means the dealy triggerred time. This is not supported in Graph API yet.

**Comment by younes199511** [comment]
Thank you, i didn't know that (It will be great if you add it to the doc). In that case why it accepts the delay parameter if it is equal to the window size ?

**Comment by ngjaying** [comment]
Check the doc here https://ekuiper.org/docs/en/latest/sqls/windows.html#sliding-window. It was added recently, before that there are only two arguments, so it takes up the thrid argument. The window size in graph is not necessarily mapped to the third argument in the SQL window function.
