### ISSUE TITLE
where  is  eKuiper manager  code？

### ISSUE THREAD

**Issue by icetech233** [lf-edge/ekuiper#2773]
eKuiper manager 是一个免费的 eKuiper 管理控制台，以 Docker 镜像的形式提供。我们可以使用 docker compose 来一键运行 eKuiper 和 eKuiper manager。

**Comment by icetech233** [comment]
<html>
<body>

编号 | 名称 | 提供商 | 开源
-- | -- | -- | --
1 | EMQX Neuron | EMQ | 否 - 1
2 | EMQX Edge | EMQ | 是, Apache 2.0
3 | EMQX Kuiper | EMQ | 是, Apache 2.0
4 | Edge manager | EMQ | 否 - 2
5 | TDengine | Taosdata | 是, GNU AGPL v3.0
6 | Grafana | Grafana Labs | 是, Apache 2.0



为啥不开源啊



</body>
</html>编号	名称	提供商	开源
1	[EMQX Neuron](https://www.emqx.com/zh/products/neuronex)	EMQ	否 - 1
2	[EMQX Edge](https://www.emqx.com/zh/products/emqx)	EMQ	是, Apache 2.0
3	[EMQX Kuiper](https://github.com/lf-edge/ekuiper)	EMQ	是, Apache 2.0
4	[Edge manager](https://hub.docker.com/r/emqx/edge-manager)	EMQ	否 - 2
5	TDengine	Taosdata	是, GNU AGPL v3.0
6	Grafana	Grafana Labs	是, Apache 2.0

**Comment by ngjaying** [comment]
Please do a search before opening an issue. There are already similar issues.
