### ISSUE TITLE
Can not filter nil arrays

### ISSUE THREAD

**Issue by EscanorUt** [lf-edge/ekuiper#2865]
**Environment**:

- eKuiper version: 1.12.8
- Hardware configuration :
- OS: Alpine Docker Image

**What happened and what you expected to happen**:
When using eKuiper, i'm not able to filter nil arrays. I'm getting the following error in the logs:

![image](https://github.com/lf-edge/ekuiper/assets/145465122/f44b7d2c-da85-4240-9433-f28094e4d9c1)

**How to reproduce it (as minimally and precisely as possible)**:
Create a rule with the following expression 
`array_create(1,2) != nil`

**Comment by ngjaying** [comment]
How about `isNull(array_create(1,2)) = false`

**Comment by EscanorUt** [comment]
That's working fine. Thank you
