### ISSUE TITLE
Compiling SQL source plugin with docker container

### ISSUE THREAD

**Issue by abhibhatia98** [lf-edge/ekuiper#3018]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

Hi Community, I was trying to install SQL source plugin, following [this](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/guide/sources/plugin/sql.md) guide, I have followed below steps 
1. Cloned [this](https://github.com/lf-edge/ekuiper/tree/master) repo
2. Run below command
`go build -trimpath --buildmode=plugin -tags sqlserver -o plugins/sources/Sql.so extensions/sources/sql/*.go`
3. copy  plugins/sources/Sql.so to /plugins/source in docker container
4. Restart docker container
It gives me below error in docker container logs 
` level=error msg="plugin sql open error: plugin.Open(\"/kuiper/plugins/sources/Sql.so\"): Error loading shared library libresolv.so.2: No such file or directory (needed by /kuiper/plugins/sources/Sql.so)" file="native/manager.go:746"`
 
 
Please help, is it the right way to work, not sure if this going to work with docker or not ?

Thanks

**Comment by ngjaying** [comment]
We have pre-built plugin in url endpoint https://packages.emqx.net/kuiper-plugins/{version}/{os}/{type}/sql_{arch}.zip, for example, https://packages.emqx.net/kuiper-plugins/1.10.0/alpine/sinks/sql_amd64.zip. You can install directly.
If you want to build from source code, check this https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#plugin-deployment

**Comment by abhibhatia98** [comment]
Hi @ngjaying, thanks for quick response, I tried it gives me below error in API response, Do I have to pass script parameter as well, like they are mandatory ?

If any documentation link, please share 
```
{
    "error": 1000,
    "message": "sources plugins create command error: fail to install plugin: invalid zip file: expectFiles: 2, got filenames:[/kuiper/plugins/sources/sql@1.10.0.so], zipFiles: [sql_test.go sql.json sql.go sql@1.10.0.so], yamlFileChecked:false, soFileChecked:true"
}
```
Thanks

**Comment by ngjaying** [comment]
Which zip file did you use? Is you eKuiper version the same as the plugin (1.10.0 from the error message).

**Comment by abhibhatia98** [comment]
Version -> 1.14.0
UI gives me below link  -> https://packages.emqx.net/kuiper-plugins/1.14.0/alpine/sources/sql_amd64.zip

error on this link is 

```
{
  "error": 1000,
  "message": "sources plugins create command error: fail to download file https://packages.emqx.net/kuiper-plugins/1.14.0/alpine/sources/sql_amd64.zip: cannot download the file with status: 403 Forbidden"
}
```

**Comment by ngjaying** [comment]
Version number now srarts with v. So use v1.14.0
