### ISSUE TITLE
masterv2:kuiper Server not start

### ISSUE THREAD

**Issue by 578223592** [lf-edge/ekuiper#3046]
1.just clone the repository 
2. checkout master-v2
3. make build_with_edgex
4. cd outputdir
5. bin/kuiperd ,but when `bin/kuiper query`, the screen shows:
![image](https://github.com/user-attachments/assets/b7909208-b857-4d35-8efd-cecaab816e1d)
and `netstat` also can't see the port 20498
![image](https://github.com/user-attachments/assets/c476f173-a7b8-4a49-a0c2-5a31273db4a0)

Looks like that the server not start at all.
And I didn't have this problem with version 1.4 before, is there something I didn't notice ?
**Environment**:

- eKuiper version (e.g. `1.3.0`): master-v2
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`):PRETTY_NAME="Ubuntu 22.04.4 LTS"
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
git not trace `go.work.sum`,is the problem caused by it?

**Comment by ngjaying** [comment]
CLI is not restored yet for v2.

**Comment by 578223592** [comment]
> CLI is not restored yet for v2.

@ngjaying 
thansk for reply.
And the REST API is supported now for v2 yet?

**Comment by ngjaying** [comment]
Sure. CLI is restoring soon
