### ISSUE TITLE
schemaless external function in ekuiper

### ISSUE THREAD

**Issue by nbenhur** [lf-edge/ekuiper#3053]
I am running ekuiper with version [lfedge/ekuiper:v1.14.0-alpha.2] as a container in edgex running in docker environment. Ubuntu 22.04.4 LTS. I want to test schemaless external function. I created json file which mentions the function name. I have written REST API function in go language golang file. When i call the http call like "http://localhost:59722/tsschemaless" it is not calling from golang file.

I tested this same golang file in ubuntu shell. When i call the http call like http://localhost:8080/ getting reply from the file.
[tsschemaless.json](https://github.com/user-attachments/files/16363382/tsschemaless.json)
[tsschemaless.txt](https://github.com/user-attachments/files/16363415/tsschemaless.txt)
![Screenshot from 2024-07-24 19-05-59](https://github.com/user-attachments/assets/9cd2a4d3-16bc-411a-96e0-97115ca546b7)
![Screenshot from 2024-07-24 19-06-59](https://github.com/user-attachments/assets/5232ceb4-7fd9-421c-900d-3d572106d0ce)
![Screenshot from 2024-07-24 19-07-38](https://github.com/user-attachments/assets/42ce9b3f-06d6-40ad-ad14-d9f06b885c85)

**Comment by Yisaer** [comment]
@nbenhur Could you describe what's you issue you meet

**Comment by nbenhur** [comment]
I am running ekuiper with version [lfedge/ekuiper:v1.14.0-alpha.2] as a container in edgex running in docker environment. Ubuntu 22.04.4 LTS. I want to test schemaless external function. I am following link https://wiki.lfedge.org/display/EKUIPER/Schemaless+HTTP+Design to create schemaless external function service, stream and rule. I successfully created the service using json file and i can view the service by giving the command "GET http://localhost:59720/services". I successfully created stream in edgex ui.
When i try to create rule using sql command 
{
  "id": "tsschemalessrule-1",
  "sql": "SELECT tsschemaless("POST", "", *) from schemalessStream",
  "actions": [{
    "memory": {
      "topic": "tsschemalessTopic"
    }
  }]
} 
This is the error i am getting for the above rule
error : invalid character 'P' after object key:value pair..

I again edited the sql command as below 
"sql": "SELECT tsschemaless(POST, "", *) from schemalessStream",

This is the error i am getting for the above rule
error : invalid character '"' after object key:value pair..
How to solve this sql error.

I am attaching the json file for schemaless service and screenshot
[tsschemaless.json](https://github.com/user-attachments/files/16400214/tsschemaless.json)
![Screenshot from 2024-07-26 19-33-55](https://github.com/user-attachments/assets/039d18a2-5856-4a92-b1d2-dd8db1a7fe53)
![Screenshot from 2024-07-27 18-14-49](https://github.com/user-attachments/assets/538998c5-1775-4cd2-9c75-7d9d4ea36085)

**Comment by nbenhur** [comment]
{
  "id": "tsschemalessrule-1",
  "sql": "SELECT tsschemaless(post, "/tsschemaless", *) from schemalessStream",
  "actions": [{
    "memory": {
      "topic": "tsschemalessTopic"
    }
  }]
}
 error : invalid character '/' after object key:value pair..

I tried with the other way by following link "https://ekuiper.org/docs/en/latest/extension/external/external_func.html", and here also getting error from sql command.

**Comment by nbenhur** [comment]
I found the solution for the above question. By using single quote it worked as below.

{
  "id": "tsschemalessrule-1",
  "sql": "SELECT tsschemaless(POST,'',*) from schemalessStream",
  "actions": [{
    "memory": {
      "topic": "tsschemalessTopic"
    }
  }]
}

{
  "id": "tsschemalessrules-1",
  "sql": "SELECT tsschemaless(POST,'/tsschemaless',*) from schemalessStream",
  "actions": [{
    "memory": {
      "topic": "tsschemalessTopic"
    }
  }]
}
