### ISSUE TITLE
Ekuiper delete and update external services not working 

### ISSUE THREAD

**Issue by nbenhur** [lf-edge/ekuiper#3070]
I am following the link https://ekuiper.org/docs/en/latest/api/restapi/services.html for registering the external service in edgex ekuiper running in docker environment. I successfully registered external service using command

POST http://localhost:59720/services
Please enter content (application/x-www-form-urlencoded) to be POSTed:
{
  "name":"tsschemaless",
  "file":"http://192.168.29.74/downloads/tsschemaless.zip"
}

Now i wanted to update tsschemaless.zip file. I used below command 

PUT http://localhost:59720/services
{
  "name":"tsschemaless",
  "file":"http://192.168.29.74/downloads/tsschemaless.zip"
}

which gives me below error
PUT: command not found
name:tsschemaless,: command not found
bash: file:http://192.168.29.74/downloads/tsschemaless.zip: No such file or directory

I tried to delete existing service. so i used below command
DELETE http://localhost:9081/services/tsschemaless

I am getting the error "DELETE: command not found"
DELETE http://localhost:9081/services/tsschemaless

Please help to solve these errors of PUT and DELETE. Attached the screen shorts.
![Screenshot from 2024-07-30 18-02-36](https://github.com/user-attachments/assets/ac4cbc7f-2eac-415a-90af-deb248c895c5)
![Screenshot from 2024-07-30 18-03-44](https://github.com/user-attachments/assets/5073e5c5-0cb2-4fed-ba8f-5961efeaf20e)
![Screenshot from 2024-07-30 18-04-41](https://github.com/user-attachments/assets/83f0f8b1-43bb-4965-b6f8-d9403668fd55)

**Comment by nbenhur** [comment]
Hi,
I checked the response after post the service. I attached the response
screenshot.
I am facing trouble with updating the service using PUT request and
deleting the existing service using DELETE. According to the link
https://ekuiper.org/docs/en/latest/api/restapi/services.html. Please help
regarding PUT and DELETE requests.

**Comment by ngjaying** [comment]
@nbenhur You'll need to use a HTTP client like postman to issue those REST API commands.

**Comment by ngjaying** [comment]
Close as no response.
