### ISSUE TITLE
MQTT Source Stream : The connection to mqtt broker is lost due to EOF

### ISSUE THREAD

**Issue by robodevchampion** [lf-edge/ekuiper#3079]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

Hi I have created a MQTT source stream and then rule, rule gives me alarms continuously:

`The connection to mqtt broker is lost due to EOF`

MQTT Config looks like this : 

```
 mqtt_config = {
                "server": "tcp://IP_ADDR:1883",
                "protocolVersion": "3.1.1",
                "clientId": f"test_client_id",
                "qos": 1,
                "insecureSkipVerify": False,
                "topic": f"test_data",
            }
```

Can you please help me what could be the issue ?

Thanks
Abhishek

**Comment by ngjaying** [comment]
Client id may be conflicted. Try not to set the id.

**Comment by abhibhatia98** [comment]
Hi, If I don't set client id it works fine.

But I checked broker, it does not have any client connected.

Seems some issue in ekuiper, as soon as I start the rule a client is connected 

But stopping a rule & Deleting a rule not makes the client disconnected 

<img width="737" alt="image" src="https://github.com/user-attachments/assets/31c40556-653c-4d52-b416-a7bd31a09ace">

Can you please check, what could be the issue ?

Thanks

**Comment by ngjaying** [comment]
That is work as desing. Stream is a logical concept. When creating the rule with that stream, it will use the connection configuration in the stream to do the logical connection.

**Comment by abhibhatia98** [comment]
1. So when does this client got disconnected ? 
2. Also, even if client id is definitely new(No clinet exist with such id) , what could be the cause of `The connection to mqtt broker is lost due to EOF` error ?

**Comment by ngjaying** [comment]
@abhibhatia98 1. When the rule is stopped.  2. Your source and sink are MQTT type, they may use the same client id.

**Comment by abhibhatia98** [comment]
Hi, 

1. Even on stopping the rule client is not getting disconnected. 
2. Source is on MQTT while Sink is completely different. I tried with memory/log file. 

Thanks

**Comment by ngjaying** [comment]
@abhibhatia98 What version are you using? For 1.x, the stream will be disconnected once all referenced rules are stopped. Could you try to set another client id and check.

**Comment by abhibhatia98** [comment]
Hi @ngjaying ,

I tried setting up another client id (completely random) as well, but still giving me same error, If I dont pass then only it works fine otherwise it gives me error?

I am running using latest docker image.

Thanks 
Abhishek

**Comment by ngjaying** [comment]
> Hi @ngjaying ,
> 
> I tried setting up another client id (completely random) as well, but still giving me same error, If I dont pass then only it works fine otherwise it gives me error?
> 
> I am running using latest docker image.
> 
> Thanks

What error? Maybe you can export all your rules and check how many places the client id is referenced.

**Comment by ngjaying** [comment]
Close as no response after a long time. Feel free to reopen if you still have problems.
