### ISSUE TITLE
降频率这个功能好像没有实现，代码里这个字段没有用到定时器去设置。

### ISSUE THREAD

**Issue by lindayou** [lf-edge/ekuiper#3086]
File: [/docs/zh_CN/guide/sources/down_sample.md](https://ekuiper.org/docs/zh/latest/guide/sources/down_sample.html)

这个功能好像没有实现，我设置的interval字段并没有设置到代码里降低采样

**Comment by ngjaying** [comment]
Duplicate of #3087, so close
