### ISSUE TITLE
interval in push option

### ISSUE THREAD

**Issue by lindayou** [lf-edge/ekuiper#3087]
File: [/docs/zh_CN/guide/sources/down_sample.md](https://ekuiper.org/docs/zh/latest/guide/sources/down_sample.html)

Down Sampling doesn't seem to happen，interval， field set the no reaction in push this option，like redisSub Mqtt，This field is not used in the source code to set the timer。

**Comment by ngjaying** [comment]
This is a feature of v2.0.0 which is still under development. What version do you use?
