### ISSUE TITLE
 no sql sink plugin for v.14.x ?

### ISSUE THREAD

**Issue by meal** [lf-edge/ekuiper#3200]
I'm looking to upgrade from 1.13.X to 1.14.X but I can't find related SQL sink plugins. 

`https://packages.emqx.net/kuiper-plugins/1.14.3/debian/sinks/sql_amd64.zip` returns 403 but docs for master-1.14 still says it's valid URL

**Comment by ngjaying** [comment]
@meal Since 1.14.x, we add v prefix to the version name to comply with Go convention. The URL should be `https://packages.emqx.net/kuiper-plugins/v1.14.3/debian/sinks/sql_amd64.zip`
