### ISSUE TITLE
Dynamic reload of external state storage

### ISSUE THREAD

**Issue by younes199511** [lf-edge/ekuiper#3216]
**What would you like to be added/modified**:
I would like to request a new feature for eKuiper that enables dynamic reload of external state storage without the need to restart eKuiper.

**Why is this needed**:
This feature will enhance the flexibility of external state use-cases. In my project, I frequently utilize common static data initialized in an external storage across multiple rules. These data are infrequently updated (usually for maintenance purposes). Having the ability to reload the external state storage on demand via an API would be immensely beneficial. It would allow seamless updates without the necessity to restart eKuiper.

Your consideration of this feature request is highly appreciated.

**Comment by ngjaying** [comment]
@younes199511 Could you please check https://ekuiper.org/docs/en/latest/sqls/functions/other_functions.html#get-keyed-state. Does it fulfill your requirement?

**Comment by younes199511** [comment]
@ngjaying Thank you for your response. 

I'm using this function in my current. However, I've observed that despite updates to the external state storage, the function continues to return previous data until eKuiper is restarted, at which point the new data is reflected. That's why i created the issue to request the addition of an API that allows for the on-demand reloading of the external state storage, if feasible.

Thank you once again

**Comment by ngjaying** [comment]
The functions seems to fetch data each time. It should load the latest data. How did you use it? Could you provide steps to reproduce the problem?

**Comment by younes199511** [comment]
Repoiduction steps with ekuiper 1.12.8 docker image:
- Prepare local sqlite db with static data (example: max = 20)
- Share via docker volume local db with ekuier extState.db: `./extState.db:/kuiper/data/extState.db`
- Start eKuiper container 
- Create a rule with `get_keyed_state("max", "bigint", 0)` to log the result
- Check max is 20
- Update local db (max = 30)
- Check max is still 20
- Restart ekuiper container
- Check max is 30

**Comment by younes199511** [comment]
After farther investigation you're right the function is  fetching data each time (i tried to modify the extState.db direclty inside the container and get_keyed_state returned the new data). 
It seems like when i share the db with the host the updates are not reflected inside ekuiper container for some reason. 

Thank you for your support

**Comment by younes199511** [comment]
Hello @ngjaying 
I have a question about sqlite storage. 
I saw this PR https://github.com/lf-edge/ekuiper/pull/1001 and i'm wondering if the restriction on sqlite path applies for both sqliteKV.db and extState.db. I want to share the extState.db with a docker container that is responsible for setting static data that are used in eKuiper rules but with default path i need to share all the ekuiper Data folder which colatains a lot of files that i don't need/want to share and in order to do that i need to change the location of the extSate.db file. 

Thank you for your support

**Comment by ngjaying** [comment]
Unfortunately, there is no config to change the path now. I don't know if docker has a mechanism to mount files.
