### ISSUE TITLE
The sink is temporarily unavailable but wants to keep the rules running to cache the data when ekuiper restart

### ISSUE THREAD

**Issue by lindayou** [lf-edge/ekuiper#3270]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I encountered a situation. When my device restarted, ekuiper also restarted. However, the emqx in the sink defined by the rule could not be connected temporarily. This is the so-called weak network or no network situation. At this time, the rule is in a stopped state. At this time, the function of caching data without network is no longer possible. How can I solve this problem? That is to say, I want to keep the rules running instead of suspending them when emqx in the sink is temporarily unable to connect after restarting ekuiper. status to collect offline data. Thanks

**Comment by ngjaying** [comment]
Please try the latest v2.x beta version. The rule won't stop when connection fails at the beginning. It will reconnect automatically.

**Comment by lindayou** [comment]
Thank you for your answer。If the reconnection fails, is this rule still running to ensure that unsent data can be cached locally?

**Comment by ngjaying** [comment]
The rule will keep running but the data will be dropped if sink caching is not enabled. Check https://ekuiper.org/docs/en/latest/guide/sinks/overview.html#caching
