### ISSUE TITLE
Security vulnerabilities in the v1.14.4

### ISSUE THREAD

**Issue by OlgasAcc** [lf-edge/ekuiper#3309]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.14.4
- OS (e.g. `cat /etc/os-release`): Ubuntu, linux/amd64

The latest version uses vulnerable version of Go stdlib (1.22.1) and /grpc. Could you please upgrade them to v1.23 and 1.64.1?

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/21a4c54a-2db0-4236-8bb5-57221b9d8fe7">

**Comment by ngjaying** [comment]
Upgrade go to 1.22.8 in 1.14.5. Basically, we won't update the go major version in a fixpack. Also update grpc mod version.

**Comment by OlgasAcc** [comment]
Thanks a lot @ngjaying, the vulns have gone.
