### ISSUE TITLE
I want to use websocket as an input source

### ISSUE THREAD

**Issue by Maingol** [lf-edge/ekuiper#3367]
I want to use websocket as an input source, I have read your documentation, and according to its operation, I can add a websocket type source configuration group through the api, but when I try to edit it, has been prompted by the lack of related plug-ins, but your plug-ins to download the entrance and does not provide a websocket connection, too many related bugs! I'm not sure if you really intend to support websocket input sources, or if I'm not using it in the right way, can you provide me with detailed steps to realize this requirement?

**Comment by Maingol** [comment]
I've tried both 1.13.4 and the latest 2.0

**Comment by Maingol** [comment]
docker
lfedge/ekuiper:1.13.4-slim

**Comment by Maingol** [comment]
介绍太模糊了，具体要怎么做，一个api能搞定吗？一个API能同时指定创建流和websocket地址？怎么指定websocket地址？是不是还要用api增加一个源配置组？能不能在你们自己机器上搭建一个简单的demo，实现出从websocket源读取数据的需求，然后把详细步骤告诉我一下？

**Comment by ngjaying** [comment]
All source configurations are alike. Using confkey to refer to the config in a yaml file for that source kind. Check out mqtt source as an example https://ekuiper.org/docs/en/latest/guide/sources/builtin/mqtt.html#configurations
