### ISSUE TITLE
Issue with Nil Comparison in eKuiper

### ISSUE THREAD

**Issue by younes199511** [lf-edge/ekuiper#3401]
**Environment**:

- eKuiper version : Since 1.13.0 until 1.14.6 (didn't test in 2.0.0) 
- Environment: Alpine Docker Image

**What happened and what you expected to happen**:
I’ve encountered a potential issue in the eKuiper project since the release of version 1.13.0. It appears that comparing data with **nil** is consistently returning false, which seems to be affecting the expected behavior of the application especially filters.  Same behavior is observed in graph rules as well. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a rule with following payload: 

```json
{
    "id": "2",
    "sql": "SELECT * from demo where Temperature != nil",
    "actions": [
        {
            "log": {}
        }
    ]
}
```

You can observe that no log is displayed even if events have non-nil Temperature 

**Anything else we need to know?**:
Was this done intentionally to encourage users to utilize the IS_NULL function instead of direct nil comparisons?

**Comment by ngjaying** [comment]
@younes199511 nil is not a keyword in SQL, thus here it is treated as a column named `nil`.  IS_NULL is the only way to do nil comparison.

**Comment by younes199511** [comment]
@ngjaying Thank you for the answer. I have two remarks:
1- You may want to update some examples in the documentation that use direct comparaison with nil value like in https://ekuiper.org/docs/en/latest/edgex/edgex_rule_engine_command.html#option-1-use-rest-api-1

2- Maybe eKuiper should return a validation (or execution) error when direct comparaison with nil value is used to avoid confusion

Thank you again

**Comment by ngjaying** [comment]
> @ngjaying Thank you for the answer. I have two remarks: 1- You may want to update some examples in the documentation that use direct comparaison with nil value like in https://ekuiper.org/docs/en/latest/edgex/edgex_rule_engine_command.html#option-1-use-rest-api-1
> 
> 2- Maybe eKuiper should return a validation (or execution) error when direct comparaison with nil value is used to avoid confusion
> 
> Thank you again

Thanks for reporting. 1. the doc has updated.  2. nil is not a keyword, in schemaless mode, we do not know if it is a field or not. Syntactically, a != nil is correct, similar to a != b.
