### ISSUE TITLE
Why can't I use the Golang Template

### ISSUE THREAD

**Issue by clh-cod** [lf-edge/ekuiper#587]
Why can't I use the **{{if pipeline}} T1 {{else} T0 {{end}}** syntax in the Golang Template?
the rule status is Running, but there's no output.

**Comment by jinfahua** [comment]
Could you please copy your rule here if it's OK for you?

**Comment by clh-cod** [comment]
thank you, I know what's wrong.
Because the actual average in the map is of type float, and I'm comparing it to an int.

**Comment by clh-cod** [comment]
Hello, I'd like to ask you a question:
How to count the number of changes of data in a time window

I use this action: {{range pipeline}} T1 {{else}} T0 {{end}} 
and **counter** the number of changes of data,but **counter** variable is not incrementing.

Can you help me?

**Comment by jinfahua** [comment]
> Hello, I'd like to ask you a question:
> How to count the number of changes of data in a time window
> 
> I use this action: {{range pipeline}} T1 {{else}} T0 {{end}}
> and **counter** the number of changes of data,but **counter** variable is not incrementing.
> 
> Do you have any good Suggestions? Thanks

Probably you can use the `add` template function provided by Kuiper? You need firstly define a variable, and then use the `add` function. You can refer to [link](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/data_template.md#data-traversal) for how to use the add function.

**Comment by jinfahua** [comment]
Also you could use `countwindow`, and refer to the [doc](https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/windows.md) see if it could help you.

**Comment by clh-cod** [comment]
That's what I did.
sql:
    SELECT collect(zeroPoint) FROM demo1 GROUP BY COUNTWINDOW(5);
dataTemplate:
{{if ne $tmpdate $ele}}
    {{$**counter** := add $counter 1.0}}
{{end}}

but counter variable is not incrementing.

**Comment by jinfahua** [comment]
> {{if ne $tmpdate $ele}}
> {{$**counter** := add $counter 1.0}}
> {{end}}

Not sure if below template could be executed?
```
{{$counter := 0}}
{{if ne $tmpdate $ele}}
{{$counter = add $counter 1.0}}
{{end}}
```

**Comment by clh-cod** [comment]
Yes, this row is not executed.  
{{$counter = add $counter 1.0}}

**Comment by ngjaying** [comment]
It is likely that the ne has problem for incompatible types. Can you make sure the arguments of `ne $tmpdate $ele` is type compatible. Below is a template that I have tried and successful against data like `[{"temperature":33,"humidity":70},{"temperature":22,"humidity":50},{"temperature":11,"humidity":90}]`

```
"dataTemplate": `{{$counter := 0}}{{range $index, $ele := .}}{{if ne 90.0 $ele.humidity}}{{$counter = add $counter 1}}{{end}}{{end}}{"result":{{$counter}}}`
```

**Comment by ngjaying** [comment]
Close this as no reply for a long time. Please reopen it if neede. Thanks.
