### ISSUE TITLE
Use window to filter the last n data

### ISSUE THREAD

**Issue by DaveZLB** [lf-edge/ekuiper#615]
There is a scenario where I need to filter the last n pieces of data in the window every 1 hour.

**Comment by Rui-Gan** [comment]
```
SELECT collect(*)[-n:-1] from demo GROUP BY TUMBLINGWINDOW(hh, 1);
```

**Comment by Rui-Gan** [comment]
> Which version of eKuiper supports this ?

Versions 1.5.0 and above are supported, but we recommend using the latest version.
