### ISSUE TITLE
Install native package Error in ubuntu 18.04

### ISSUE THREAD

**Issue by swing99527** [lf-edge/ekuiper#693]
# sudo dpkg -i kuiper-1.1.1-linux-x86_64.deb 
[sudo] password for swing: 
Selecting previously unselected package kuiper.
(Reading database ... 351347 files and directories currently installed.)
Preparing to unpack kuiper-1.1.1-linux-x86_64.deb ...
Unpacking kuiper (1.1.1) ...
dpkg: dependency problems prevent configuration of kuiper:
 kuiper depends on libc6 (>= 2.28); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.4.

dpkg: error processing package kuiper (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 kuiper
ps: version 0.9.1 is ok

**Comment by zhanghongtong** [comment]
Hi, @swing99527 
Perform the `dpkg -l | grep libc6` view your version of libc6, if its version is too low, upgrade it

**Comment by swing99527** [comment]
> Hi, @swing99527
> Perform the `dpkg -l | grep libc6` view your version of libc6, if its version is too low, upgrade it

Hi Rory-Z，
I believe It will fix this issue with upgrade libc6 version，
But my question can we make it compatible with lower verison libc?  
As I tested before, Version V0.9.1 worked fined with lower libc6 version(2.27-3ubuntu1.4).

**Comment by ngjaying** [comment]
Not fixed in 1.3.1 due to test fails. Move back to the backlog.

**Comment by superrxan** [comment]
please try 1.6.1 when it is released
