### ISSUE TITLE
 version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by Jadeite09** [lf-edge/ekuiper#739]
OS:CentOS 7.2
kernel:3.10.0-514.10.2.el7.x86_64
Package:kuiper-1.1.2-linux-x86_64.zip
```
#  ./bin/kuiperd
./bin/kuiperd: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./bin/kuiperd)
```

**Comment by Seayar** [comment]
You can upgrade your GLIC version, or compile it from source code yourself！

**Comment by Seayar** [comment]
您好，邮件已经收到，我会尽快查看，谢谢！Your Email has been received, I will check as soon as possible,Thank you!

**Comment by superrxan** [comment]
please try 1.6.1 when it is released

**Comment by Seayar** [comment]
您好，邮件已经收到，我会尽快查看，谢谢！Your Email has been received, I will check as soon as possible,Thank you!
