### ISSUE TITLE
strconv.Atoi: parsing \"3.220000e+01\": invalid syntax"

### ISSUE THREAD

**Issue by VijayKumarGopu** [lf-edge/ekuiper#741]
time="2021-03-09 12:33:32" level=warning msg="fail to get value for TemperatureDegC: strconv.Atoi: parsing \"3.220000e+01\": invalid syntax" file="extensions/edgex_source.go:153" rule=led_off

Please let us know which version has the fix.

PS: Device is Raspberry Pi 4.

Thanks
Vijay Kumar

**Comment by VijayKumarGopu** [comment]
More logs :
-------------
time="2021-03-09 13:13:19" level=warning msg="fail to get value for HumidityPercentRH: strconv.Atoi: parsing \"6.200000e+01\": invalid syntax" file="extensions/edgex_source.go:153" rule=led_off
time="2021-03-09 13:13:19" level=warning msg="No readings are processed for the event, so ignore it." file="extensions/edgex_source.go:185" rule=led_off

Tested with Kuiper versions:
------------------------------
1.1.1-2-g9019022
1.1.1-4-g24892eb

Device:
--------
Raspberry Pi 4


Thanks
Vijay Kumar

**Comment by VijayKumarGopu** [comment]
Same issue was raised earlier and marked as Done.

https://github.com/emqx/kuiper/issues/224

**Comment by ngjaying** [comment]
Hi @VijayKumarGopu，
It seems your value descriptor type is int but you send float values. If you need float values, could you change your value decriptor to use float type?

**Comment by VijayKumarGopu** [comment]
Hello @ngjaying,

From Sensor we are receiving INT16 as "rawType" then converting it to FLOAT32 to get the precision values. This is as per https://docs.edgexfoundry.org/1.3/examples/Ch-ExamplesModbusdatatypeconversion/ 

Please let me know if you are referring other value descriptors.


Thanks
Vijay Kumar

**Comment by ngjaying** [comment]
Hello @VijayKumarGopu ,

Kuiper EdgeXSource will refer to [this value descriptors](https://docs.edgexfoundry.org/1.3/walk-through/Ch-WalkthroughData/) to facilitate the type conversion. You type of TemperatureDegC in the value descriptor is likely to be int. Since your real type is FLOAT32, you may need to change it to FLOAT32.

Thanks

**Comment by ngjaying** [comment]
Hello @VijayKumarGopu ,

I am not quite familiar with the RawType. I think that should not affect the type in the value descriptor.  What is your deviceResources definition for *TemperatureDegC*? Is the properties->value->type FLOAT32? Could you try to get the value descriptors by `GET http://localhost:48080/api/v1/valuedescriptor` to check if the type is FLOAT32 for *TemperatureDegC*? Kuiper does not care about the rawtype, we only refer to the type of the value descriptor.

Thanks

**Comment by ngjaying** [comment]
Hello @VijayKumarGopu ,

Your value descriptor type is Int16 which does not match the real data type. and does not match the type of deviceResources. I don't know if it is a defect of edgeX. Could you open an issue for them? 

As a workaround, is it possible to manually modify the type of TemperatureDegC. Example like `curl -X POST -d '{"name":"TemperatureDegC",...,"type":"Float32",...}' localhost:48080/api/v1/valuedescriptor`

**Comment by VijayKumarGopu** [comment]
Hello @ngjaying,

I am doing data conversion from INT16 to FLOAT32 to retain the floating point values received from the Sensor. (Please check other issue which I raised for modbus).

If I remove the rawType from attributes and add value type as INT16, there is no error in Kuiper. ( I have tested this earlier)

But I will lose the precision value of the temperature. I mean when temperature value is 30.3, it will be populated as 30 after applying scale.

Please let me know which component I should open a new issues.

Device resource from working profile:


deviceResources:
      -
        name: "TemperatureDegC"
        description: "Room Temperature in Degrees Celsius."
        attributes:
                { primaryTable: "INPUT_REGISTERS", startingAddress: "2" }
        properties:
            value:
                { type: "Int16", readWrite: "R", scale: "0.1" }
            units:
                { type: "String", readWrite: "R", defaultValue: "degrees celsius"}
      -
        name: "HumidityPercentRH"
        description: "Room Humidity in %RH."
        attributes:
                { primaryTable: "INPUT_REGISTERS", startingAddress: "3" }
        properties:
            value:
                { type: "Int16", readWrite: "R", scale: "0.1" }
            units:
                { type: "String", readWrite: "R", defaultValue: "%RH"}




Thanks
Vijay Kumar

**Comment by VijayKumarGopu** [comment]
Hello @ngjaying,

Should I raise with Core Data component ? Please point to the component where I can raise the issue.


Thanks
Vijay Kumar

**Comment by ngjaying** [comment]
Hi @VijayKumarGopu ,

I am not sure,  Core Services - MetaData should be fine. If not right, EdgeX team should point to the correct component. 
Thanks.

**Comment by ngjaying** [comment]
There is no value descriptor needed for edgex v2 and eKuiper. eKuiper will only support edgex v2 since v1.2.1 thus this problem won't be fixed.
