### ISSUE TITLE
WHERE clause doesn't take effect when using mathematical function

### ISSUE THREAD

**Issue by FelixTing** [lf-edge/ekuiper#751]
WHERE clause doesn't take effect when using mathematical function in SELECT clause.

To re-produce this locally, follow the steps:
1. Setup Kuiper to an MQTT broker and make it run
`docker run -p 9081:9081 -d --name kuiper -e MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883] emqx/kuiper:1.1.2-alpine`
2. Create a stream
`bin/kuiper create stream events '()WITH (FORMAT="JSON", DATASOURCE="devices/+/messages")'`
3. Create a rule
`bin/kuiper query`
`Kuiper > select power(temperature,2) as pw_temp from events where temperature != nil`
4. Publish data to topic devices/device_123/messages of server tcp://broker.emqx.io:1883
`mosquitto_pub -h broker.emqx.io -m '{"humidity" : 20}' -t devices/device_123/messages`
5. An error message should shows up on the `bin/kuiper query` window:
`[{"error":"call func power error: only float64 & int type are supported"}]`

Since the SQL statement has a WHERE clause for filtering, should the Humidity data be ignored?

**Comment by ngjaying** [comment]
Thanks for opeing the issue. The problem happens in the alias which is calculated before the where. We will fix this.
Currently, you can work by removing the alias `select power(temperature,2) from events where temperature != nil`
