### ISSUE TITLE
kuiper manager snap package

### ISSUE THREAD

**Issue by jlikeme** [lf-edge/ekuiper#754]
Would you consider providing kuiper-manager snap package in snap store?

**Comment by jinfahua** [comment]
Are you referring this - https://snapcraft.io/store?

**Comment by gao270615179** [comment]
Yeah, I can't find kuiper-manager, only kuiper in snap store.

**Comment by jinfahua** [comment]
OK... We'll schedule to upload the installation file to the snap store.

**Comment by gao270615179** [comment]
Thanks

**Comment by ngjaying** [comment]
Close this as manager not in the scope of eKuiper project.
