### ISSUE TITLE
Percentage difference between day before avg and current avg

### ISSUE THREAD

**Issue by RBrothersBSI** [lf-edge/ekuiper#814]
As the title says, is this possible to do with Kuiper SQL? I am getting the timestamp in UNIX, if that matters. I am assuming it may be a tumbling window function, but am unsure how to pull it off.

**Comment by ngjaying** [comment]
Yes.

**Comment by ngjaying** [comment]
I think there are two approaches
1. Use a hopping window to contain all the two days' data and use a group by to calculate the avg for each and then compare. The psudo SQL would be like:
```
SELECT (ts - windowStart() > 24 hours) as isToday, AVG(col) as avg FROM device GROUP BY HoppingWindow(dd, 2, 1), isToday ORDER BY isToday
```
By this way, we can get a list of two averages. Then we can use [data template](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/data_template.md) to calculate the percentage and format the output. However, this is not working now as there is still a missing function to get the window start time and to calculate the percentage in data template. We will implement that in the next release.
2. Develop custom function to use in a one day tumbling window. In the function, you'll need to calculate the average of the current window and store the last average in memory or by state API. This will need development of function plugin by yourself.

**Comment by RBrothersBSI** [comment]
Ok, great. Glad to hear that functionality is coming. When creating a plugin that is to be used with a window function, I would not need to set isAggregate() to true, correct?

**Comment by ngjaying** [comment]
> When creating a plugin that is to be used with a window function, I would not need to set isAggregate() to true, correct?

If you need to calculate the aggregation (such as average) of the window tuples, you'll need to set isAggregate() to true.

**Comment by RBrothersBSI** [comment]
Ok, I see. When trying to use my plugin, the server crashes with error "no plugin module data". I am using the Docker compile method and putting my .so into the /usr/local/kuiper/plugins/functions/ directory to register. Any suggestions on what to do? I have tried building the AccumulateWordCount function in the extensions directory as well with the same result.

**Comment by ngjaying** [comment]
I never encounter this problem. After some research, it seems the error is likely from golang itself such as [this issue](https://github.com/golang/go/issues/33072).
I also tried to reproduce the problem but had no luck. I am using ubuntu 20.04.2 to run docker. I tried with kuiper:1.2.0 docker image. Below are my steps:

1. Run the kuiper docker container and build the plugin
```
docker run -p 9081:9081 -d --name kuiper_dev -e MQTT_SOURCE__DEFAULT__SERVERS=[tcp://127.0.0.1:1883] emqx/kuiper:1.2.0
docker exec -it kuiper_dev /bin/bash
### inside kuiper_dev, build the plugin
go build -trimpath --buildmode=plugin -o _build/kuiper-1.2.0-linux-amd64/plugins/functions/AccumulateWordCount.so plugins/functions/accumulateWordCount/accumulateWordCount.go
```
2. Exit and restart the docker container to let kuiper pick up the built plugin
3. Create stream and rule to verify the plugin, it works
```
CREATE STREAM commandStream (cmd string, base64_img string) WITH (DATASOURCE="commands", FORMAT="JSON")
SELECT accumulateWordCount(cmd, \" \") as wc FROM commandStream
```

Did you do anything different to mine?

**Comment by RBrothersBSI** [comment]
So when I build the .so file and place it in the container, I am placing it under /usr/local/kuipers/plugins/functions, is that the right place? I should also mention, I only get that error when I try a POST request containing the rule, which looks like:
{
  "id": "rule1",
  "sql": "SELECT accumulateWordCount(name, \" \") as wc from my_stream",
  "actions": [{
    "log": {}
    }]
}

I am using Debian to run my docker containers.

**Comment by RBrothersBSI** [comment]
The SELECT statement is actually "SELECT accumulateWordCount(name, \" \") as wc from my_stream", the parentheses are escaped.

**Comment by RBrothersBSI** [comment]
The space in the SELECT statement is escaped.

**Comment by ngjaying** [comment]
> So when I build the .so file and place it in the container, I am placing it under /usr/local/kuipers/plugins/functions, is that the right place?

No. In the docker container, the running kuiper binary is in _build/kuiper-1.2.0-linux-amd64. So you should place it under the plugin directory there, to be specific _build/kuiper-1.2.0-linux-amd64/plugins/functions/AccumulateWordCount.so

> I should also mention, I only get that error when I try a POST request containing the rule,

This is expectable. The plugin will only be loaded when a rule use it firstly.

**Comment by RBrothersBSI** [comment]
I see. I placed it in the correct place and am still getting the error when POSTing the rule. I am using go version 1.16.5, do you suspect that may be the issue?

**Comment by RBrothersBSI** [comment]
A little update:
I was able to get a different error and not have the server crash. Here are the steps I took and the error I got:

1. Cloned repo onto local machine
2. mounted ./extensions folder into kuiper-1.2.0 container
3. ran go build -trimpath --buildmode=plugin -o /go/kuiper/_build/kuiper-1.2.0-linux-amd64/plugins/functions/AccumulateWordCount.so functions/accumulateWordCount/accumulateWordCount.go
4. Restarted docker container
5. Posted the rule, same as above
6. Error I am getting is "plugin was built with a different version of package github.com/emqx/kuiper/xstream/api"

Any suggestions?

**Comment by ngjaying** [comment]
> I am using go version 1.16.5, do you suspect that may be the issue?

Yes, that could cause issues. But I don't understand why you have another go version. The docker image emqx/kuiper:1.2.0 should have come with the go environment and kuiper source code. It was intended to replicate the build env where kuiper itself used so that the very strict golang plugin requirement can be met.


> 6\. Error I am getting is "plugin was built with a different version of package github.com/emqx/kuiper/xstream/api"
> 
> Any suggestions?

This does not surprize me. Again, the source code is already inside the docker image emqx/kuiper:1.2.0. No need to clone and moute it which may not be the same version.

**Comment by RBrothersBSI** [comment]
Could you point me in the right direction on where the extensions folder is inside the docker container? I cannot seem to find it in /go/kuiper. I don't have much experience with go plugins so I apologize, seems very touchy.

**Comment by ngjaying** [comment]
> Could you point me in the right direction on where the extensions folder is inside the docker container? I cannot seem to find it in /go/kuiper. I don't have much experience with go plugins so I apologize, seems very touchy. 

It's fine. We all understand the go plugin is touchy.

The folder is in _build/kuiper-1.2.0-linux-amd64/plugins/functions. Could u take a close look at my second reply which is a step by step instruction .
