### ISSUE TITLE
Latest "value" is not displayed, when avg("value") and "value" are selected in the same SELECT statement 

### ISSUE THREAD

**Issue by ahsan9651** [lf-edge/ekuiper#838]
When a "field" and avg("field") are selected in the same SELECT statement using a sliding window, the average value updates at every new value of the "field" but the "field" value is not updated in the final payload.
Here is the SQL I have been running:

`SELECT v, avg(v) as mean_value from test_stream GROUP BY SLIDINGWINDOW(ss, 20);`

Input Payload | Current Output Payload | Expected Output Payload 
------------ | ------------- | -----------------
{"v":30} | {"mean_value":30,"v":30} | {"mean_value":30,"v":30}|
{"v":45} | {"mean_value":37,"v":30} | {"mean_value":37,"v":45}|
{"v":50} | {"mean_value":41,"v":30} | {"mean_value":41,"v":50}|
{"v":60} | {"mean_value":46,"v":30} | {"mean_value":46,"v":60}|

It has been observed that the value of v in the output payload changes only when the duration of the window elapses i.e. after 20 secs in this case. 
A similar behavior has been observed for TUMBLINGWINDOW and HOPPINGWINDOW as well.
There is no such issue when "v" is selected alone in the SELECT statement.

Versions:
kuiper-manager:1.1.1
kuiper:1.2.0-alpine

**Comment by ngjaying** [comment]
@ahsan9651 This is working as design. 
Like the SQL for database, when aggregating with group by, select a field just return the first field in the aggregation.
If you would like to return all the rows in the window together with avg, use collect function. To get the last value, just use the [index expression](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/json_expr.md#index-expression). Example:
```
SELECT collect(v)[-1] as lastv, avg(v) as mean_value from test_stream GROUP BY SLIDINGWINDOW(ss, 20);
```

**Comment by zeeshanshabbir93** [comment]
@ngjaying Most SQL implemetations (e.g. Postgres) force the non-aggregating fields to appear in the group by clause. If this is legal behavior in Kuiper then returning latest value seems natural especially in sliding windows.

**Comment by ngjaying** [comment]
> Most SQL implemetations (e.g. Postgres) force the non-aggregating fields to appear in the group by clause.

Yes. In MySQL the restriction is configurable.  In Kuiper, it is enabled by default

> If this is legal behavior in Kuiper then returning latest value seems natural especially in sliding windows.

MySQL seems to be the only db to allow this behavior so we aligned with it to return the first row.

**Comment by ngjaying** [comment]
Close as work as design. Please reopen if you have further problems.
