### ISSUE TITLE
Input Stream Alias Clash with Output

### ISSUE THREAD

**Issue by zeeshanshabbir93** [lf-edge/ekuiper#839]
Unexpected output is produced if the name of field in the input stream & outstream is same.

Input Stream Definition
![Screenshot from 2021-06-16 19-10-36](https://user-images.githubusercontent.com/62647357/122234860-a4e92c80-ced6-11eb-99bb-13211995bd2e.png)

Query is 
`SELECT id,t,sum (v) as v
FROM tagStream 
GROUP BY SlidingWindow(ss, 30)`

Input Payload | Current Output Payload | Expected Output Payload 
------------ | ------------- | -------------------------------------------------------------|
{"eid":"eid1","id":"tag1","t":1,"v":5}| {"id":"tag1","t":1,"v":5} |{"id":"tag1","t":1,"v":5}
{"eid":"eid1","id":"tag1","t":2,"v":5} | {"id":"tag1","t":1,"v":10}|{"id":"tag1","t":2,"v":10}
{"eid":"eid1","id":"tag1","t":3,"v":5} | {"id":"tag1","t":1,"v":20}|{"id":"tag1","t":3,"v":15}

Notice that the v should be **15 instead of 20** in last row. Changing the alias of sum(v) to e.g. v_new produces correct sum.

However the value of field 't' remains fixed as 1 & only changes after the duration of window has passed. This last problem might be related to [issue-838](https://github.com/lf-edge/ekuiper/issues/838)

**Comment by ngjaying** [comment]
Thanks for opening this issue with the detail. 
I think it is not allowed to alias to the name of another field. All field names + field alias names are supposed to be unique. Maybe we can add some validation during the SQL parsing.

**Comment by zeeshanshabbir93** [comment]
@ngjaying So if the payload format for input & output needs to be same then we should use templates?
What about second issue :
"However the value of field 't' remains fixed as 1 & only changes after the duration of window has passed. This last problem might be related to issue-838"

**Comment by ngjaying** [comment]
@zeeshanshabbir93 yes, data template should be fine.

**Comment by ngjaying** [comment]
After refactoring, it is now allowed to have an alias name to be the same as a field name. The support is planned to be released at 1.3.0
