### ISSUE TITLE
kuiper manager have a plan to open source?

### ISSUE THREAD

**Issue by ccb1900** [lf-edge/ekuiper#846]
also,I can write a ui by myself. kuiper have a api to edit source yaml？I can not find api about conf

**Comment by ngjaying** [comment]
@ccb1900  Thanks for asking. There is no plan yet to open source manager recently.

**Comment by ccb1900** [comment]
> @ccb1900 Thanks for asking. There is no plan yet to open source manager recently.

thanks for your answer.  can I use it for my product free?

**Comment by ngjaying** [comment]
Yes, it is free of charge.

**Comment by ngjaying** [comment]
Close. Please reopen for more questions.

**Comment by ankur-paan** [comment]
We are building an open source eKuiper manager at https://github.com/ankur-paan/ekuiper-manager. See if that helps. Also we are maintaining a live playground where you can interact with your own ekuiper instances using a browser at https://ankur-paan.github.io/ekuiper-manager/
