### ISSUE TITLE
How to use kuiper 's TDengine plugin 

### ISSUE THREAD

**Issue by FengZeHe** [lf-edge/ekuiper#848]
hi, I am a new user of Edgex and Kuiper, and I intend to send Edgex data from Kuiepr to Tdengine data. I've looked through some of the documents, but I still don't understand something. Can you tell me something about the TDengine plugin. Thanks a lot!

I refer to this [document](https://docs.emqx.cn/kuiper/latest/plugins/sinks/tdengine.html#%E7%BC%96%E8%AF%91%E6%8F%92%E4%BB%B6) and run `emx-kuiper/:0.3.2-dev` with Docker. After I entered the container, I created a new go.mod file in `/go/kuiper/plugins` and filled in the configuration.
![go mod](https://user-images.githubusercontent.com/25740210/122725267-63c29500-d2a7-11eb-8442-42449aa748d4.png)
And then i run 
`go mod edit -replace github.com/emqx/kuiper=/$kuiper
go build -trimpath --buildmode=plugin -o /$kuiper/plugins/sinks/Tdengine@v1.0.0.so /$kuiper/plugins/sinks/tdengine/tdengine.go` 
Then I ran into an error
`/go/kuiper # go build -trimpath --buildmode=plugin -o /$kuiper/plugins/sinks/Tdengine@v1.0.0.so /$kuiper/plugins/sinks/td
engine/tdengine.go
can't load package: package /plugins/sinks/tdengine/tdengine.go: cannot find package`

So am I doing something wrong? How do I download the tdengine. go file？

**Comment by ngjaying** [comment]
@FengZeHe Welcome to Kuiper. 
You are using emx-kuiper/:0.3.2-dev in which the tdengine was not supported yet. It was added since v0.9.0 and stablized in v1.0.0. So there is no tdengine.go in your version. 

To use Kuiper shipped plugins, you can install the prebuilt version directly from the management UI [kuiper manager](https://hub.docker.com/r/emqx/kuiper-manager), check [tutorial](https://github.com/emqx/edge-stack/blob/master/developer-scripts/README.md#setup-kuiper). Or install it from REST API or CLI with the prebuilt plugin of your version https://www.emqx.io/downloads/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip. For example, to install 1.0.0 tdengine plugin, `curl -d "{\"name\":\"tdengine\",\"file\":\"https://www.emqx.io/downloads/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip\",\"shellParas\": [\"2.0.3.1\"]}" http://127.0.0.1:9081/plugins/sinks`

**Comment by FengZeHe** [comment]
Thank you for your reply!
I followed the instructions above and found port 9081 was denied access.
`root@u20:~# curl -d "{\"name\":\"tdengine\",\"file\":\"https://www.emqx.io/downloads/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip\",\"shellParas\": [\"2.0.3.1\"]}" http://127.0.0.1:9081/plugins/sinks
curl: (7) Failed to connect to 127.0.0.1 port 9081: Connection refused`

Then I tried to use port 48075 and found the following errors. `curl -d "{\"name\":\"tdengine\",\"file\":\"https://www.emqx.io/downloads/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip\",\"shellParas\": [\"2.0.3.1\"]}" http://127.0.0.1:48075/plugins/sinks
sinks plugins create command error: fail to unzip file https://www.emqx.io/downloads/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip: exit status 127`

May I ask how to solve this situation?

**Comment by ngjaying** [comment]
@FengZeHe The prebuilt tdengine plugin is for debian only. And unfortunately, the plugin is not well supported in alpine. If you need to use plugin, tag with -slim is recommended, e.g. emqx/kuiper:1.0.0-slim

**Comment by FengZeHe** [comment]
> @FengZeHe The prebuilt tdengine plugin is for debian only. And unfortunately, the plugin is not well supported in alpine. If you need to use plugin, tag with -slim is recommended, e.g. emqx/kuiper:1.0.0-slim

@ngjaying Thank you for your reply! I have successfully added the Tdengine plugin,but I haven't sent the data to TDEngine yet.

1. The document said "**the tdengine client version corresponds to the server version one-to-one, which is not compatible with each other, so the user must inform the tdengine server version used.**" I am currently running 2.1.3.0 TDEngine using Docker. How do I know if the client version of the plugin corresponds to the server version?
2. What do these fields mean？ Such as "**provideTs**" , "**tsFileName**"
![image](https://user-images.githubusercontent.com/25740210/123095742-f8bcbe00-d460-11eb-8cd8-b1541891bef6.png)

3. Can Kuiper automatically add the current time to TDengine when sending data ？

Thanks again! Thank you for your generous help.

**Comment by ngjaying** [comment]
@FengZeHe Please check the doc [tdengine](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/sinks/tdengine.md)

**Comment by FengZeHe** [comment]
> @FengZeHe Please check the doc [tdengine](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/sinks/tdengine.md)

@ngjaying Thank you for your reply!
I read the documentation carefully, but I'm still a little confused. I feel very, very close to let it work.
I created Kuiper's streams and rules according to the documentation. And fill in the field according to the document requirements
"**Replace with data key when not filling in**"
![image](https://user-images.githubusercontent.com/25740210/123225714-8f42bb00-d505-11eb-9947-61e9530c1791.png)
![image](https://user-images.githubusercontent.com/25740210/123225770-9cf84080-d505-11eb-8b18-0fa97cedd712.png)
The structure of my TAOS database table is shown in the figure.
![image](https://user-images.githubusercontent.com/25740210/123227479-32e09b00-d507-11eb-8195-d3b316227ee6.png)

send data...
![image](https://user-images.githubusercontent.com/25740210/123228671-37f21a00-d508-11eb-90f9-c7751b13d0a0.png)

Find some error in logs  **"msg="not found field: temperature"**  
![image](https://user-images.githubusercontent.com/25740210/123229757-2cebb980-d509-11eb-830a-be5c402cefe8.png)
![image](https://user-images.githubusercontent.com/25740210/123230224-98358b80-d509-11eb-894d-7e47c743f2cd.png)

Did I do something wrong？

**Comment by ngjaying** [comment]
@FengZeHe The problem is in the source. I think there is no "temperature" reading in your edgeX event. In the log, you only have Int8, Int32 etc.

**Comment by FengZeHe** [comment]
> @FengZeHe The problem is in the source. I think there is no "temperature" reading in your edgeX event. In the log, you only have Int8, Int32 etc.
> 
> By the way, since you define stream with schema, eKuiper will validate your input data and issue an error if the field is missing. You can define the stream as [schemaless](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/streams.md#schema-less-stream) and do a filter in your rule like `SELECT * FROM demo WHERE temperature != null`

@ngjaying  
I found the "**temperature**" in the log according to your method: `SELECT * FROM demo WHERE temperature != null`
![image](https://user-images.githubusercontent.com/25740210/123362322-109c5b00-d5a3-11eb-8f65-bb300ec1e864.png)
Now the log shows `error: taos_connect() fail!"`

Taos runs on local Docker(version 2.0.3.1)  ,and 6041 port has been open.
![image](https://user-images.githubusercontent.com/25740210/123363478-362a6400-d5a5-11eb-856c-c512ba7aec41.png)
![image](https://user-images.githubusercontent.com/25740210/123363388-f8c5d680-d5a4-11eb-8864-741b03b33ecf.png)

**Comment by ngjaying** [comment]
Could you try port `"port": 0,` ?

**Comment by FengZeHe** [comment]
> Could you try port `"port": 0,` ?

Unfortunately, port 0 still doesn't work. I also tried 6031, 6040... But it doesn't work either.
Because taos run in Docker, I've also tried changing the IP to `docker0` or TAOS container IP, but it doesn't work either 
![image](https://user-images.githubusercontent.com/25740210/123384907-89ada980-d5c7-11eb-9052-90468cefb0ed.png)
![image](https://user-images.githubusercontent.com/25740210/123384155-a4cbe980-d5c6-11eb-8d6c-1e1fc125da40.png)

**Comment by FengZeHe** [comment]
finally it works !!!!! Thank you so much

**Comment by lzh123** [comment]
> finally it works !!!!! Thank you so much

how to works, I got this question too,
ekuiper and tdengine work in centos7,  


{
    "id": "202312261743",
    "sql": "SELECT * FROM http_push;",
    "actions": [
        {
            "tdengine": {
                "provideTs": true,
                "tsFieldName": "time",
                "port": 6041,
                "host": "127.0.0.1",
                "user": "root",
                "password": "taosdata",
                "database": "iot_test",
                "table": "iot_1425",
                "fields": [
                    "time",
                    "pm2_5",
                    "hum"
                ]
            }
        }
    ]
}

![image](https://github.com/lf-edge/ekuiper/assets/21017205/ad43e9e7-1232-4cf2-8597-36d1c4d07c2d)
