### ISSUE TITLE
kuiper start error

### ISSUE THREAD

**Issue by tixff** [lf-edge/ekuiper#857]
fatal error: runtime: no plugin module data

**Comment by ngjaying** [comment]
Could you please describe the problem in detail? How can we reproduce the problem. Thanks.

**Comment by tixff** [comment]
I wanted to use an Influx plugin, so I compiled it according to the documentation, following the following operation, and then the startup rule returned an error：

**step1:**
go build -trimpath --buildmode=plugin -o /var/lib/kuiper/plugins/sinks/Influx.so /var/lib/kuiper/plugins/sinks/influx/influx.go 

**step2:**
systemctl restart kuiper

**step3:**
[root@iot-node2 /var/lib/kuiper/plugins/sinks/influx]#kuiper show plugins sink
Connecting to 127.0.0.1:20498... 
influx

**step4:**
[root@iot-node2 /home/bigdata/data/kuiper_rule]#kuiper create rule toinflux_test -f toinfluxtest.json
Connecting to 127.0.0.1:20498... 
Creating a new rule from file toinfluxtest.json.
Rule toinflux_test was created successfully, please use 'bin/kuiper getstatus rule toinflux_test' command to get rule status.

After the fourth step, the kuiper process dies,Restarting Kuiper has the following error:
[root@iot-node2 /home/bigdata/data/kuiper_rule]#kuiperd 
Serving kuiper (version - 1.2.0-1) on port 20498, and restful api on http://0.0.0.0:9081. 
fatal error: runtime: no plugin module data

**Comment by ngjaying** [comment]
Plugin was not verified in RPM, we recommend to use docker image for plugins and refer to [plugin tutorial](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md) for detail.

Also, for shipped plugins like influx, we have prebuilt version in [pugin repo](https://www.emqx.io/downloads/kuiper-plugins/1.2.0/debian/sinks). Just find out the right version and install by REST API or CLI like:

```
curl -X POST --location "http://127.0.0.1:9081/plugins/sinks" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"influx\", \"file\": \"https://www.emqx.io/downloads/kuiper-plugins/1.2.0/debian/sinks/influx_amd64.zip\"}"
```
