### ISSUE TITLE
Create rule with inexisted sink may cause error when restarting eKuiper

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#858]

**Comment by rwadowski** [comment]
@ngjaying hi is there particular way to reproduce it ? I am trying to reproduce it using files attached, with no mqtt broker.
1. I start it with clear database
2. I am uploading data
3. Restart the service and I assume it should crash / produce error log or sth ?
As for now with no result
[stream_and_rule.zip](https://github.com/lf-edge/ekuiper/files/6945991/stream_and_rule.zip)

**Comment by ngjaying** [comment]
I tried with the master branch, I also can't reproduce it now. I'll just close this for now. Thanks.
