### ISSUE TITLE
Memory Leak when use QoS 1 or 2

### ISSUE THREAD

**Issue by salmanazmat666** [lf-edge/ekuiper#875]
Hi,
There seems to be a memory leak which occurs when we use QoS greater than 0.
Following is our test case.
**Kuiper Version**: 1.2.0
**Number of streams**: 250 (1 per rule)
**Number of Rules**: 250
**Rule Sample**:
```
{
	"id": "rule1",
	"sql": "SELECT meta(t1->name), collect(meta(t1->origin))[-1]/1000.0, sum(t1) from stream1 GROUP BY SlidingWindow(ss, 30)",
	"actions": [{
		"mqtt": {
			"server": "tcp://127.0.0.1:1883",
			"topic": "cep_topic_1",
			"sendSingle": true,
			"dataTemplate": "[{\"origin\": {{.kuiper_field_0}}, \"message\": {{.meta}}, \"st1\": {{.sum}}}]"
		}
	}],
	"options": {
		"isEventTime": false,
		"lateTolerance": 1000,
		"concurrency": 1,
		"bufferLength": 1024,
		"sendMetaToSink": false,
		"sendError": true,
		"qos": 1,
		"checkpointInterval": 5000
	}
}
```
**Run time**: 3 hours
**Throughput**: 1 value per second per rule

**CPU Usage**: in %
![35e23b93-5a2b-4040-b4b6-078c0a13a666](https://user-images.githubusercontent.com/10860229/124281257-f9d9a380-db62-11eb-991e-95f80b3e3eeb.png)

**Memory Usage**: in MBs
![dd399f06-c312-44a7-baf6-faffc93fa38a](https://user-images.githubusercontent.com/10860229/124281379-183f9f00-db63-11eb-8425-48ec64baf535.png)

**Comment by ngjaying** [comment]
Thanks @salmanazmat666, I can recreate the problem. It seems a problem of state cleanup. We'll continue looking into this.
