### ISSUE TITLE
Issues while handling queries involving filtering values of functions for functions involving context.state

### ISSUE THREAD

**Issue by ahsan9651** [lf-edge/ekuiper#883]
I am trying to execute a select query that involves return value of a function and a tag value, the return value from the function needs to be filtered against a threshold using HAVING clause. 
Here is the SQL I have written:

`SELECT stateChangeCty(temperature), collect(temperature) 
FROM demo7 GROUP BY id 
HAVING stateChangeCty(temperature) = "Normal Operation"; `

The function stateChangeCty compares the values of input against threshold and assigns value to context.state which is later used in the next run of the rule to detect if the state has changed or not.
Once the value from the function is returned, it is compared against "Normal Operation" string and value is returned only if the output of function is "Normal Operation".
However, since we are calling a function twice in the same query, once for selecting and once for filtering, the results of the query are not as expected. 

Input Payload | Output Payload | Expected Payload
------------ | ------------- | ------------------------
{"temperature": 48, "id":"tag2"} | {"collect":[48],"stateChangeCty":"Normal Operation"} | {"collect":[48],"stateChangeCty":"Normal Operation"}
{"temperature": 48, "id":"tag2"} |            -          |        -    
{"temperature": 56, "id":"tag2"} |     -                 |            -      
{"temperature": 43, "id":"tag2"} |    {"collect":[43]}   |   {"collect":[43],"stateChangeCty":"Normal Operation"}

So, from above behaviour I have concluded that if there is a difference in the number of times an instances of function gets executed following HAVING clause and following Select clause, the values of state.caontext for both instances get mismatched and the output is no longer predictable. 
Since, Kuiper is based on MySQL, and Mysql does allow using aliases in the HAVING clause: 
[Stackoverflow Link](https://stackoverflow.com/questions/24127932/mysql-query-clause-execution-order
)
so Is there a way that we can assign an alias to the function return in SELECT and use that Alias after the HAVING clause? That way we can avoid execution of two different instances of the same function hence no mismatch in the states. 
Something like this:
`SELECT stateChangeCty(temperature) as statevar, collect(temperature) 
FROM demo7 GROUP BY id 
HAVING statevar = "Normal Operation"; `

Below is the function  stateChangeCty for your reference:

###  **Code: stateChangeCty**

```golang
package main

import (
	"fmt"
	//"github.com/emqx/kuiper/xsql"
	"github.com/emqx/kuiper/xstream/api"
	//"strings"
)

type stateChangeCty struct {
}

func (f *stateChangeCty) Validate(args []interface{}) error {
	if len(args) != 1 {
		return fmt.Errorf("stateChange function only supports 1 parameter but got %d", len(args))
	}
	return nil
}
func (f *stateChangeCty) Exec(args []interface{}, ctx api.FunctionContext) (interface{}, bool) {

	m1 := args[0]

	//fmt.Printf("%T\n",m1)

	m2 := m1.([]interface{})

	//fmt.Printf("type is %v\n",m2)

	new_bound := []float64{}

	for _, v := range m2 {
		new_bound = append(new_bound, v.(float64))
	}

	var currstate interface{}

	if new_bound[0] >= 50 && new_bound[0] < 100 {
		currstate = "Medium Level Alarm"
	}
	if new_bound[0] >= 100 {
		currstate = "High Level Alarm"
	}
	if new_bound[0] < 50 {
		currstate = "Normal Operation"
	}

	fmt.Printf("current state at start: %v\n", currstate)
	prevstate, _ := ctx.GetState("currstated")
	fmt.Printf("prevstate: %v\n", prevstate)

	if prevstate == nil {
		ctx.PutState("currstated", currstate)
		fmt.Printf("entry point %v\n", currstate)
		return currstate, true
	}

	if prevstate.(string) != currstate.(string) {
		ctx.PutState("currstated", currstate)
		fmt.Printf("routine %v\n", currstate)
		return currstate, true
	}

	fmt.Printf("end of function state same %v\n", currstate)
	return nil, true

}
func (f *stateChangeCty) IsAggregate() bool {
	return true
}

var StateChangeCty stateChangeCty


```

**Comment by ngjaying** [comment]
Thanks for bringing this up. I agree this is a problem and alias may be a good solution. Which version do you use? I think alias in having should be supported in the master stream now.

**Comment by ahsan9651** [comment]
I am using kuiper 1.2.0

**Comment by ahsan9651** [comment]
> Thanks for bringing this up. I agree this is a problem and alias may be a good solution. Which version do you use? I think alias in having should be supported in the master stream now.

The version 1.2.1 allows assigning alias to default/builtin aggregate functions, and passing them on into HAVING clause. But when I try to write the rule for our function(by copying the .so file in the plugins/functions folder within the build): I get following error:

> Connecting to 127.0.0.1:20498... 
Creating a new rule from file rulectynew.txt.
Create rule error : Parse SQL SELECT stateChangeCty(temperature) as state, collect(temperature) FROM demo7 GROUP BY id HAVING state ="Normal Operation" error: error getting function stateChangeCty: exported symbol &{} is not type of api.Function or function that return api.Function..


I also tried compiling the function for kuiper 1.2.1 from scratch using Golang but get following messages while compiling the function using golang:

**Command**: go build -trimpath --buildmode=plugin -o /home/in01-nbk-757/Desktop/kuiper/kuiper1.2.1/ekuiper/_build/kuiper-1.2.1-26-gf77f314-linux-amd64/plugins/functions/stateChangeCty.so extensions/functions/stateChangeCty/stateChangeCty.go

**Message:**
> extensions/functions/stateChangeCty/stateChangeCty.go:6:2: no required module provides package github.com/emqx/kuiper/xstream/api; to add it:
	go get github.com/emqx/kuiper/xstream/api

**Command:**
go get github.com/emqx/kuiper/xstream/api

**Message:**
> go get: module github.com/emqx/kuiper@upgrade found (v0.0.0-20210709025030-aaee4abb0f9c), but does not contain package github.com/emqx/kuiper/xstream/api

Version of Go Installed: go1.16.5 linux/amd64

**Comment by ngjaying** [comment]
- I don't think the support of alias is different between 1.2.0 and 1.2.1. So using 1.2.1 may not have any differences. However, we do have refactored alias support in the master stream. You can compile the latest code by https://github.com/lf-edge/ekuiper#compile
- Plugin must be rebuilt across versions due to the restriction of the golang plugin system. Make sure to run the build in the root path of eKuiper project. Move your plugin code into eKuiper project would be eaiser. If you want to keep your plugin in a seperate project, check [plugin tutorial](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md).

**Comment by ahsan9651** [comment]
Using Having with alias solves the issue of sate getting disturbed.

**Comment by ngjaying** [comment]
Thanks your for confirming!
