### ISSUE TITLE
memory usage is keeping increasing for continuous frequent REST API call

### ISSUE THREAD

**Issue by mygithubcjm** [lf-edge/ekuiper#888]
### 使用kuiper时，内存占用一直在增加
以下是测试用例：

**kuiper 版本**：1.2.1 （经测试版本1.1.2也同样存在这个问题）

**kuiper对应docker版本**：1.2.1-alpine

**linux版本**：
![image](https://user-images.githubusercontent.com/38320453/125252741-496e5b00-e32b-11eb-9260-5b039705c481.png)

**流**：1个
`{
  "Name": "rtspDevice0701",
  "StreamFields": null,
  "Options": {
    "DATASOURCE": "$tw/rule/device/rtspDevice0701/up",
    "KEY": "id",
    "FORMAT": "json",
    "CONF_KEY": "",
    "TYPE": "",
    "STRICT_VALIDATION": false,
    "TIMESTAMP": "",
    "TIMESTAMP_FORMAT": "",
    "RETAIN_SIZE": 0
  },
  "StreamType": 0
}`

**规则**：3个
`{
  "triggered": true,
  "id": "48df7ef117114ef9ab0b734483cc355d",
  "sql": "select * from rtspDevice0701 where rtspDevice0701.d->class = 2",
  "actions": [
    {
      "log": {}
    },
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "$tw/rule/48df7ef117114ef9ab0b734483cc355d/execute"
      }
    }
  ],
  "options": {
    "isEventTime": false,
    "lateTolerance": 1000,
    "concurrency": 1,
    "bufferLength": 1024,
    "sendMetaToSink": false,
    "sendError": true,
    "qos": 0,
    "checkpointInterval": 300000
  }
}`

`{
  "triggered": true,
  "id": "6068fa3b2dd849dfba7315584d32a365",
  "sql": "select * from rtspDevice0701 where rtspDevice0701.d->score > 0.5 and rtspDevice0701.d->class = 1",
  "actions": [
    {
      "log": {}
    },
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "$tw/rule/6068fa3b2dd849dfba7315584d32a365/execute"
      }
    }
  ],
  "options": {
    "isEventTime": false,
    "lateTolerance": 1000,
    "concurrency": 1,
    "bufferLength": 1024,
    "sendMetaToSink": false,
    "sendError": true,
    "qos": 0,
    "checkpointInterval": 300000
  }
}`

`{
  "triggered": true,
  "id": "79e631e091684c648f0cd7c4eea2437d",
  "sql": "select * from rtspDevice0701 where rtspDevice0701.d->score > 0.5 and rtspDevice0701.d->class = 0",
  "actions": [
    {
      "log": {}
    },
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "$tw/rule/79e631e091684c648f0cd7c4eea2437d/execute"
      }
    }
  ],
  "options": {
    "isEventTime": false,
    "lateTolerance": 1000,
    "concurrency": 1,
    "bufferLength": 1024,
    "sendMetaToSink": false,
    "sendError": true,
    "qos": 0,
    "checkpointInterval": 300000
  }
}`

**吞吐量**：流每20秒 1 条数据

**内存占用情况**：

> 运行5分钟左右的时候，内存占用为120MB：
![test1](https://user-images.githubusercontent.com/38320453/125253833-69eae500-e32c-11eb-9b67-d4a7f6f25cf1.png)

> 运行30分钟左右的时候，内存占用为534MB:
![test2](https://user-images.githubusercontent.com/38320453/125254535-22188d80-e32d-11eb-8bae-d1cfde225261.png)

> 运行一个小时左右的时候，内存占用为1.04GB:
![test3](https://user-images.githubusercontent.com/38320453/125259281-bf75c080-e331-11eb-8237-7d320abdd7d6.png)

**Comment by ngjaying** [comment]
@mygithubcjm What's your data look like? Could you please provide a sample. Also could you please go into the container and run `top` to see the memory usage inside the container?

**Comment by mygithubcjm** [comment]
> @mygithubcjm你的数据是什么样的？你能提供一个样品吗？还请您进入容器并运行`top`以查看容器内的内存使用情况？

数据样本：
{"gp":"rtsp","g":"A","id":"rtspDevice0701","t":1625451757033,"v":"2","d":{"ct":1625451757080,"imagePath":"/home/cameraRecord/2021/7/5/1625451757006.jpg","class":1,"rect":[234.0,55.0,970.0,520.0],"score":0.97}}
容器内运行top：
![test4](https://user-images.githubusercontent.com/38320453/125269146-04522500-e33b-11eb-956d-abe7ad2794de.png)

**Comment by ngjaying** [comment]
I try with similar rules and send the data through mqtt every 20 seconds, the memory keeps in 34MB.
I try sending data every 20 **milliseconds**, the memory is growing a little bit to 43MB or so after 15 minutes and it is not growing linear (maybe because of GC). Anyway, the magnitude of my experiment is very different from yours. Did you do anything special to you eKuiper container? Did you find any errors for the rules? Try get status of your rules and see the metrics.

**Comment by mygithubcjm** [comment]
> 我尝试使用类似的规则，每 20 秒通过 mqtt 发送数据，内存保持在 34MB。
> 我尝试每 20**毫秒**发送一次数据，15 分钟后内存增长到 43MB 左右，并且不是线性增长（可能是因为 GC）。无论如何，我的实验规模与您的非常不同。你对你的 eKuiper 容器做了什么特别的事情吗？您是否发现规则有任何错误？尝试获取规则的状态并查看指标。

1、我并没有对kuiper容器做什么特殊操作，
使用 `docker pull emqx/kuiper:1.2.1-alpine `获取的docker镜像
使用 `docker run -p 9081:9081 -d --net=host --privileged=true   --name kuiper -e MQTT_SOURCE__DEFAULT__SERVERS=[tcp://127.0.0.1:1883]  emqx/kuiper:1.2.1-alpine`  启动的容器
2、规则和流是通过http接口请求的方式创建的  
3、还有一点  我的程序中有一个定时任务10秒中触发一次会调用http接口获取规则的状态 
4、还有我发现kuiper的容器日志中有很多`Show rules error: sql: database is closed` 这样子的错误
如图所示：
![test6](https://user-images.githubusercontent.com/38320453/125285074-d4138200-e34c-11eb-87b6-374051fd10da.png)
5、最后，我的kuiper目前运行了4.5个小时了，内存已经占用了4GB多了
![test5](https://user-images.githubusercontent.com/38320453/125285403-310f3800-e34d-11eb-8c1a-9242ac9bbe2c.png)

**Comment by ngjaying** [comment]
It seems there are errors in your log and why did you get more then 10 "Show rules error: sql: database is closed"? Did you run http check more then 10 times a second? I think you can stop the testing now. Try to figure out the errors before running again.

What's the result of `GET http://{{host}}/rules/ruleId/status`?

Also could you please paste your `etc/kuiper.yaml`

**Comment by mygithubcjm** [comment]
> It seems there are errors in your log and why did you get more then 10 "Show rules error: sql: database is closed"? Did you run http check more then 10 times a second? I think you can stop the testing now. Try to figure out the errors before running again.
> 
> What's the result of `GET http://{{host}}/rules/ruleId/status`?
> 
> Also could you please paste your `etc/kuiper.yaml`


- 问题似乎找到了，应该是定时任务的问题，我将定时任务停了再重新运行测试，kuiper的内存占用就并不像之前那样增长很快了。

定时任务停了之后运行kuiper10分钟，内存占用35.57MB：
![test7](https://user-images.githubusercontent.com/38320453/125374180-11155e00-e3b9-11eb-8de2-4cc3e6a78d60.png)

定时任务停了之后运行kuiper30分钟，内存占用35.59MB：
![test8](https://user-images.githubusercontent.com/38320453/125374347-69e4f680-e3b9-11eb-9c24-7018dd37a72a.png)

定时任务停了之后运行kuiper50分钟，内存占用35.93MB：
![test13](https://user-images.githubusercontent.com/38320453/125376136-f80eac00-e3bc-11eb-907e-2028890f988c.png)






- 定时任务总共是有三个，都是10秒触发一次，分别为

1、 `GET http://{{host}}/rules `
     调用这个接口来获取kuiper中的规则状态信息，与程序中缓存的规则状态信息进行对比，如果发现kuiper中的规则状态与程序中缓存的规则状态信息不一致，那么就会调用 “POST http://{{host}}/rules/{{id}}/stop” 停止规则  或者调用`POST http://{{host}}/rules/{{id}}/start`  启动规则

2、 `GET http://{{host}}/streams`  
     调用这个接口来获取kuiper中的流信息，如果发现程序缓存中的规则没有用到某个流了，那么就会调用`DELETE http://{{host}}/streams/{{id}}` 来删除kuiper中的流

3、`GET http://{{host}}/rules`
     这个定时任务是收集kuiper中的规则信息，将规则信息发送到EMQ中






-  `GET http://{{host}}/rules/ruleId/status` 的结果分别是：

![test9](https://user-images.githubusercontent.com/38320453/125375805-466f7b00-e3bc-11eb-9a5a-7f8eabb42773.png)
![test10](https://user-images.githubusercontent.com/38320453/125375819-4d968900-e3bc-11eb-8b17-21dcb5fc9de3.png)
![test11](https://user-images.githubusercontent.com/38320453/125375831-52f3d380-e3bc-11eb-8132-c87310ec39ea.png)




- `etc/kuiper.yaml`  信息如下：

![test12](https://user-images.githubusercontent.com/38320453/125375981-9a7a5f80-e3bc-11eb-8078-a24942725d0b.png)

**Comment by ngjaying** [comment]
Thanks for cofirmation. Now you observe the same as mine. I also agree the problem may be in the REST API as it was not designed to be called so frequently especially to delete/update which may cause file db crash thus memory may be a side effect. A workaourd is to add some sleep between each REST API call to avoid too frequent call. We will investigate this together with other REST API performance issue.

**Comment by mygithubcjm** [comment]
> Thanks for cofirmation. Now you observe the same as mine. I also agree the problem may be in the REST API as it was not designed to be called so frequently especially to delete/update which may cause file db crash thus memory may be a side effect. A workaourd is to add some sleep between each REST API call to avoid too frequent call. We will investigate this together with other REST API performance issue.
感谢您的回答和帮助，现在我已经将定时任务做了修改调整，已经没有出现内存持续升高的问题了。
