### ISSUE TITLE
kuiper1.2.1-slim startup failure in EdgeX 2.0

### ISSUE THREAD

**Issue by FengZeHe** [lf-edge/ekuiper#909]
Hi , I used the image EMqx/Kuiper :`1.2.1-slim` and `1.2.1` versions on EdgeX and found the boot failed. It starts normally with the alpine version.
![error](https://user-images.githubusercontent.com/25740210/127272275-ce4294c0-edff-4933-868d-21e1e2b94211.png)
![error2](https://user-images.githubusercontent.com/25740210/127272284-73e469e0-566a-499b-b1f9-f3a763d3a165.png)

here is the docker compose file
![image](https://user-images.githubusercontent.com/25740210/127272875-3b52b077-1005-4c17-b869-df7e7f80336e.png)

**Comment by ngjaying** [comment]
@FengZeHe Because the plugin installation needs root,  we only add `kuiper` user to alpine. To use slim, please remove the line `user: kuiper:kuiper` in your docker compose file. By the way, the `1.2.1` is not recommended to use in production. It is only provided for plugin development.

**Comment by FengZeHe** [comment]
Thank you for your reply and reminder.

**Comment by FengZeHe** [comment]
@ngjaying By the way ,Kuiper 's TDengine plugin download address is invalid. 
https://www.emqx.io/downloads/kuiper-plugins/1.2.1/debian/sinks/tdengine_amd64.zip

**Comment by ngjaying** [comment]
The location is changed to: https://packages.emqx.io/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip
or https://packages.emqx.net/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip. And TDEngine client download location is also changed. You'll need to manually upate the url in the line 25 of install.sh inside the zip:
```shell
url="https://www.taosdata.com/assets-download/TDengine-client-$1-Linux-x64.tar.gz"
if [ "$(uname -m)" = "aarch64" ]; then \
	url="https://www.taosdata.com/assets-download/TDengine-client-$1-Linux-aarch64.tar.gz"
fi
```

**Comment by FengZeHe** [comment]
> The location is changed to: https://packages.emqx.io/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip
> or https://packages.emqx.net/kuiper-plugins/1.0.0/debian/sinks/tdengine_amd64.zip. And TDEngine client download location is also changed. You'll need to manually upate the url in the line 25 of install.sh inside the zip:
> 
> ```shell
> url="https://www.taosdata.com/assets-download/TDengine-client-$1-Linux-x64.tar.gz"
> if [ "$(uname -m)" = "aarch64" ]; then \
> 	url="https://www.taosdata.com/assets-download/TDengine-client-$1-Linux-aarch64.tar.gz"
> fi
> ```

@ngjaying Thanks for your help, I have successfully installed the plugin. Your responses are patient,accurate and professional!
