### ISSUE TITLE
Not allowed to add more nodes in the management control platform

### ISSUE THREAD

**Issue by wangzh1024** [lf-edge/ekuiper#918]
After I add three nodes to the management control platform, I can't add more nodes. I need a license file. How can I solve it?

 ![image](https://user-images.githubusercontent.com/38374640/128108506-e294ede2-6287-4208-8519-00c984ebefe4.png)

**Comment by ngjaying** [comment]
@wangzh1024 It supports at most 3 nodes. If you need more than 3 nodes, you'll need to delete some nodes and keep less than 3 nodes in your node list. We will remove this restriction in the next release.

**Comment by wangzh1024** [comment]
OK, thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lf-edge/ekuiper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lf-edge/ekuiper] Not allowed to add more nodes in the management control platform (#918)





 
@wangzh1024 It supports at most 3 nodes. If you need more than 3 nodes, you'll need to delete some nodes and keep less than 3 nodes in your node list. We will remove this restriction in the next release.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
