### ISSUE TITLE
Proposal: Redis as KV storage

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#926]
Currently, eKuiper need to persist meta data like stream def, rule def, plugin def etc; meanwhile, it also persist states of rules with checkpoint mechanism. The current and only storage implementation is Sqlite which can be embeded, portable and need NO extra configuration. However, the database model of sqlite is not key/value and it is not scalable. In some scenario, users may want to use redis or other storage implementation to store the data. For example, when working with EdgeX, eKuiper may leverage the same redis instance bundled with EdgeX.

This proposal will include:
1. Refactor the KV storage to be extensible and switchable for various storage implementation. And provide the conf parameter to switch implementation.
2. Develop the support for redis as the storage. 
3. Investigate the integration with redis in EdgeX.

**Comment by ngjaying** [comment]
@rwadowski my thoughts about redis support that you might be interested. Appreciate your comments.

**Comment by rwadowski** [comment]
@ngjaying sure, I can contribute something here for sure. 1 and 2 are clear to me. I have two qestions
* regarding 3rd - I will have to read a little bit how EdgeX works with redis [here](https://docs.edgexfoundry.org/2.0/microservices/core/database/Ch-Redis/) - is there any other description how edgex interacts with redis ?
* I noticed that configs are not using environment variables, I think it would be nice to introduce them. I come from scala world where HOCON config files works with them very well, shouldn't we think about such options. You have default config and any env veriable for config that is set takes priority ?

**Comment by ngjaying** [comment]
> * regarding 3rd - I will have to read a little bit how EdgeX works with redis [here](https://docs.edgexfoundry.org/2.0/microservices/core/database/Ch-Redis/) - is there any other description how edgex interacts with redis ?

EdgeX provides a set of [docker compose files](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml) as describe in [EdgeX getting started](https://docs.edgexfoundry.org/2.0/getting-started/quick-start/). There is a redis instance in the docker compose as well as eKuiper. Here I am just thinking if we could leverage that instance instead of letting user setup another redis instance. It my just a docker compose set up problem.

> * I noticed that configs are not using environment variables, I think it would be nice to introduce them. I come from scala world where HOCON config files works with them very well, shouldn't we think about such options. You would have default config and any env veriable for config that is set takes priority ?

Some configs are supported using env variable in docker by deploy/docker/conf_util.go. This sounds interesting. We need to dig if there is similar implementation in go and the pros and cons compared to hand written conf_util. You can create an issue or proposal notes in Project proposals: https://github.com/lf-edge/ekuiper/projects/17

**Comment by rwadowski** [comment]
@ngjaying created [here](https://github.com/lf-edge/ekuiper/issues/927) - I am not golang expert but it seems convenient improvement.

**Comment by rwadowski** [comment]
> EdgeX provides a set of docker compose files as describe in EdgeX getting started. There is a redis instance in the docker compose as well as eKuiper. Here I am just thinking if we could leverage that instance instead of letting user setup another redis instance. It my just a docker compose set up problem.

You mean make ekuiper compatible with the docker compose - in other words - if someone will use these images eKuiper will be able to work with this redis ? Am I correct ?

**Comment by ngjaying** [comment]
> You mean make ekuiper compatible with the docker compose - in other words - if someone will use these images eKuiper will be able to work with this redis ? Am I correct ?

Yes, that's what I mean.

**Comment by rwadowski** [comment]
@ngjaying I assume that this improvement applies to topo.go code as well ?

**Comment by ngjaying** [comment]
@rwadowski Yeah, I think so. The kv used there is apend only and need to delete history from time to time. I don't know yet how to model it in redis.

**Comment by rwadowski** [comment]
@ngjaying hi, what is purpose of the tskv.db ? It operates on timestamps and values associated with them ? I want to understand the problem solved by this part of code since I don't want to model sql in redis.

**Comment by ngjaying** [comment]
@rwadowski It is used to save the snapshot of the states of a rule. Each snapshot is labeled with timestamp. Currently in SQLite, each rule that enabled checkpoint(qos > 1) will have a table named with ruleId. And each snapshot of the rule will be saved to that table with timestamp as the key and content as the value. The structure will be like:

```
Table: rule1
    key: 1541152486600  value: {serialized snapthot}
    key: 1541152488600  value: {serialized snapthot}
    more keys....
Table: rule2
    key: 1541152486600  value: {serialized snapthot}
    key: 1541152488600  value: {serialized snapthot}
    more keys....
More rule tables...
```

Each snapshot will be saved for some time and then expired. When restoring, we need to get the latest timestamp(key). We seldom do random read or random write (mostly just append). So we add an API last() to get the last snapshot and deleteBefore() to easily clean up all expired snapshot.

**Comment by rwadowski** [comment]
@ngjaying ok so I think the easiest way to model snapshots in redis is to use lists - head of the list is the newest snapshot, tail has older ones. So instead of table we would have key to list of snapshots ?

**Comment by ngjaying** [comment]
> So instead of table we would have key to list of snapshots ?

This sounds good! Is it possible to delete part of the list items? If it is, that's the perfect model.

**Comment by rwadowski** [comment]
it seems that list has a [trim](https://redis.io/commands#list) command which I think will allow to remove tail for example

**Comment by rwadowski** [comment]
@ngjaying initial implementation is [here](https://github.com/lf-edge/ekuiper/pull/950)

**Comment by tonyespy** [comment]
Just a note that the EdgeX redis instance is secured by default. For the Ireland release of EdgeX, security-secretstore-setup has been modified to update the EdgeX source configuration by adding the required redis username and password to the `/etc/source/edgex.yaml`. There's been some discussion about extending this to cover the EdgeX sink as well. If Kuiper additionally were to use redis as its database, then we might also need to update an additional file (/etc/kuiper.yaml?).

Maybe it's worth adding Vault support instead of modifying multiple configuration files?

@lenny-intel ^^
