### ISSUE TITLE
dash not accepted in meta function 

### ISSUE THREAD

**Issue by raycola** [lf-edge/ekuiper#934]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.2.0 or last?
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Others: EdgeX Foundry/docker

**What happened and what you expected to happen**:
A validation error occurs when there are dash character '-' into property name and it used in meta function:

- Create rule error: Parse SQL' ...error: Expect meta reference type for 1 parameter of function meta.. 

**How to reproduce it (as minimally and precisely as possible)**:
Rule body:
```
{
   "options":{
      "sendError":false
   },
   "id":"myRule",
   "actions":[
      {
         "log":{}
      }
   ],
   "sql":"SELECT (max(SITE1-L0B_MULTIMETRO_1__PHASE_1_V) - min(SITE1-L0B_MULTIMETRO_1__PHASE_1_V))  as PROPERTYTARGET_VALUE, \"PHASE_1_V\" as PROPERTYTARGET_NAME, collect(*)[1]->SITE1-L0B_MULTIMETRO_1__PHASE_1_V as PROPERTYSOURCE_VALUE, SITE1-L0B_MULTIMETRO_1__PHASE_1_V as PROPERTYSOURCE_NAME, meta(id) AS eid, meta(Origin) AS eorigin, meta(device) AS device, meta(SITE1-L0B_MULTIMETRO_1__PHASE_1_V->Origin) AS rorigin, collect(*), collect(*)[1]->eid as last_eid, collect(*)[1]->rorigin as last_rorigin FROM edgex_events GROUP BY COUNTWINDOW(2, 1) FILTER(  WHERE meta(device) = \"SITE1-L0B_MULTIMETRO_1\" AND SITE1-L0B_MULTIMETRO_1__PHASE_1_V != nil ) "
}
```

- "meta(SITE1-L0B_MULTIMETRO_1__PHASE_1_V->Origin) AS rorigin" is not accepted
- "meta(\"SITE1-L0B_MULTIMETRO_1__PHASE_1_V\"->Origin) AS rorigin" is also not accepted

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
@raycola The dash is actually recognized as minus. Please enclose the object with backtick ```. That is ``meta(`SITE1-L0B_MULTIMETRO_1__PHASE_1_V`->Origin)``

**Comment by ngjaying** [comment]
This is documented in https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/sqls/lexical_elements.md#keywords, so close.
