### ISSUE TITLE
compile and using ZMQ plugin as source, plugin compiled failed

### ISSUE THREAD

**Issue by khemendra0** [lf-edge/ekuiper#935]
Hi everyone,

I am facing issue when try to compile and use zeroMQ plugin

I am try below steps:
1. download code from ekuper:
git@github.com:lf-edge/ekuiper.git

2. enter inside ekuiper folder and run make cmd  (build kuiper)
  It generate _build folder which internaly hase bin, log, plugins, etc folders

3. then compile zmq plugin:
 compile zmq plugin: 
 i. enter inside folder extensions and build the plugin
go build -trimpath --buildmode=plugin -o sources/Zmq.so sources/zmq/zmq.go

This generate Zmq.so file

the  I copied Zmq.so file to build folder bin directory:
  ii. cp Zmq.so ../../_build/kuiper-1.3.0-linux-amd64/plugins/sources/

4. Last I start kuiper like below:
cd _build/kuiper-1.3.0-linux-amd64/bin 
./kuperd

5. now added streams with zmq source
{"sql":"create stream demo () WITH ( datasource = \"Event\", FORMAT = \"json\", KEY = \"temperature\", TYPE = \"zmq\")"}

6. next adding a rule for filter and send data to MQTT broker

Rule adding failed
when chekced log below is error for plugin compile:
**closing rule rule2 for error: cannot open /home/root1/My_Work/EdgeGallery/IIOT_Analaysis/kuiper/install_lfedge/ekuiper/_build/kuiper-1.3.0-linux-amd64/plugins/sources/Zmq.so: plugin.Open(\"/home/root1/My_Work/EdgeGallery/IIOT_Analaysis/kuiper/install_lfedge/ekuiper/_build/kuiper-1.3.0-linux-amd64/plugins/sources/Zmq\"): plugin was built with a different version of package github.com/lf-edge/ekuiper/pkg/api" file="server/ruleManager.go:110**

   
![zmq_compilefailed](https://user-images.githubusercontent.com/30586015/129230922-218cd0ed-aa93-4d93-b3cf-2bfed997afa1.png)

**Comment by ngjaying** [comment]
@khemendra0 The problem is step 3, it is required to run the build command **in the root path of eKuiper** instead of extensions folder.

```sql
go build -trimpath -modfile extensions.mod --buildmode=plugin -o ./_build/$build/plugins/sources/Zmq.so extensions/sources/zmq/zmq.go
```

Please check the updated [plugin tutorial](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md#compile-and-debug-the-plugin) for detail.

**Comment by khemendra0** [comment]
Thank you so much ngjaying , compile is working and I am able to add rule with zmq source :)

But when I testing with zmq source, i am not getting any data to kuiper.
1. my source is zmq
2. sink is mqtt broker


I tested by publisher code and it is fine but data in not getting by kuiper and not sent out to sink
Kindly help

below are snapshot 

![1](https://user-images.githubusercontent.com/30586015/129351203-5ae29049-fc84-4207-aa3a-9aa64f82e8ae.png)
![2](https://user-images.githubusercontent.com/30586015/129351210-206ff5e1-4e3a-4512-9c1f-12adac6cb950.png)
![3](https://user-images.githubusercontent.com/30586015/129351213-b4bf4a3a-9e2f-4bb1-878f-28279e52865c.png)
![4](https://user-images.githubusercontent.com/30586015/129351215-1e68a16c-2f97-4710-9664-28f2bd62e870.png)
![5](https://user-images.githubusercontent.com/30586015/129351218-19975a16-5db6-4562-ac20-1ac905e7368f.png)
![6](https://user-images.githubusercontent.com/30586015/129351219-305570b0-41e4-4aae-9f0e-ae5c7fd4aec1.png)
![7](https://user-images.githubusercontent.com/30586015/129351220-881df9b5-5486-4627-9af8-a2702e212e1b.png)

**Comment by khemendra0** [comment]
I found the reason, it was problem in my application. 
I need to add Event topic to my publish data, then it was working 
Thanks a lot :)

**Comment by khemendra0** [comment]
HI, 
Now i am trying to compile and use plugin inside docker container.
I did only step 3 to compile plugin inside docker container and rerun ./kuiperd

go build -trimpath -modfile extensions.mod --buildmode=plugin -o ./_build/$build/plugins/sources/Zmq.so extensions/sources/zmq/zmq.go

but here also i am getting similiar issue:
![8](https://user-images.githubusercontent.com/30586015/129429527-e36a1d94-f68a-455d-af4f-b720d039ac1d.png)

do we need to build both kuiper and plugin in docker ??
any chnages for kuiper 1.2.1 version which i can see in docker version.  ??

thanks a lot in advance

**Comment by khemendra0** [comment]
Now i tried compile kuiper and zmq plugin both with step 2 and 3 in side docker
in kuiper folder:
1. make
2. go build -trimpath -modfile extensions.mod --buildmode=plugin -o ./_build/$build/plugins/sources/Zmq.so extensions/sources/zmq/zmq.go

now i am gettng different error:
![9](https://user-images.githubusercontent.com/30586015/129430219-635c4187-0831-4f2a-903e-589cf03bc17f.png)

But I checked in my docker container, Zmq.so is compiled and avaible:
![10](https://user-images.githubusercontent.com/30586015/129430247-29a47b5a-bcea-40ad-8bde-5aa0e3fcecde.png)

I am following same link for docker plugin build also:
https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md#compile-and-debug-the-plugin

Is it some difference when building in docker ??

**Comment by khemendra0** [comment]
Now I am trying to compile and use zmq plugin in docker container.

I followed below steps:
1. start conatiner:
docker run -p 9081:9081 -d --name kuiper -e MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883] lfedge/ekuiper:1.3.0
2.  enter inside container "docker exec -it containerID bash"
3. in ekuiper folder, build kuiper
make
4. in ekuiper folder, build zmq plugin:
go build -trimpath -modfile extensions.mod --buildmode=plugin -o ./_build/kuiper-1.3.0-linux-amd64/plugins/sources/Zmq.so extensions/sources/zmq/zmq.go

I can see both kuiper "kuiperd" and zmq binary Zmq.so are generated succesuffuly.

But now I added stream and rule for source as zmq and sink as mqtt.

But it failed as zmq plugin not found
![11](https://user-images.githubusercontent.com/30586015/129431020-55348116-8121-40d4-85cc-3981e3bd179f.png)

Kindly help

**Comment by ngjaying** [comment]
@khemendra0 It seems you need to restart the docker container to reload the plugins or use REST API/CLI to register the new plugin in runtime.

By the way, step 3 is not needed in the docker as it already built the eKuiper main program when creating the docker image. And it is supposed not to be changed to make sure it is exactly the same env as the production docker image.

**Comment by ngjaying** [comment]
@khemendra0 Additionally, we have pre-built zip file for shipped plugins like zmq. You can install it by REST API as below. Change the version and arch in the url to match your env.

```shell
curl -X POST --location "http://127.0.0.1:9081/plugins/sinks" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"zmq\", \"file\": \"https://packages.emqx.io/kuiper-plugins/1.3.0/debian/sinks/zmq_amd64.zip\"}"
```
