### ISSUE TITLE
EdgeX data is different after kuiper processing

### ISSUE THREAD

**Issue by dmocek-o** [lf-edge/ekuiper#956]
**Environment**:
- EdgeX Foundry Ireland release: v2.0.0
- eKuiper version (e.g. `1.3.0`): v1.2.1
- Hardware configuration (e.g. `lscpu`): 64-bit Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
- OS (e.g. `cat /etc/os-release`): Elementary OS v6

**What happened and what you expected to happen**:
This is the data being sent by EdgeX's device-mqtt service to Redis:
{apiVersion='v2', deviceName='MQ_DEVICE', origin='1629330844003819484', profileName='Oracle-Test-Device-MQTT-Profile', sourceName='humidity', edgexReadings=[EdgexReading{binaryValue='null', deviceName='MQ_DEVICE', id='6907c231-9b10-4d5b-8d10-01e173446686', mediaType='', origin='1629330844003754666', resourceName='humidity', profileName='Oracle-Test-Device-MQTT-Profile', value='64', valueType='Int32'}]}

This is the data Kuiper is sending to Redis after processing:
{"apiVersion":"v2","id":"f8bd6e13-25b4-4cd2-85b6-85cac7f5909c","deviceName":"","profileName":"kuiperProfile","sourceName":"ekuiper-events","origin":1629330844010732167,"readings":[{"id":"c5cba92f-7666-44ed-8177-57e275dffce7","origin":1629330844011738874,"deviceName":"","resourceName":"humidity","profileName":"kuiperProfile","valueType":"Float64","binaryValue":null,"mediaType":"","value":"6.400000e+01"}]}

This is my Kuiper Rule:
curl -X POST \
         http://$kuiper_docker:$kuiper_port/rules \
         -H 'Content-Type: application/json' \
         -d '{
         "id": "tempHumidity-rule",
         "sql": "SELECT meta(*) AS edgex_meta, temperature, humidity FROM demo WHERE (temperature >= 60 AND temperature <= 80) OR (humidity >= 60 AND humidity <= 80)",
         "actions": [
             {
                 "log":{},
                 "edgex": {
                     "contentType": "application/json",
                     "host": "edgex-redis",
                     "messageType": "request",
                     "port": 6379,
                     "protocol": "redis",
                     "topic": "ekuiper-events",
                     "type": "redis"
                 }
             }
         ]
         }'

Kuiper is changing the data:
- The deviceName is missing in the kuiper data, in both the payload and reading.
- The profileName changes to kuiperProfile in the kuiper data in both the payload and reading.
- The data type changes from Int32 to Float64
- The value changes from Int32 to Float64

**How to reproduce it (as minimally and precisely as possible)**:
A simulated MQTT device is sending data to the MQTT broker defined in the EdgeX Ireland release's docker-compose.  The values are all Int32's.  EdgeX is configured to use the redis message bus.  Core Data is not running.  EdgeX's device-mqtt is getting data from the MQTT broker and sending it to redis.  Kuiper is configured to get the data from redis, filter it, and send the data back to redis using the 'ekuiper-events' channel.

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
@dmocek-o This is expected and well documented.  By default, eKuiper will overwrite the metadata as if itself is a virtual device. If you need to keep original metadata, you'll need to specify the `metadata` property and point to your selected field for meta. Check [Keep original metadata](https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/rules/sinks/edgex.md#publish-result-to-a-new-edgex-message-bus-keeping-original-metadata).

**Comment by dmocek-o** [comment]
It turns out I was missing one entry in my rule:

"metadata": "edgex_meta",

adding this solved my issue.
