### ISSUE TITLE
Support setting configuration through environment variable

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#962]
Allow to setup configurations by environment variable.

**What would you like to be added/modified**:
Currently only docker image can set the configuration through env. It will be better to extend the support to local run.

**Why is this needed**:
This is inspired by the request of snap for [this issue](https://github.com/edgexfoundry/edgex-go/issues/3676#issuecomment-901975089).

**Comment by ngjaying** [comment]
Due to deb/rpm problem of writing to config file, we may need to load the env but not writing to file.

**Comment by rwadowski** [comment]
@ngjaying hi, I can take this one

**Comment by rwadowski** [comment]
As I mentioned in other issue - maybe usage of hocon would be useful however I don't know whether this idea has been dropped or considered

**Comment by ngjaying** [comment]
Thanks. About the hocon, the main concern is that the CI may be broken for format change. And the backward compatibility of previous users/tools is another obstacle.

**Comment by rwadowski** [comment]
> Thanks. About the hocon, the main concern is that the CI may be broken for format change. And the backward compatibility of previous users/tools is another obstacle.

Indeed so I will write something to handle configs from env. By default every config will be read from file however any env variable associated with the given config will overwrite it.

**Comment by ngjaying** [comment]
> Indeed so I will write something to handle configs from env. By default every config will be read from file however any env variable associated with the given config will overwrite it.

Sounds good.

> Another options is too suport two formats, legacy one as it is, and hocon one with defined priority...

I think it is confusing to have two formats but brings little benefits. I do not favor this idea.

**Comment by rwadowski** [comment]
> I think it is confusing to have two formats but brings little benefits. I do not favor this idea.

Ok, so lets drop hocon topic
