### ISSUE TITLE
Can kuiper rules be created from deviceName？

### ISSUE THREAD

**Issue by FengZeHe** [lf-edge/ekuiper#968]
Hi, I use Kuiper to filter the data and add it to TDengine. Currently I have two devices, `PowerData3` and `PowerData5`. At the same time, there are data tables `mainvolt3` and `mainvolt5`in the TDengine. 
This is the rules,
![image](https://user-images.githubusercontent.com/25740210/130426381-835d587c-2bab-4e63-b1a9-e298df6e4179.png)

but when the data is sent both rules match. 

![select3](https://user-images.githubusercontent.com/25740210/130426664-f8fb8e6c-18b5-430a-b1e3-5c3190219838.png)
![select2](https://user-images.githubusercontent.com/25740210/130426708-2e18ed70-5c78-40bc-b85c-4a540ac13e14.png)

I want Kuiper's rules to distinguish between data from two devices. **I want to filter the deviceName from the metadata and send the data separately to different databases,** and I don't know how to do that. Please help me, thanks!

**Comment by ngjaying** [comment]
What is your rule `mainvolt-5`? 

You can try rule like:
```
SELECT mainvoltage FROM Powerdata WHERE isNull(mainVoltage) = false AND meta(deviceName)="PowerData-5"
```

**Comment by FengZeHe** [comment]
> What is your rule `mainvolt-5`?
> 
> You can try rule like:
> 
> ```
> SELECT mainvoltage FROM Powerdata WHERE isNull(mainVoltage) = false AND meta(deviceName)="PowerData-5"
> ```

Thanks for your help, I solved the problem!

**Comment by ngjaying** [comment]
@FengZeHe Just inspired by your scenario, you might want to set the table name dynamically so that you can use a single rule to do all this work. Let's think about if this is possible and how to design the usage.
