### ISSUE TITLE
Feature Request : add the sTable field to the TDengine Plugin ？

### ISSUE THREAD

**Issue by FengZeHe** [lf-edge/ekuiper#982]
STable in TDengine has the ability to create tables automatically. Using sTable templates, you can create a table automatically without having to create a database before inserting data.
![image](https://user-images.githubusercontent.com/25740210/131081320-40140ba7-ea84-41c6-8809-4cd881ed0a9b.png)

Could you add a sTable option in the future? This will enable the database to build tables without additional connections.Thank you very much！

**Comment by ngjaying** [comment]
Check the doc to see if it meets your requirement: https://ekuiper.org/docs/zh/latest/rules/sinks/plugin/tdengine.html#%E8%A7%84%E5%88%99-actions-%E8%AF%B4%E6%98%8E
