### ISSUE TITLE
STRICT_VALIDATION = "False" not working as expected to place default current time!

### ISSUE THREAD

**Issue by nhossaincse** [lf-edge/ekuiper#987]
I am using EdgeX type stream. 

My steam schema is as below:
create stream s1(magtec string, InsertTime datetime) WITH (FORMAT = \"json\", TYPE = \"edgex\", STRICT_VALIDATION = \"False\")

When I send payload like below:
[{"magtec":"[{\"Property\":001}]"}]

Getting error as:
[{"error":"error in preprocessor: invalid data map[magtec:[{"Property":001}]], field InsertTime not found"}]
But as per documentation as I set STRICT_VALIDATION  as false, should set the value for the InsertTime property as the current time.
https://docs.emqx.io/en/kuiper/latest/sqls/streams.html#strict-validation

Please help on this matter.

**Comment by nhossaincse** [comment]
Dear Team,

I was using 1.2.1-alpine. When you are planning to update it in docker hub, here?
https://hub.docker.com/r/emqx/kuiper/tags?page=1&ordering=last_updated

**Comment by ngjaying** [comment]
This is planned at 1.3.1.  And it should be released soon.
