### ISSUE TITLE
Error happened when created 180 rules

### ISSUE THREAD

**Issue by wallace-hu** [lf-edge/ekuiper#989]
**Environment**:
- eKuiper version (`1.1.2`): 1.12
- Hardware configuration (): RISC-V
- OS (e.g. `cat /etc/os-release`):Linux

**What happened and what you expected to happen**:
After created over about 600 rules in my application, I got below errors:

time="2021-08-30 11:42:52" level=warning msg="sink node rest_0 instance 0 publish { \"deviceId\": \"D59eGSxy_f000b8\" ,\"mid\": \"7\" } error: rest sink fails to send out the data: Put \"http://127.0.0.1:50108/api/v1/device/name/res_temperature_f000b8_ABFFFFFFFFFFFFFF/addresponse\": dial tcp 127.0.0.1:50108: socket: too many open files" file="nodes/sink_node.go:285" rule=restRule_adddevice_res_temperature_f000b8_ABFFFFFFFFFFFFFF
2021/08/30 11:42:52 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:53 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:54 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:55 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:56 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:57 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:58 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:42:59 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:00 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:01 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:02 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:09 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
time="2021-08-30 11:43:08" level=warning msg="sink node rest_0 instance 0 publish { \"deviceId\": \"D59eGSxy_f000b8\" ,\"mid\": \"7\" } error: rest sink fails to send out the data: Put \"http://127.0.0.1:50108/api/v1/device/name/res_temperature_f000b8_ABFFFFFFFFFFFFFF/addresponse\": dial tcp 127.0.0.1:50108: socket: too many open files" file="nodes/sink_node.go:285" rule=restRule_adddevice_res_temperature_f000b8_ABFFFFFFFFFFFFFF
2021/08/30 11:43:10 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:11 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:12 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:13 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:14 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
time="2021-08-30 11:43:14" level=warning msg="sink node rest_0 instance 0 publish { \"deviceId\": \"D59eGSxy_f000b8\" ,\"mid\": \"7\" } error: rest sink fails to send out the data: Put \"http://127.0.0.1:50108/api/v1/device/name/res_temperature_f000b8_ABFFFFFFFFFFFFFF/addresponse\": dial tcp 127.0.0.1:50108: socket: too many open files" file="nodes/sink_node.go:285" rule=restRule_adddevice_res_temperature_f000b8_ABFFFFFFFFFFFFFF
2021/08/30 11:43:15 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:16 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:17 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:18 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:19 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:20 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:21 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:22 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:23 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:24 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s
2021/08/30 11:43:25 http: Accept error: accept tcp [::]:20498: accept4: too many open files; retrying in 1s

In that time, I try to show all the ruls with ./kuiper show rules,  It freezd in "Connecting to 127.0.0.1:20498"

root@exaleapsemi-r2:~/semi_edgex/ekuiper-1.1.2/_build/kuiper--linux-riscv64/bin# ./kuiper show rules
Connecting to 127.0.0.1:20498... 

Is it  a known issue? What's the reason and how to fix it?

**Comment by SuperRxan** [comment]
Hi @wallace-hu .
I tried to reproduce this issue but no luck, please try 1.3.1 that will release in two days.
If the problem stil exist, please give us feedback
