### ISSUE TITLE
Is it possible in ekuiper sql, extracting time difference like sql?

### ISSUE THREAD

**Issue by iamonlysaiful** [lf-edge/ekuiper#992]
I have two question about time difference related query,

1. Is it possible to query like tsql
`SELECT datediff(minute, startdatetime, enddatetime) from demo` 
2. Can print time difference of stream windows(e.g. sliding window)'s between first event and last event of specific interval.

**Comment by SuperRxan** [comment]
for the first question, I think we do not have yet
for the second, you can try the
``window_start()  & window_end() function``
```
select avg(humidity) as avg_hum, window_end() - window_start() as time_diff from demo2 GROUP BY TUMBLINGWINDOW(ss, 10);
Query was submit successfully.
kuiper > [{"avg_hum":15,"time_diff":9971}]
```

**Comment by iamonlysaiful** [comment]
I'm  using `emqx/kuiper:1.2.1-alpine` , which is using with edgex compose file.
from which version ` window_end() , window_start()` these function supported?

**Comment by SuperRxan** [comment]
good question !!!

we add these function since this release
https://github.com/lf-edge/ekuiper/releases/tag/1.3.0

and you can find the image here
https://registry.hub.docker.com/r/lfedge/ekuiper/tags?page=1&ordering=last_updated

**Comment by iamonlysaiful** [comment]
this version of ekuiper return this errorn when I am tyring to run with `edgex-ireland` compose file
![image](https://user-images.githubusercontent.com/25750962/131465327-5779cae1-19db-4f20-b3f2-9a8faf5cd366.png)

**Comment by SuperRxan** [comment]
you can remove this line in compose config
``user: kuiper: kuiper``
