### ISSUE TITLE
can not call aggregate valuer  alias in HAVING clause

### ISSUE THREAD

**Issue by SuperRxan** [lf-edge/ekuiper#995]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.3.0
- Hardware configuration (e.g. `lscpu`): all
- OS (e.g. `cat /etc/os-release`): linux
- Others:

**What happened and what you expected to happen**:

can not call aggregate valuer  alias in HAVING clause
```
SELECT collect(*)[0] as last FROM events INNER JOIN homeEvents ON events.homeId=homeEvents.homeId GROUP BY SlidingWindow(ss,5) HAVING last.temperature > 30 AND last.windowDegree < 30 Order By events.ts DESC
Not allowed to call non-aggregate functions in HAVING clause.

SELECT max(collect(temperature)) as last FROM events INNER JOIN homeEvents ON events.homeId=homeEvents.homeId GROUP BY SlidingWindow(ss,5) HAVING last.temperature > 30 AND last.windowDegree < 30 Order By events.ts DESC
Not allowed to call non-aggregate functions in HAVING clause.
```

can only call in this way
```
SELECT collect(*)[0] as last FROM events INNER JOIN homeEvents ON events.homeId=homeEvents.homeId GROUP BY SlidingWindow(ss,5) HAVING collect(temperature)[0] > 30 AND collect(windowDegree)[0] < 30 Order By events.ts DESC
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
The problem is in `last.temperature` which last is just a field, not a stream. Should use `last->temperature` instead. However, this is still a bug because the error message is ambiguous.
