### ISSUE TITLE
How to get the latest value according to the window

### ISSUE THREAD

**Issue by nickscut** [lf-edge/ekuiper#999]
Is there a function similar to Flink LAST_VALUE function

**Comment by nickscut** [comment]
LAST_VALUE function

**Comment by ngjaying** [comment]
@nickscut It is proposed #727 but not supported yet. You can use collect function to do the same.
```sql
SELECT collect(*)[-1] as last FROM demo GROUP BY TumblingWindow(ss, 10)
```
